/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Technical_Services;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.RootPaneContainer;

/**
 *
 * @author user
 */
public class complain extends javax.swing.JPanel {

    /**
     * Creates new form complains
     */boolean complainViewMode=false,jobViewMode=false;
     
      //default table loading query
      TechnicalServiceDbAcess obtComplain = new TechnicalServiceDbAcess();
      String sqlJob = "select j.jobId as 'Job ID',c.itemId as 'Item ID',j.jobDate as 'Job Date',j.complainId as 'Complain ID' ,c.status as 'Status',c.technician as 'Technician Id' ,c.employeeId as 'Employee Id' from job j, complain c where j.complainId = c.complainId";
      String sqlComplain = "SELECt complainId AS 'Complain ID',itemId AS 'Item ID',complainDate AS 'Complain Date',status AS 'Status',fault AS Fault,employeeId AS 'Employee ID',technician  AS Technicion FROM complain";
    
     public complain() {
        
        initComponents();
         
        btn495.setEnabled(false);
        //add buttons to group
        buttonGroup1.add(rbtn406);
        buttonGroup1.add(rbtn405);
        
        buttonGroup2.add(rbtn407);
        buttonGroup2.add(rbtn408);
        
        buttonGroup3.add(rdbtn401);
        buttonGroup3.add(rdbtn402);
        buttonGroup3.add(rdbtn403);
        
        btn405.setEnabled(false);
        btn405.setEnabled(false);
        bnt406.setEnabled(false);
        
        //set selecte radio button(graph)
        rbtn405.setSelected(true);
        rbtn408.setSelected(true);
        rdbtn401.setSelected(true);
        
        
        //set date(graph panel)
        DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
         try{
        jDateChooser422.setDate(df.parse(dateAndTime.getDateAndTime("dd-MM-yyyy")));
        jDateChooser421.setDate(df.parse("01-01-2014"));
         }catch(Exception e){}
        
            //set date in panel
          lbl431.setText(dateAndTime.getDateAndTime("dd MMMMM yyyy"));
          lbl432.setText(dateAndTime.getDateAndTime("dd MMMMM yyyy"));
          //set value for combobox
          
          //set visibility "!" lable
          
         lbl400.setVisible(false);
         lbl401.setVisible(false);
         lbl402.setVisible(false);
         jLabel1.setVisible(false);
         jLabel3.setVisible(false);
         jLabel4.setVisible(false);
         jLabel2.setVisible(false);
         
        
          //add items to comboboxs
        
       
        obtComplain.setTechnicionID(cmb401);
        
        cmb400.addItem("Electrical");
        cmb400.addItem("Mechnical");
       

       //add data to tables
             
       String sqlNumber ="SELECT technician as Technicion , count(complainId) as 'Number of Complains'  from complain where status = 'Checking' group by technician";
       
       obtComplain.fillTable(tbl402, sqlComplain);
       obtComplain.fillTable(tbl401, sqlJob);
       obtComplain.fillTable(tbl400, sqlNumber);
      
      //get complain id and job id
       String complainId=obtComplain.GetIncrementedId("complain","complainID");
       txtF400.setText(complainId);
             
       txtF405.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cmb400 = new javax.swing.JComboBox<>();
        cmb401 = new javax.swing.JComboBox<>();
        btn400 = new javax.swing.JButton();
        txtF401 = new javax.swing.JTextField();
        jScrollPane12 = new javax.swing.JScrollPane();
        tbl400 = new javax.swing.JTable();
        lbl402 = new javax.swing.JLabel();
        lbl400 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtF402 = new javax.swing.JTextField();
        lbl401 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtF400 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        txtAr400 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jpnl429 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtF426 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl402 = new javax.swing.JTable();
        jPanel12 = new javax.swing.JPanel();
        lbl431 = new javax.swing.JLabel();
        jpnl430 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAr435 = new javax.swing.JTextArea();
        btn405 = new javax.swing.JButton();
        btn495 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl401 = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        lbl432 = new javax.swing.JLabel();
        jpnl431 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAr437 = new javax.swing.JTextArea();
        bnt406 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        txtF427 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jDateChooser421 = new com.toedter.calendar.JDateChooser();
        jDateChooser422 = new com.toedter.calendar.JDateChooser();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        rbtn405 = new javax.swing.JRadioButton();
        txtF405 = new javax.swing.JTextField();
        rbtn406 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        rbtn407 = new javax.swing.JRadioButton();
        rbtn408 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rdbtn401 = new javax.swing.JRadioButton();
        rdbtn402 = new javax.swing.JRadioButton();
        rdbtn403 = new javax.swing.JRadioButton();

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 783, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 490, Short.MAX_VALUE)
        );

        jButton6.setText("jButton6");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 590));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(790, 590));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(790, 590));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(790, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel11.setText("Iteam ID");
        jLabel11.setName("lbl425"); // NOI18N

        jLabel13.setText("Fault Type");
        jLabel13.setName("lbl427"); // NOI18N

        jLabel14.setText("Technician ID");
        jLabel14.setName("lbl428"); // NOI18N

        cmb400.setName("cmb400"); // NOI18N
        cmb400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb400ActionPerformed(evt);
            }
        });

        cmb401.setName("cmb401"); // NOI18N
        cmb401.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb401ActionPerformed(evt);
            }
        });
        cmb401.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb401KeyReleased(evt);
            }
        });

        btn400.setText("Add");
        btn400.setName("btn427"); // NOI18N
        btn400.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn400ActionPerformed(evt);
            }
        });

        txtF401.setName("txtF401"); // NOI18N

        tbl400.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Name", "Number of complains"
            }
        ));
        tbl400.setPreferredSize(new java.awt.Dimension(150, 150));
        tbl400.setRowHeight(25);
        jScrollPane12.setViewportView(tbl400);

        lbl402.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl402.setForeground(new java.awt.Color(255, 0, 0));
        lbl402.setText("!");
        lbl402.setName("lbl434"); // NOI18N

        lbl400.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl400.setForeground(new java.awt.Color(255, 0, 0));
        lbl400.setText("!");
        lbl400.setName("lbl434"); // NOI18N

        jLabel12.setText("Employee ID");

        lbl401.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lbl401.setForeground(new java.awt.Color(255, 0, 0));
        lbl401.setText("!");
        lbl401.setName("lbl401"); // NOI18N

        jLabel18.setText("Complain ID");

        txtF400.setEditable(false);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Discription"));

        txtAr400.setColumns(20);
        txtAr400.setRows(5);
        txtAr400.setName("txtAr422"); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 3, Short.MAX_VALUE)
                .addComponent(txtAr400, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(0, 2, Short.MAX_VALUE)
                .addComponent(txtAr400, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel18)
                .addGap(61, 61, 61)
                .addComponent(txtF400, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addGap(53, 53, 53)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF401, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb400, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtF402, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb401, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl400)
                    .addComponent(lbl401, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(lbl402, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(535, 535, 535)
                .addComponent(jButton2)
                .addGap(36, 36, 36)
                .addComponent(btn400, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtF400, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(txtF401, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cmb400, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(txtF402, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(cmb401, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(lbl400)
                        .addGap(66, 66, 66)
                        .addComponent(lbl401))
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lbl402)))
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn400)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setName("lbl431"); // NOI18N

        jpnl429.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setForeground(new java.awt.Color(153, 153, 153));
        jLabel15.setText("Complain ID / Employee ID / Iteam ID / Date / Job ID");
        jLabel15.setName("lbl430"); // NOI18N

        txtF426.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtF426.setName("txtF422"); // NOI18N
        txtF426.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF426ActionPerformed(evt);
            }
        });
        txtF426.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtF426KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF426KeyReleased(evt);
            }
        });

        tbl402.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Complain ID", "Item id", "Complain Date", "Status", "Fault", "Employee Id", "Technicion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl402.setName("tbl402"); // NOI18N
        tbl402.setRowHeight(25);
        tbl402.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl402MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl402MouseEntered(evt);
            }
        });
        jScrollPane4.setViewportView(tbl402);
        if (tbl402.getColumnModel().getColumnCount() > 0) {
            tbl402.getColumnModel().getColumn(0).setResizable(false);
            tbl402.getColumnModel().getColumn(1).setResizable(false);
            tbl402.getColumnModel().getColumn(2).setResizable(false);
            tbl402.getColumnModel().getColumn(3).setResizable(false);
            tbl402.getColumnModel().getColumn(4).setResizable(false);
            tbl402.getColumnModel().getColumn(5).setResizable(false);
            tbl402.getColumnModel().getColumn(6).setResizable(false);
        }

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Date "));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lbl431, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(lbl431, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnl430.setBackground(new java.awt.Color(255, 255, 255));
        jpnl430.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        txtAr435.setColumns(20);
        txtAr435.setRows(5);
        jScrollPane1.setViewportView(txtAr435);

        btn405.setText("Create Job");
        btn405.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn405ActionPerformed(evt);
            }
        });

        btn495.setText("Report");
        btn495.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn495ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl430Layout = new javax.swing.GroupLayout(jpnl430);
        jpnl430.setLayout(jpnl430Layout);
        jpnl430Layout.setHorizontalGroup(
            jpnl430Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl430Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpnl430Layout.createSequentialGroup()
                .addGap(507, 507, 507)
                .addComponent(btn495)
                .addGap(18, 18, 18)
                .addComponent(btn405, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnl430Layout.setVerticalGroup(
            jpnl430Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl430Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jpnl430Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn405, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn495)))
        );

        jButton1.setText("View Checking");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl429Layout = new javax.swing.GroupLayout(jpnl429);
        jpnl429.setLayout(jpnl429Layout);
        jpnl429Layout.setHorizontalGroup(
            jpnl429Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl429Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpnl429Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl429Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtF426, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addGap(28, 28, 28)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpnl429Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpnl429Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpnl430, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnl429Layout.setVerticalGroup(
            jpnl429Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl429Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpnl429Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl429Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpnl429Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnl429Layout.createSequentialGroup()
                                .addComponent(txtF426, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton1))))
                .addGap(7, 7, 7)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpnl430, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Complains", jpnl429);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        tbl401.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Job ID", "Job Date", "Complain Id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl401.setName("tbl401"); // NOI18N
        tbl401.setRowHeight(25);
        tbl401.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl401MouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl401);
        if (tbl401.getColumnModel().getColumnCount() > 0) {
            tbl401.getColumnModel().getColumn(0).setResizable(false);
            tbl401.getColumnModel().getColumn(1).setResizable(false);
            tbl401.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder("Date "));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl432, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(lbl432, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        jpnl431.setBackground(new java.awt.Color(255, 255, 255));
        jpnl431.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        txtAr437.setColumns(20);
        txtAr437.setRows(5);
        jScrollPane2.setViewportView(txtAr437);

        bnt406.setText("Done");
        bnt406.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnt406ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl431Layout = new javax.swing.GroupLayout(jpnl431);
        jpnl431.setLayout(jpnl431Layout);
        jpnl431Layout.setHorizontalGroup(
            jpnl431Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl431Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jpnl431Layout.createSequentialGroup()
                .addGap(596, 596, 596)
                .addComponent(bnt406, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnl431Layout.setVerticalGroup(
            jpnl431Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl431Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(bnt406, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel16.setForeground(new java.awt.Color(153, 153, 153));
        jLabel16.setText("Complain ID / Employee ID / Iteam ID / Date");
        jLabel16.setName("lbl430"); // NOI18N

        txtF427.setName("txtF422"); // NOI18N
        txtF427.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF427ActionPerformed(evt);
            }
        });
        txtF427.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtF427KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF427KeyReleased(evt);
            }
        });

        jButton3.setText("View Repairing");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF427, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(76, 76, 76)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 760, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpnl431, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(txtF427, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jButton3))))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jpnl431, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Jobs", jPanel10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 560, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("View", jPanel2);

        jPanel27.setBackground(new java.awt.Color(255, 255, 255));

        jPanel28.setBackground(new java.awt.Color(255, 255, 255));
        jPanel28.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Duration"));

        jLabel28.setText("From ");

        jLabel29.setText("To");

        javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(jPanel28);
        jPanel28.setLayout(jPanel28Layout);
        jPanel28Layout.setHorizontalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(26, 26, 26)
                        .addComponent(jDateChooser421, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel28Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(45, 45, 45)
                        .addComponent(jDateChooser422, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel28Layout.setVerticalGroup(
            jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel28Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel28)
                    .addComponent(jDateChooser421, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel28Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(jDateChooser422, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel29.setBackground(new java.awt.Color(255, 255, 255));
        jPanel29.setBorder(javax.swing.BorderFactory.createTitledBorder("Item"));

        rbtn405.setText("All");
        rbtn405.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn405ActionPerformed(evt);
            }
        });

        rbtn406.setText("One Item");
        rbtn406.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtn406ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("!");

        javax.swing.GroupLayout jPanel29Layout = new javax.swing.GroupLayout(jPanel29);
        jPanel29.setLayout(jPanel29Layout);
        jPanel29Layout.setHorizontalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn405)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addComponent(rbtn406)
                        .addGap(8, 8, 8)
                        .addComponent(txtF405, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel29Layout.setVerticalGroup(
            jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel29Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(rbtn405)
                .addGap(4, 4, 4)
                .addGroup(jPanel29Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtn406)
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(txtF405, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel29Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))))
        );

        jButton10.setText("Create");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel30Layout = new javax.swing.GroupLayout(jPanel30);
        jPanel30.setLayout(jPanel30Layout);
        jPanel30Layout.setHorizontalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );
        jPanel30Layout.setVerticalGroup(
            jPanel30Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Arange By"));

        rbtn407.setText("Month");

        rbtn408.setText("Year");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(rbtn408)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(rbtn407)
                .addGap(43, 43, 43))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn408)
                    .addComponent(rbtn407))
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("There are no records about this Item");

        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("!");

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("!");

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph Type"));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rdbtn401.setText("Pie Chart");
        jPanel3.add(rdbtn401, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        rdbtn402.setText("Line Chart");
        jPanel3.add(rdbtn402, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        rdbtn403.setText("Bar Chart");
        jPanel3.add(rdbtn403, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        javax.swing.GroupLayout jPanel27Layout = new javax.swing.GroupLayout(jPanel27);
        jPanel27.setLayout(jPanel27Layout);
        jPanel27Layout.setHorizontalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(3, 3, 3)
                .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel27Layout.setVerticalGroup(
            jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGroup(jPanel27Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel3)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel4))
                    .addGroup(jPanel27Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jPanel30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel27Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jPanel29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout jPanel26Layout = new javax.swing.GroupLayout(jPanel26);
        jPanel26.setLayout(jPanel26Layout);
        jPanel26Layout.setHorizontalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel26Layout.setVerticalGroup(
            jPanel26Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel27, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Graphs", jPanel26);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbl402MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl402MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl402MouseEntered

    private void tbl402MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl402MouseClicked
        String selected = (String) tbl402.getModel().getValueAt(tbl402.getSelectedRow(),0);
        
        TechnicalServiceDbAcess obtCom = new TechnicalServiceDbAcess("complain");
        obtCom.getdiscription(selected, txtAr435, "complainId");
        
        
        String sql = "select status from complain where complainId = '"+selected+"'";
        if(obtCom.hasAJob(sql,"Checking"))
            btn405.setEnabled(true);
        else
            btn405.setEnabled(false);
        btn495.setEnabled(true);
    }//GEN-LAST:event_tbl402MouseClicked

    private void tbl401MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl401MouseClicked
       
        String selected = (String) tbl401.getModel().getValueAt(tbl401.getSelectedRow(),0);
        TechnicalServiceDbAcess obtJob = new TechnicalServiceDbAcess("job");
        obtJob.getdiscription(selected, txtAr437, "jobId");
        
        
        String selected2 = (String) tbl401.getModel().getValueAt(tbl401.getSelectedRow(),3);
        
        String sql = "select status from complain where complainId = '"+selected2+"'";
        if(obtJob.hasAJob(sql,"Repairing"))
            bnt406.setEnabled(true);
        else
            bnt406.setEnabled(false);
        
    }//GEN-LAST:event_tbl401MouseClicked

    private void btn405ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn405ActionPerformed
       
        String selected = (String) tbl402.getModel().getValueAt(tbl402.getSelectedRow(),0);
          this.setEnabled(false);
        CreateJobNEw cn = new CreateJobNEw(selected,tbl402);
        cn.setVisible(true);
        
        
      
      
        
    }//GEN-LAST:event_btn405ActionPerformed

    private void txtF426ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF426ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF426ActionPerformed

    private void txtF426KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF426KeyReleased
        
        String searchId = txtF426.getText();        
        
        textValidator obtCom = new  textValidator();
        TechnicalServiceDbAcess obtSearch =new  TechnicalServiceDbAcess();
        
        if(!obtCom.isNull(searchId)){
        
        obtSearch.searchingComplain(tbl402, searchId);
        
        }
        else{
            
        String sqlCom= "SELECt complainId AS 'Complain ID',itemId AS 'Item ID',complainDate AS 'Complain Date',status AS 'Status',fault AS Fault,employeeId AS 'Employee ID',technicion  AS Technicion FROM complain ";
        obtSearch.fillTable(tbl402, sqlCom);
        }
        
        
    }//GEN-LAST:event_txtF426KeyReleased

    private void bnt406ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnt406ActionPerformed
    String selected = (String) tbl401.getModel().getValueAt(tbl401.getSelectedRow(),3); 
    TechnicalServiceDbAcess obtStatus = new TechnicalServiceDbAcess();
    obtStatus.setStatus(selected,"Done");
    obtComplain.fillTable(tbl401, sqlJob);
    
      JFrame parent = new JFrame();
      JOptionPane.showMessageDialog(parent, "Finished Job");  
    }//GEN-LAST:event_bnt406ActionPerformed

    private void txtF427ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF427ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF427ActionPerformed

    private void txtF427KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF427KeyReleased
         String searchId = txtF427.getText(); 
         int length = txtF427.getText().length();
        
        textValidator obtCom = new  textValidator();
        TechnicalServiceDbAcess obtSearch =new  TechnicalServiceDbAcess();
        
        if(length > 0){
        
        obtSearch.searchingJob(tbl401, searchId);
        
        }
        else{
            
        obtSearch.fillTable(tbl401, sqlJob);
        }
        
    }//GEN-LAST:event_txtF427KeyReleased

    private void btn400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn400ActionPerformed
        lbl402.setVisible(false);
        lbl400.setVisible(false);
         lbl401.setVisible(false);
         
        //validation
        boolean check  = true;
        
        textValidator obtc = new textValidator();
        if(obtc.isNull(txtAr400.getText())){
        lbl402.setVisible(true);
        }
        
        
       TechnicalServiceDbAcess obt = new TechnicalServiceDbAcess();
         if(!obt.checkAvalability("machinery", "machineId", txtF401.getText()) && !obt.checkAvalability("plant", "plantId",  txtF401.getText()) && !obt.checkAvalability("vehicle", "vehicleNo",  txtF401.getText())) {
             lbl400.setVisible(true);
             check =false;
        }
        if(!obt.checkAvalability("employee","employeeId",txtF402.getText())){
         lbl401.setVisible(true);
        }
         
        //store data
        if(check && obt.checkAvalability("employee","employeeId",txtF402.getText()) && !obtc.isNull(txtAr400.getText())){
        TechnicalServiceDbAcess obtAddAcompalin = new TechnicalServiceDbAcess();
        obtAddAcompalin.addComplain(txtF400.getText(),txtF401.getText().toUpperCase(),dateAndTime.getDateAndTime("yyyy-MM-dd"),"Checking",txtAr400.getText(),cmb400.getSelectedItem().toString(),txtF402.getText().toUpperCase(),cmb401.getSelectedItem().toString());
        
      JFrame parent = new JFrame();
      JOptionPane.showMessageDialog(parent, "Complain Added");
      
      //genarate a report
      
          JDialog.setDefaultLookAndFeelDecorated(true);
          int response = JOptionPane.showConfirmDialog(null, "Do you want generate a report ?", "Confirm",
          JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
          
          if (response == JOptionPane.YES_OPTION) {
              HashMap param=new HashMap();
              param.put("comId",txtF400.getText());
              Technical_Services_main report=new Technical_Services_main("src\\technicalServiceIReport\\newComplain.jasper",param);
              report.setVisible(true);
          }
          
    
        //reload page
        SetPanel obtP = new SetPanel();
        complain obtC= new complain();
        obtP.SetPanel(obtC);
        }
    }//GEN-LAST:event_btn400ActionPerformed

    private void cmb400ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb400ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb400ActionPerformed

    private void cmb401KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb401KeyReleased
        
    }//GEN-LAST:event_cmb401KeyReleased

    private void txtF427KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF427KeyPressed
         String searchId = txtF427.getText();     
         int length = txtF427.getText().length();
        
        textValidator obtCom2 = new  textValidator();
        TechnicalServiceDbAcess obtSearch2 =new  TechnicalServiceDbAcess();
        
        if(length < 0){
        
        String sqlJob= "select j.jobId as 'Job ID',j.jobDate as 'Job Date',j.complainId as 'Complain ID' ,c.status as 'Status',c.technician as 'Technician Id' ,c.employeeId as 'Employee Id' from job j, complain c where j.complainId = c.complainId";
        obtSearch2.fillTable(tbl401, sqlJob);
        
        }
       
    }//GEN-LAST:event_txtF427KeyPressed

     public void setComplain(String itemId,String discription){
        txtF401.setText(itemId);
        txtAr400.setText(discription);
     }
    
    private void txtF426KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF426KeyPressed
        int length = txtF426.getText().length();
        String sqlComplain = "SELECt complainId AS 'Complain ID',itemId AS 'Item ID',complainDate AS 'Complain Date',status AS 'Status',fault AS Fault,employeeId AS 'Employee ID',technician  AS Technicion FROM complain";
         
        
        if(length < 1){
        TechnicalServiceDbAcess obtComplain = new TechnicalServiceDbAcess();
        obtComplain.fillTable(tbl402, sqlComplain);
        
        }
       
    }//GEN-LAST:event_txtF426KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         TechnicalServiceDbAcess obtmode =new  TechnicalServiceDbAcess();
         String sqlChecking= "SELECt complainId AS 'Complain ID',itemId AS 'Item ID',complainDate AS 'Complain Date',status AS 'Status',fault AS Fault,employeeId AS 'Employee ID',technician  AS Technicion FROM complain WHERE status = 'Checking'";
        if(complainViewMode == false){
         obtmode.fillTable(tbl402, sqlChecking);
         complainViewMode = true;
         jButton1.setText("view All");
        }
        else{
         obtmode.fillTable(tbl402, sqlComplain);
         complainViewMode = false;
         jButton1.setText("view Checking");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
      jLabel2.setVisible(false);
      jLabel3.setVisible(false);
      jLabel4.setVisible(false);
      jLabel1.setVisible(false);
      
      //reload graph panal
        JPanel p = new JPanel();
        SetPanel resetPanele = new SetPanel();
        resetPanele.SetPanel(p, jPanel30);
      
      //get data
      
        SimpleDateFormat ft= new SimpleDateFormat("yyyy-MM-dd");
        String  startDate =  ft.format(jDateChooser421.getDate());   
        String endDate  = ft.format(jDateChooser422.getDate());
        String sql = "";
        String nameOfX = "Time";
        String nameOfY = "numOfComplains";
        boolean correctDate = false;
        
        
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        Date toDate = new Date();
      
       //validation dates
        TechnicalServiceDbAcess obtVali = new TechnicalServiceDbAcess();
      
                if (jDateChooser421.getDate().before(jDateChooser422.getDate())){
                    if(jDateChooser422.getDate().before(toDate)){
                    correctDate = true;
                    }
                    else
                        jLabel4.setVisible(true);
                    
                }
                else
                jLabel3.setVisible(true);
        
        //select the query
        if(rbtn405.isSelected()){
           if (rbtn408.isSelected()) 
              sql="SELECT YEAR(complainDate)  AS Time,count( complainId ) AS numOfComplains FROM complain WHERE complainDate > '"+startDate +"' AND complainDate < '"+endDate+"' GROUP BY year(complainDate)";
          else
              sql="SELECT month(complainDate)  AS Time,count( complainId ) AS numOfComplains FROM complain  WHERE complainDate > '"+startDate +"' AND complainDate < '"+endDate+"' GROUP BY month(complainDate)";
        }
        else {
          if (rbtn408.isSelected()) 
              sql="SELECT YEAR(complainDate)  AS Time,count( complainId ) AS numOfComplains FROM  complain WHERE itemId = '"+txtF405.getText().toUpperCase()+"'AND complainDate > '"+startDate +"' AND complainDate < '"+endDate+"'  GROUP BY year(complainDate)";
          else
              sql="SELECT month(complainDate)  AS Time,count( complainId ) AS numOfComplains FROM  complain WHERE itemId = '"+txtF405.getText().toUpperCase()+"' AND complainDate > '"+startDate +"' AND complainDate < '"+endDate+"'  GROUP BY month(complainDate)";
        }

        
         //create the graph
        if(rbtn406.isSelected()){
            
            if(!obtVali.checkAvalability("machinery", "machineId", txtF405.getText().toUpperCase()) && !obtVali.checkAvalability("plant", "plantId",  txtF405.getText().toUpperCase()) && !obtVali.checkAvalability("vehicle", "vehicleNo",  txtF405.getText())){
             jLabel1.setVisible(true);  
            }
        else{
               if(!obtVali.checkAvalability("complain", "itemId", txtF405.getText().toUpperCase()) && correctDate){
                     jLabel2.setVisible(true);
                 }
               else{
                   if(correctDate){
                       //create pie chart
                       if(rdbtn401.isSelected()){
                            Chart testPie = new Chart();
                            testPie.createPieDataset(sql, nameOfX, nameOfY);
                            JPanel pnl = new JPanel();
                            pnl = testPie.createPanel(testPie.createPieChart("Number Of Complain"), 480, 520);

                            SetPanel testPanele = new SetPanel();
                            testPanele.SetPanel(pnl, jPanel30);
                       }
                       else if(rdbtn402.isSelected()){
                           Chart testLine = new Chart();
                           JPanel pnl = new JPanel();
                           pnl = testLine.createPanel(testLine.createLineChart("Complains vs Time", "Time", "Number of Complains", sql, nameOfY, nameOfX, "complins"), 480,520);
                           SetPanel testPanele = new SetPanel();
                           testPanele.SetPanel(pnl, jPanel30);
                       }
                       else{
                        Chart testBar = new Chart();
                           JPanel pnl = new JPanel();
                           pnl = testBar.createPanel(testBar.createBarChart("Complains vs Time", "Time", "Number of Complains", sql, nameOfY, nameOfX, "complins"), 
                                   480,520);
                           SetPanel testPanele = new SetPanel();
                           testPanele.SetPanel(pnl, jPanel30);
                       }
                   }
               }
            }
        }
        else{
             if(correctDate){
                 if(rdbtn401.isSelected()){
                    Chart testPie = new Chart();
                    testPie.createPieDataset(sql, nameOfX, nameOfY);
                    JPanel pnl;
                     pnl = testPie.createPanel(testPie.createPieChart("Number Of Complain"), 480, 520);

                    SetPanel testPanele = new SetPanel();
                    testPanele.SetPanel(pnl, jPanel30);
                    }
                 else if(rdbtn402.isSelected()){
                           Chart testLine = new Chart();
                           JPanel pnl = new JPanel();
                           pnl = testLine.createPanel(testLine.createLineChart("Complains vs Time", "Time", "Number of Complains", sql, nameOfY, nameOfX, "complins"), 480,520);
                           SetPanel testPanele = new SetPanel();
                           testPanele.SetPanel(pnl, jPanel30);
                }
                 else{
                 
                           Chart testBar = new Chart();
                           JPanel pnl = new JPanel();
                           pnl = testBar.createPanel(testBar.createBarChart("Complains vs Time", "Time", "Number of Complains", sql, nameOfY, nameOfX, "complins"), 480,520);
                           SetPanel testPanele = new SetPanel();
                           testPanele.SetPanel(pnl, jPanel30);
                 
                 
                 }
             }
        }
                
    }//GEN-LAST:event_jButton10ActionPerformed

       
    private void rbtn405ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn405ActionPerformed
        txtF405.setEditable(false);
        txtF405.setText("");
    }//GEN-LAST:event_rbtn405ActionPerformed

    private void rbtn406ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtn406ActionPerformed
         txtF405.setEditable(true);
    }//GEN-LAST:event_rbtn406ActionPerformed

    private void btn495ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn495ActionPerformed
       	      HashMap param=new HashMap();
              param.put("comId",(String) tbl402.getModel().getValueAt(tbl402.getSelectedRow(),0));
              Technical_Services_main report=new Technical_Services_main("src\\technicalServiceIReport\\newComplain.jasper",param);
              report.setVisible(true);
    }//GEN-LAST:event_btn495ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         TechnicalServiceDbAcess obtmode =new  TechnicalServiceDbAcess();
         String sqlChecking= "select j.jobId as 'Job ID',j.jobDate as 'Job Date',j.complainId as 'Complain ID' ,c.status as 'Status',c.technician as 'Technician Id' ,c.employeeId as 'Employee Id' from job j, complain c  WHERE c.status = 'Repairing'";
        if(jobViewMode == false){
         obtmode.fillTable(tbl401, sqlChecking);
         jobViewMode = true;
         jButton3.setText("view ALL");
        }
        else{
         obtmode.fillTable(tbl401, sqlJob);
         jobViewMode = false;
         jButton3.setText("view Repairing");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    
      

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      txtF401.setText("MAC05");
      txtF402.setText("EMP1001");
      txtAr400.setText("when it works automatically it shut down and it cannot start");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmb401ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb401ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb401ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt406;
    private javax.swing.JButton btn400;
    private javax.swing.JButton btn405;
    private javax.swing.JButton btn495;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox<String> cmb400;
    private javax.swing.JComboBox<String> cmb401;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton6;
    private com.toedter.calendar.JDateChooser jDateChooser421;
    private com.toedter.calendar.JDateChooser jDateChooser422;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel jpnl429;
    private javax.swing.JPanel jpnl430;
    private javax.swing.JPanel jpnl431;
    private javax.swing.JLabel lbl400;
    private javax.swing.JLabel lbl401;
    private javax.swing.JLabel lbl402;
    private javax.swing.JLabel lbl431;
    private javax.swing.JLabel lbl432;
    private javax.swing.JRadioButton rbtn405;
    private javax.swing.JRadioButton rbtn406;
    private javax.swing.JRadioButton rbtn407;
    private javax.swing.JRadioButton rbtn408;
    private javax.swing.JRadioButton rdbtn401;
    private javax.swing.JRadioButton rdbtn402;
    private javax.swing.JRadioButton rdbtn403;
    private javax.swing.JTable tbl400;
    private javax.swing.JTable tbl401;
    private javax.swing.JTable tbl402;
    private javax.swing.JTextArea txtAr400;
    private javax.swing.JTextArea txtAr435;
    private javax.swing.JTextArea txtAr437;
    private javax.swing.JTextField txtF400;
    private javax.swing.JTextField txtF401;
    private javax.swing.JTextField txtF402;
    private javax.swing.JTextField txtF405;
    private javax.swing.JTextField txtF426;
    private javax.swing.JTextField txtF427;
    // End of variables declaration//GEN-END:variables
}
