/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PurchaseManagement;

import RootElement.DbConnect;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Samitha Heanthenna
 */
public class DirectSales extends javax.swing.JPanel {

    /**
     * Creates new form DirectSales
     */
    public DirectSales() {
        ComboKeyHandler cm;
        
        initComponents();
        
        btn305.requestFocusInWindow();
        
        DbConnect c=new DbConnect();
        c.setConnection();
        
            try
            {                                                                             
                ResultSet qresults;
                Statement statem1=c.con.createStatement();
                qresults=statem1.executeQuery("select * from directsale");
                               
                String ids="";
            
                while(qresults.next())
                {
                    ids=qresults.getString("salesId");
                }
                
                IdIncrementPurchase inc=new IdIncrementPurchase(ids,'d');
                String newids=inc.getIncrementedId();
                
                txtF302.setText(newids);
                

                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error Connecting to Database", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try 
                {
                c.con.close();
                } 
                catch (SQLException ex) 
                {
                Logger.getLogger(PurchaseOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
            DbAccessPurchase dba = new DbAccessPurchase("purchase","purchaseType","Trading");
            dba.fillNextComboview(cmb397);
            cm=new ComboKeyHandler(cmb397);
            
            cmb397.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                cm.keyTyped(e);
            }
        });
            
            DbAccessPurchase dba2 = new DbAccessPurchase("directItemNames");
            dba2.fillTable(tbl331, lblResultCount);
            
             DbAccessPurchase dba3 = new DbAccessPurchase("directsale");
             dba3.viewDirectSales(tbl318, lblResultCount2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jtb300 = new javax.swing.JTabbedPane();
        jpnl301 = new javax.swing.JPanel();
        lblSalesID = new javax.swing.JLabel();
        txtF302 = new javax.swing.JTextField();
        lblItemId = new javax.swing.JLabel();
        lblBuyerName = new javax.swing.JLabel();
        txtF304 = new javax.swing.JTextField();
        btn305 = new javax.swing.JButton();
        btn306 = new javax.swing.JButton();
        jpnl307 = new javax.swing.JPanel();
        tbl308 = new javax.swing.JScrollPane();
        tbl331 = new javax.swing.JTable();
        lblResultCount = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtF309 = new javax.swing.JTextField();
        lblTp = new javax.swing.JLabel();
        txtF310 = new javax.swing.JTextField();
        lblSalesPrice = new javax.swing.JLabel();
        txtF311 = new javax.swing.JTextField();
        lbl327 = new javax.swing.JLabel();
        lbl328 = new javax.swing.JLabel();
        lbl329 = new javax.swing.JLabel();
        lbl330 = new javax.swing.JLabel();
        lbl331 = new javax.swing.JLabel();
        cmb397 = new javax.swing.JComboBox<>();
        cmb398 = new javax.swing.JComboBox<>();
        ItemID = new javax.swing.JLabel();
        lbl332 = new javax.swing.JLabel();
        btn399 = new javax.swing.JButton();
        jpnl312 = new javax.swing.JPanel();
        lblSearchSalesID = new javax.swing.JLabel();
        txtF313 = new javax.swing.JTextField();
        btn315 = new javax.swing.JButton();
        jpnl316 = new javax.swing.JPanel();
        tbl317 = new javax.swing.JScrollPane();
        tbl318 = new javax.swing.JTable();
        lblResultCount2 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 590));

        jtb300.setBackground(new java.awt.Color(255, 255, 255));

        jpnl301.setBackground(new java.awt.Color(255, 255, 255));

        lblSalesID.setText("Sales ID");

        txtF302.setEditable(false);

        lblItemId.setText("Purchase ID");

        lblBuyerName.setText("Buyer name");

        txtF304.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF304FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF304FocusLost(evt);
            }
        });
        txtF304.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF304KeyTyped(evt);
            }
        });

        btn305.setText("Add sales");
        btn305.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn305ActionPerformed(evt);
            }
        });

        btn306.setText("Cancel sales");
        btn306.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn306ActionPerformed(evt);
            }
        });

        jpnl307.setBackground(new java.awt.Color(255, 255, 255));
        jpnl307.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Items"));

        tbl331.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Item_Name", "Item_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl308.setViewportView(tbl331);

        lblResultCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl307Layout = new javax.swing.GroupLayout(jpnl307);
        jpnl307.setLayout(jpnl307Layout);
        jpnl307Layout.setHorizontalGroup(
            jpnl307Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl307Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl307Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl307Layout.createSequentialGroup()
                        .addComponent(lblResultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(tbl308, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl307Layout.setVerticalGroup(
            jpnl307Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl307Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl308, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblEmail.setText("Email address");

        txtF309.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF309FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF309FocusLost(evt);
            }
        });

        lblTp.setText("Telephone");

        txtF310.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF310FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF310FocusLost(evt);
            }
        });
        txtF310.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF310KeyTyped(evt);
            }
        });

        lblSalesPrice.setText("Sales price");

        txtF311.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF311FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF311FocusLost(evt);
            }
        });
        txtF311.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF311KeyTyped(evt);
            }
        });

        lbl327.setBackground(new java.awt.Color(255, 255, 255));
        lbl327.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl327.setForeground(new java.awt.Color(255, 0, 0));

        lbl328.setBackground(new java.awt.Color(255, 255, 255));
        lbl328.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl328.setForeground(new java.awt.Color(255, 0, 0));

        lbl329.setBackground(new java.awt.Color(255, 255, 255));
        lbl329.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl329.setForeground(new java.awt.Color(255, 0, 0));

        lbl330.setBackground(new java.awt.Color(255, 255, 255));
        lbl330.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl330.setForeground(new java.awt.Color(255, 0, 0));

        lbl331.setBackground(new java.awt.Color(255, 255, 255));
        lbl331.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl331.setForeground(new java.awt.Color(255, 0, 0));

        cmb397.setEditable(true);
        cmb397.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb397FocusLost(evt);
            }
        });

        cmb398.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Credit" }));
        cmb398.setSelectedIndex(-1);
        cmb398.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb398FocusLost(evt);
            }
        });

        ItemID.setText("Payment method");

        lbl332.setBackground(new java.awt.Color(255, 255, 255));
        lbl332.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl332.setForeground(new java.awt.Color(255, 0, 0));

        btn399.setText("Demo");
        btn399.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn399ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl301Layout = new javax.swing.GroupLayout(jpnl301);
        jpnl301.setLayout(jpnl301Layout);
        jpnl301Layout.setHorizontalGroup(
            jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl301Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSalesID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuyerName, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTp, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSalesPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemID)))
                    .addComponent(lblItemId, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF302, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addComponent(txtF309, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl329, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addComponent(txtF310, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl330, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addComponent(txtF311, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl331, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmb397, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtF304, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnl301Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl328, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpnl301Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lbl327, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addComponent(cmb398, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl332, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addComponent(btn399, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn305, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(btn306))
                    .addComponent(jpnl307, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jpnl301Layout.setVerticalGroup(
            jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl301Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnl307, javax.swing.GroupLayout.PREFERRED_SIZE, 409, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl301Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jpnl301Layout.createSequentialGroup()
                                .addComponent(lblSalesID)
                                .addGap(23, 23, 23)
                                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblItemId)
                                    .addComponent(cmb397, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBuyerName)
                                    .addComponent(txtF304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpnl301Layout.createSequentialGroup()
                                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jpnl301Layout.createSequentialGroup()
                                        .addComponent(txtF302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(57, 57, 57))
                                    .addGroup(jpnl301Layout.createSequentialGroup()
                                        .addComponent(lbl327, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(20, 20, 20)))
                                .addComponent(lbl328, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(23, 23, 23)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblEmail)
                                .addComponent(txtF309, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl329, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblTp)
                                .addComponent(txtF310, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl330, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblSalesPrice)
                                .addComponent(txtF311, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl331, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cmb398, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ItemID))
                            .addComponent(lbl332, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl301Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn305)
                        .addComponent(btn399))
                    .addComponent(btn306))
                .addGap(28, 28, 28))
        );

        jtb300.addTab("Add Direct Sale", jpnl301);

        jpnl312.setBackground(new java.awt.Color(255, 255, 255));

        lblSearchSalesID.setText("Search by sales ID");

        txtF313.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF313KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF313KeyTyped(evt);
            }
        });

        btn315.setText("View all");
        btn315.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn315ActionPerformed(evt);
            }
        });

        jpnl316.setBackground(new java.awt.Color(255, 255, 255));
        jpnl316.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl318.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Sales_ID", "Customer_Name", "Payment_Method", "Email", "Telephone", "Sales_Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl317.setViewportView(tbl318);

        lblResultCount2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount2.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount2.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl316Layout = new javax.swing.GroupLayout(jpnl316);
        jpnl316.setLayout(jpnl316Layout);
        jpnl316Layout.setHorizontalGroup(
            jpnl316Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl316Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl316Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl317, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(jpnl316Layout.createSequentialGroup()
                        .addComponent(lblResultCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl316Layout.setVerticalGroup(
            jpnl316Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl316Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl317, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblResultCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jpnl312Layout = new javax.swing.GroupLayout(jpnl312);
        jpnl312.setLayout(jpnl312Layout);
        jpnl312Layout.setHorizontalGroup(
            jpnl312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl312Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpnl312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnl316, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnl312Layout.createSequentialGroup()
                        .addComponent(lblSearchSalesID, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtF313, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn315, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jpnl312Layout.setVerticalGroup(
            jpnl312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnl312Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jpnl312Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF313, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchSalesID)
                    .addComponent(btn315))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jpnl316, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jtb300.addTab("View Direct Sales", jpnl312);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb300)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtb300)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtF304FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF304FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF304.getText().toString());
        tv.empty(lbl328);
    }//GEN-LAST:event_txtF304FocusLost

    private void txtF304FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF304FocusGained
        lbl328.setText("");
    }//GEN-LAST:event_txtF304FocusGained

    private void txtF309FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF309FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF309.getText().toString());
        tv.empty(lbl329);
        
        TextValidatorPurchase tv2 = new TextValidatorPurchase(txtF309.getText().toString());
        if(tv2.isEmail()){
            lbl329.setText("");
        }
        else{
            lbl329.setText("!");
        }
    }//GEN-LAST:event_txtF309FocusLost

    private void txtF309FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF309FocusGained
        lbl329.setText("");
    }//GEN-LAST:event_txtF309FocusGained

    private void txtF310FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF310FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF310.getText().toString());
        tv.empty(lbl330);
        
        if(txtF310.getText().length()<10){
                         lbl330.setText("!");
        }
    }//GEN-LAST:event_txtF310FocusLost

    private void txtF310FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF310FocusGained
        lbl330.setText("");
    }//GEN-LAST:event_txtF310FocusGained

    private void txtF311FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF311FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF311.getText().toString());
        tv.empty(lbl331);
    }//GEN-LAST:event_txtF311FocusLost

    private void txtF311FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF311FocusGained
        lbl331.setText("");
    }//GEN-LAST:event_txtF311FocusGained

    private void txtF311KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF311KeyTyped
        if(txtF311.getText().length()<20){
                   if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF311KeyTyped

    private void txtF310KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF310KeyTyped
        if(txtF310.getText().length()<10){
                   if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF310KeyTyped

    private void cmb397FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb397FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb397, lbl327);
    }//GEN-LAST:event_cmb397FocusLost

    private void btn305ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn305ActionPerformed
        if(lbl327.getText().equals("!")||lbl328.getText().equals("!")||lbl329.getText().equals("!")||lbl330.getText().equals("!")||lbl331.getText().equals("!")||lbl332.getText().equals("!")){
        
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(cmb397.getSelectedIndex()==-1||cmb398.getSelectedIndex()==-1||txtF304.getText().isEmpty()||txtF309.getText().isEmpty()||txtF310.getText().isEmpty()||txtF311.getText().isEmpty()){
        
            TextValidatorPurchase tv2 = new TextValidatorPurchase();
            
            if(cmb397.getSelectedIndex()==-1){
                tv2.comboSelection(cmb397, lbl327);
            }
            if(cmb398.getSelectedIndex()==-1){
                tv2.comboSelection(cmb398, lbl332);
            }
            if(txtF304.getText().isEmpty()){
                lbl328.setText("!");
            }
            if(txtF309.getText().isEmpty()){
                lbl329.setText("!");
            }
            if(txtF310.getText().isEmpty()){
                 lbl330.setText("!");
            }
            if(txtF311.getText().isEmpty()){
                lbl331.setText("!");
            }
           
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //insertion code
            DbAccessPurchase dba = new DbAccessPurchase();
            dba.addDirectSales(txtF302.getText().toString(),txtF304.getText().toString(),Double.parseDouble(txtF311.getText()),cmb398.getSelectedItem().toString(),txtF309.getText(),txtF310.getText(),cmb397.getSelectedItem().toString(),"EMP1002");
            
            DbAccessPurchase dba2=new DbAccessPurchase("purchase", "status", "Direct Sales", "purchaseid", cmb397.getSelectedItem().toString());
            dba2.updateOneFeild();
            
            JOptionPane.showMessageDialog(this, "DirectSales recorded successfuly");
            //Creating a new instance of purchaseorder to refresh
            DirectSales ds = new DirectSales();
            SetPanel sp = new SetPanel();
            sp.SetPanel(ds);
        }
    }//GEN-LAST:event_btn305ActionPerformed

    private void btn306ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn306ActionPerformed
            DirectSales ds = new DirectSales();
            SetPanel sp = new SetPanel();
            sp.SetPanel(ds);
    }//GEN-LAST:event_btn306ActionPerformed

    private void btn315ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn315ActionPerformed
        DbAccessPurchase dba = new DbAccessPurchase("directsale");
        dba.viewDirectSales(tbl318, lblResultCount2);
        
        txtF313.setText("");
    }//GEN-LAST:event_btn315ActionPerformed

    private void txtF313KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF313KeyTyped
         if(txtF313.getText().length()>=7)
            evt.consume();
    }//GEN-LAST:event_txtF313KeyTyped

    private void cmb398FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb398FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb398, lbl332);
    }//GEN-LAST:event_cmb398FocusLost

    private void txtF313KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF313KeyReleased
        DbAccessPurchase dba = new DbAccessPurchase("directsale", "salesId", txtF313.getText().toString());
        dba.viewDirectSalesSelected(tbl318, lblResultCount2);
    }//GEN-LAST:event_txtF313KeyReleased

    private void txtF304KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF304KeyTyped
        if(txtF304.getText().length()<50){
                   if((Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF304KeyTyped

    private void btn399ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn399ActionPerformed
        cmb397.setSelectedIndex(0);
        cmb398.setSelectedIndex(0);
        txtF304.setText("Mr.Kumara Perera");
        txtF310.setText("0756990877");
        txtF309.setText("kumara123@gmail.com");
        txtF311.setText("7500");

    }//GEN-LAST:event_btn399ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ItemID;
    private javax.swing.JButton btn305;
    private javax.swing.JButton btn306;
    private javax.swing.JButton btn315;
    private javax.swing.JButton btn399;
    private javax.swing.JComboBox<String> cmb397;
    private javax.swing.JComboBox<String> cmb398;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jpnl301;
    private javax.swing.JPanel jpnl307;
    private javax.swing.JPanel jpnl312;
    private javax.swing.JPanel jpnl316;
    private javax.swing.JTabbedPane jtb300;
    private javax.swing.JLabel lbl327;
    private javax.swing.JLabel lbl328;
    private javax.swing.JLabel lbl329;
    private javax.swing.JLabel lbl330;
    private javax.swing.JLabel lbl331;
    private javax.swing.JLabel lbl332;
    private javax.swing.JLabel lblBuyerName;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblItemId;
    private javax.swing.JLabel lblResultCount;
    private javax.swing.JLabel lblResultCount2;
    private javax.swing.JLabel lblSalesID;
    private javax.swing.JLabel lblSalesPrice;
    private javax.swing.JLabel lblSearchSalesID;
    private javax.swing.JLabel lblTp;
    private javax.swing.JScrollPane tbl308;
    private javax.swing.JScrollPane tbl317;
    private javax.swing.JTable tbl318;
    private javax.swing.JTable tbl331;
    private javax.swing.JTextField txtF302;
    private javax.swing.JTextField txtF304;
    private javax.swing.JTextField txtF309;
    private javax.swing.JTextField txtF310;
    private javax.swing.JTextField txtF311;
    private javax.swing.JTextField txtF313;
    // End of variables declaration//GEN-END:variables
}
