/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PurchaseManagement;

import RootElement.DbConnect;
import RootElement.SessionHandler;
import java.awt.Container;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.swing.JRViewer;
import java.lang.String;
import javax.swing.JOptionPane;

/**
 *
 * @author ashanginige
 */
public class PurchaseManagementMain extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public PurchaseManagementMain() {
        initComponents();
        if(SessionHandler.getInsta()==null){
            jButton2.setVisible(false);
        }
        lbl_logged_user.setText(SessionHandler.getOccupation());
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnl300 = new javax.swing.JPanel();
        lbl301 = new javax.swing.JLabel();
        lbl_logged_user = new javax.swing.JLabel();
        btn300 = new javax.swing.JButton();
        btn301 = new javax.swing.JButton();
        btn302 = new javax.swing.JButton();
        btn303 = new javax.swing.JButton();
        btn304 = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnl300.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jpnl300, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 780, 590));

        lbl301.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl301.setForeground(new java.awt.Color(162, 167, 174));
        getContentPane().add(lbl301, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, -1, -1));

        lbl_logged_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_logged_user.setForeground(new java.awt.Color(162, 167, 174));
        lbl_logged_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_logged_user.setText("Purchase Manager");
        getContentPane().add(lbl_logged_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, -1, -1));

        btn300.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/rawMaterialPurchases_default.png"))); // NOI18N
        btn300.setBorderPainted(false);
        btn300.setContentAreaFilled(false);
        btn300.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/rawMaterialPurchases_rollOver.png"))); // NOI18N
        btn300.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn300ActionPerformed(evt);
            }
        });
        getContentPane().add(btn300, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        btn301.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/directSales_default.png"))); // NOI18N
        btn301.setBorderPainted(false);
        btn301.setContentAreaFilled(false);
        btn301.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/directSales_rollOver.png"))); // NOI18N
        btn301.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn301ActionPerformed(evt);
            }
        });
        getContentPane().add(btn301, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        btn302.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/returnItems_default.png"))); // NOI18N
        btn302.setBorderPainted(false);
        btn302.setContentAreaFilled(false);
        btn302.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/returnItems_rollOver.png"))); // NOI18N
        btn302.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn302ActionPerformed(evt);
            }
        });
        getContentPane().add(btn302, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        btn303.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/supplierItems_default.png"))); // NOI18N
        btn303.setBorderPainted(false);
        btn303.setContentAreaFilled(false);
        btn303.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/supplierItems_rollOver.png"))); // NOI18N
        btn303.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn303ActionPerformed(evt);
            }
        });
        getContentPane().add(btn303, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));

        btn304.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/supplierManagement_default.png"))); // NOI18N
        btn304.setBorderPainted(false);
        btn304.setContentAreaFilled(false);
        btn304.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/PurchaseManagment/supplierManagement_rollOver.png"))); // NOI18N
        btn304.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn304ActionPerformed(evt);
            }
        });
        getContentPane().add(btn304, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_default.png"))); // NOI18N
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_hover.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_default.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_hover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 640, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainLayoutPurchasing.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn300ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn300ActionPerformed
        try{
        PurchaseOrders po = new PurchaseOrders();
        SetPanel p = new SetPanel();
        p.SetPanel(po, jpnl300);
        
        lbl301.setText("Raw Material Purchases");}
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btn300ActionPerformed

    private void btn301ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn301ActionPerformed
        try{
        DirectSales ds = new DirectSales();
        SetPanel p = new SetPanel();
        p.SetPanel(ds, jpnl300);
        
        lbl301.setText("Direct Sales");}
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btn301ActionPerformed

    private void btn302ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn302ActionPerformed
        try
        {ReturnItems ri = new ReturnItems();
        SetPanel p = new SetPanel();
        p.SetPanel(ri, jpnl300);
        
        lbl301.setText("Return Items");}
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btn302ActionPerformed

    private void btn303ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn303ActionPerformed
        try
        {SupplierItems si = new SupplierItems();
        SetPanel p = new SetPanel();
        p.SetPanel(si, jpnl300);
        
        lbl301.setText("Supplier Items");}
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btn303ActionPerformed

    private void btn304ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn304ActionPerformed
        try
        {SupplierManagment sm = new SupplierManagment();
        SetPanel p = new SetPanel();
        p.SetPanel(sm, jpnl300);
        
        lbl301.setText("Supplier Managment");}
        catch(Exception e)
        {
        }
    }//GEN-LAST:event_btn304ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        SessionHandler.getInsta().getRootPane().getGlassPane().setVisible(false);
        SessionHandler.getInsta().setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int option=JOptionPane.showConfirmDialog(this,"Do you want to logout ?");
      if(option==JOptionPane.YES_OPTION){
          this.dispose();
          SessionHandler.Dispose();
      }
      else{
            
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    
 PurchaseManagementMain(String filename, Map param) {
      
    // super("view report");
       try {
//           Class.forName("com.mysql.jdbc.Driver").newInstance();
//            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/kelanidb","kelaniAdmin","kelani123");
//        
            DbConnect dbc=new DbConnect();
            dbc.setConnection();
            
            JasperPrint print=JasperFillManager.fillReport(filename,param,dbc.con);
            JRViewer viewer=new JRViewer(print);
            
            Container c=getContentPane();
            c.add(viewer);
            
           
       } catch (Exception e) {
           System.out.println(e);
           e.printStackTrace();
       }
       
       
       setBounds(10,10,1000,500);
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PurchaseManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PurchaseManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PurchaseManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PurchaseManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PurchaseManagementMain().setVisible(true);
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(PurchaseManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(PurchaseManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(PurchaseManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(PurchaseManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn300;
    private javax.swing.JButton btn301;
    private javax.swing.JButton btn302;
    private javax.swing.JButton btn303;
    private javax.swing.JButton btn304;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpnl300;
    private javax.swing.JLabel lbl301;
    private javax.swing.JLabel lbl_logged_user;
    // End of variables declaration//GEN-END:variables
}
