/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PurchaseManagement;

import RootElement.DbConnect;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Samitha Heanthenna
 */
public class SupplierItems extends javax.swing.JPanel {

    /**
     * Creates new form SupplierItems
     */
    public SupplierItems() {
        ComboKeyHandler cm;
        ComboKeyHandler cm1;
        
        initComponents();
        
        btn327.requestFocusInWindow();
        
        DbConnect c=new DbConnect();
        c.setConnection();
        
            try
            {                                                                             
                ResultSet qresults;
                Statement statem1=c.con.createStatement();
                qresults=statem1.executeQuery("select * from itemlist");
                               
                String ids="";
            
                while(qresults.next())
                {
                    ids=qresults.getString("itemId");
                }
                
                IdIncrementPurchase inc=new IdIncrementPurchase(ids,'i');
                String newids=inc.getIncrementedId();
                
                txtF328.setText(newids);
                

                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error Connecting to Database", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try 
                {
                c.con.close();
                } 
                catch (SQLException ex) 
                {
                Logger.getLogger(PurchaseOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            DbAccessPurchase dab = new DbAccessPurchase("supplier");
            dab.viewSuplierDetailsOnTBL(tbl331, lblResultCount300);
            
            DbAccessPurchase dba1 = new DbAccessPurchase("itemlist");
            dba1.viewSuplierItemsOnTBL(tbl333, lblResultCount301);
            
            DbAccessPurchase dba = new DbAccessPurchase("supplier","supplierId");
            dba.fillCombo(cmb399);
            cm=new ComboKeyHandler(cmb399);
            
            cmb399.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                cm.keyTyped(e);
            }
        });
            
            DbAccessPurchase dba2 = new DbAccessPurchase("itemlist","itemId");
            dba2.fillCombo(cmb365);
            cm1=new ComboKeyHandler(cmb365);
            
            cmb365.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                cm1.keyTyped(e);
            }
        });
            
            DbAccessPurchase dba3 = new DbAccessPurchase("itemlist");
            dba3.viewSuplierItemsOnTBL(tbl318, lblResultCount2);
            
        String sql = "select price as val1, itemid as val2, count(itemName) as val3 from itemlist group by itemName";
        String valOfCol1 = "val1";
        String valOfCol2 = "val2";
        String valOfCol3 = "val3";
        
            Chart bar = new Chart();
            JPanel pnl = new JPanel();
            pnl= bar.createPanel(bar.createBarChart("Purchase item prices", "Item ID", "Price", sql, valOfCol1, valOfCol2, valOfCol3), 680, 445);
            SetPanel testpnl = new SetPanel();
            testpnl.SetPanel(pnl, jpnl336);
            

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl317 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblPurchaseID = new javax.swing.JLabel();
        txtF328 = new javax.swing.JTextField();
        lblItemName = new javax.swing.JLabel();
        txtF329 = new javax.swing.JTextField();
        lblItemID = new javax.swing.JLabel();
        txtF330 = new javax.swing.JTextField();
        lblItemID1 = new javax.swing.JLabel();
        btn327 = new javax.swing.JButton();
        btn326 = new javax.swing.JButton();
        jpnl302 = new javax.swing.JPanel();
        tbl307 = new javax.swing.JScrollPane();
        tbl331 = new javax.swing.JTable();
        lblResultCount300 = new javax.swing.JLabel();
        cmb399 = new javax.swing.JComboBox<>();
        lbl329 = new javax.swing.JLabel();
        lbl315 = new javax.swing.JLabel();
        lbl316 = new javax.swing.JLabel();
        btn399 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtF323 = new javax.swing.JTextField();
        lblSearchSalesID = new javax.swing.JLabel();
        btn325 = new javax.swing.JButton();
        jpnl317 = new javax.swing.JPanel();
        tbl309 = new javax.swing.JScrollPane();
        tbl318 = new javax.swing.JTable();
        lblResultCount2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblItemName2 = new javax.swing.JLabel();
        txtF333 = new javax.swing.JTextField();
        lblItemID3 = new javax.swing.JLabel();
        jpnl304 = new javax.swing.JPanel();
        tbl310 = new javax.swing.JScrollPane();
        tbl333 = new javax.swing.JTable();
        lblResultCount301 = new javax.swing.JLabel();
        btn331 = new javax.swing.JButton();
        btn332 = new javax.swing.JButton();
        cmb365 = new javax.swing.JComboBox<>();
        lbl318 = new javax.swing.JLabel();
        lbl319 = new javax.swing.JLabel();
        btn333 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jpnl336 = new javax.swing.JPanel();

        lbl317.setBackground(new java.awt.Color(255, 255, 255));
        lbl317.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl317.setForeground(new java.awt.Color(255, 0, 0));

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPurchaseID.setText("Item  ID");

        txtF328.setEditable(false);

        lblItemName.setText("Item name");

        txtF329.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF329FocusLost(evt);
            }
        });
        txtF329.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF329KeyTyped(evt);
            }
        });

        lblItemID.setText("Price");

        txtF330.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF330FocusLost(evt);
            }
        });
        txtF330.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF330KeyTyped(evt);
            }
        });

        lblItemID1.setText("Supplier ID");

        btn327.setText("Add");
        btn327.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn327ActionPerformed(evt);
            }
        });

        btn326.setText("Cancel ");
        btn326.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn326ActionPerformed(evt);
            }
        });

        jpnl302.setBackground(new java.awt.Color(255, 255, 255));
        jpnl302.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier Details"));

        tbl331.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Supplier_ID", "Company_Name", "Specialization"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl307.setViewportView(tbl331);

        lblResultCount300.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount300.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount300.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl302Layout = new javax.swing.GroupLayout(jpnl302);
        jpnl302.setLayout(jpnl302Layout);
        jpnl302Layout.setHorizontalGroup(
            jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl302Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl307, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(jpnl302Layout.createSequentialGroup()
                        .addComponent(lblResultCount300, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl302Layout.setVerticalGroup(
            jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl302Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl307, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultCount300, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        cmb399.setEditable(true);
        cmb399.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb399FocusLost(evt);
            }
        });

        lbl329.setBackground(new java.awt.Color(255, 255, 255));
        lbl329.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl329.setForeground(new java.awt.Color(255, 0, 0));

        lbl315.setBackground(new java.awt.Color(255, 255, 255));
        lbl315.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl315.setForeground(new java.awt.Color(255, 0, 0));

        lbl316.setBackground(new java.awt.Color(255, 255, 255));
        lbl316.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl316.setForeground(new java.awt.Color(255, 0, 0));

        btn399.setText("Demo");
        btn399.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn399ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(414, 414, 414)
                .addComponent(btn399, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btn327, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn326, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPurchaseID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemName)
                            .addComponent(lblItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtF328, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblItemID1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cmb399, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbl329, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtF330, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl316, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtF329, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(lbl315, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 23, Short.MAX_VALUE)
                        .addComponent(jpnl302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPurchaseID)
                        .addGap(26, 26, 26)
                        .addComponent(lblItemName)
                        .addGap(26, 26, 26)
                        .addComponent(lblItemID))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtF328, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb399, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblItemID1))
                            .addComponent(lbl329, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtF329, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtF330, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl315, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl316, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(36, 36, 36)
                .addComponent(jpnl302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn326)
                    .addComponent(btn327)
                    .addComponent(btn399)))
        );

        jTabbedPane1.addTab("Add Supplier Item Details", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        txtF323.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF323KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF323KeyTyped(evt);
            }
        });

        lblSearchSalesID.setText("Search by supplier item name");

        btn325.setText("View all");
        btn325.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn325ActionPerformed(evt);
            }
        });

        jpnl317.setBackground(new java.awt.Color(255, 255, 255));
        jpnl317.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        tbl318.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item_ID", "Item_Name", "Price", "Supplier_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl309.setViewportView(tbl318);

        lblResultCount2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount2.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount2.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl317Layout = new javax.swing.GroupLayout(jpnl317);
        jpnl317.setLayout(jpnl317Layout);
        jpnl317Layout.setHorizontalGroup(
            jpnl317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl317Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl309, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
                    .addGroup(jpnl317Layout.createSequentialGroup()
                        .addComponent(lblResultCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl317Layout.setVerticalGroup(
            jpnl317Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl317Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl309, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblResultCount2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnl317, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblSearchSalesID, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtF323, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn325, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF323, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSearchSalesID)
                    .addComponent(btn325))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jpnl317, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("View Supplier Item Details", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblItemName2.setText("Item ID");

        txtF333.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF333FocusLost(evt);
            }
        });
        txtF333.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF333KeyTyped(evt);
            }
        });

        lblItemID3.setText("New Price");

        jpnl304.setBackground(new java.awt.Color(255, 255, 255));
        jpnl304.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier Item Details"));

        tbl333.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier_ID", "Item_ID", "Item_Name", "Supplier_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl310.setViewportView(tbl333);

        lblResultCount301.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount301.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount301.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl304Layout = new javax.swing.GroupLayout(jpnl304);
        jpnl304.setLayout(jpnl304Layout);
        jpnl304Layout.setHorizontalGroup(
            jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl304Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl310, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(jpnl304Layout.createSequentialGroup()
                        .addComponent(lblResultCount301, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl304Layout.setVerticalGroup(
            jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl304Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl310, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultCount301, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn331.setText("Update");
        btn331.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn331ActionPerformed(evt);
            }
        });

        btn332.setText("Cancel ");
        btn332.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn332ActionPerformed(evt);
            }
        });

        cmb365.setEditable(true);
        cmb365.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb365FocusLost(evt);
            }
        });

        lbl318.setBackground(new java.awt.Color(255, 255, 255));
        lbl318.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl318.setForeground(new java.awt.Color(255, 0, 0));

        lbl319.setBackground(new java.awt.Color(255, 255, 255));
        lbl319.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl319.setForeground(new java.awt.Color(255, 0, 0));

        btn333.setText("Remove");
        btn333.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn333ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblItemName2)
                            .addComponent(lblItemID3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF333, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmb365, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl318, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl319, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jpnl304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn333, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn331, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(639, 639, 639)
                    .addComponent(btn332, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(36, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItemName2)
                        .addComponent(cmb365, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl318, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItemID3)
                        .addComponent(txtF333, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl319, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(58, 58, 58)
                .addComponent(jpnl304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn333)
                    .addComponent(btn331))
                .addGap(31, 31, 31))
            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel3Layout.createSequentialGroup()
                    .addGap(510, 510, 510)
                    .addComponent(btn332)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Update Supplier Items", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Statistical Graph"));

        jpnl336.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnl336Layout = new javax.swing.GroupLayout(jpnl336);
        jpnl336.setLayout(jpnl336Layout);
        jpnl336Layout.setHorizontalGroup(
            jpnl336Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 681, Short.MAX_VALUE)
        );
        jpnl336Layout.setVerticalGroup(
            jpnl336Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jpnl336, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl336, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View Prices", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtF329KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF329KeyTyped
        if(txtF329.getText().length()>=7)
            evt.consume();
    }//GEN-LAST:event_txtF329KeyTyped

    private void txtF330KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF330KeyTyped
        if(txtF330.getText().length()<=20){
                   if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF330KeyTyped

    private void txtF330FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF330FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF330.getText().toString());
        tv.empty(lbl316);
    }//GEN-LAST:event_txtF330FocusLost

    private void txtF329FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF329FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF329.getText().toString());
        tv.empty(lbl315);
    }//GEN-LAST:event_txtF329FocusLost

    private void btn326ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn326ActionPerformed
        SupplierItems si = new SupplierItems();
        SetPanel sp = new SetPanel();
        sp.SetPanel(si);
    }//GEN-LAST:event_btn326ActionPerformed

    private void btn327ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn327ActionPerformed
        //addcode
        
        if(cmb399.getSelectedIndex()==-1||txtF329.getText().isEmpty()||txtF330.getText().isEmpty()){
        if(cmb399.getSelectedIndex()==-1){
            lbl329.setText("!");
        }
        if(txtF329.getText().isEmpty()){
            lbl315.setText("!");
        }
        if(txtF330.getText().isEmpty()){
            lbl316.setText("!");
        }
   
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        else if(lbl315.getText().equals("!")||lbl316.getText().equals("!")||lbl329.getText().equals("!")){
        
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //insertion code
            
            DbAccessPurchase dba = new DbAccessPurchase();
            dba.addSupplierItems(txtF328.getText().toString(),cmb399.getSelectedItem().toString(),txtF329.getText().toString(),txtF330.getText().toString());
            JOptionPane.showMessageDialog(this, "Item details recorded successfuly");
        //refresh
        SupplierItems si = new SupplierItems();
        SetPanel sp = new SetPanel();
        sp.SetPanel(si);
    }//GEN-LAST:event_btn327ActionPerformed
    }
    private void btn325ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn325ActionPerformed
        DbAccessPurchase dba = new DbAccessPurchase("itemlist");
        dba.viewSuplierItemsOnTBL(tbl318, lblResultCount2);
        
        txtF323.setText("");
    }//GEN-LAST:event_btn325ActionPerformed

    private void txtF323KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF323KeyTyped
        if(txtF323.getText().length()>=7)
            evt.consume();
    }//GEN-LAST:event_txtF323KeyTyped

    private void txtF333FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF333FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF333.getText().toString());
        tv.empty(lbl319);
    }//GEN-LAST:event_txtF333FocusLost

    private void txtF333KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF333KeyTyped
        if(txtF333.getText().length()<=20){
                   if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF333KeyTyped

    private void btn331ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn331ActionPerformed
        if(cmb365.getSelectedIndex()==-1||txtF333.getText().toString().isEmpty()){
            lbl318.setText("!");
            lbl319.setText("!");
        }
        
        
        if(lbl318.getText().equals("!")||lbl319.getText().equals("!")){
        
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        try{
            DbAccessPurchase dba = new DbAccessPurchase("itemlist", "price", txtF333.getText().toString(), "itemId", cmb365.getSelectedItem().toString());
            dba.updateOneFeild();
            
            JOptionPane.showMessageDialog(this, "price updated successfuly");
        
        txtF333.setText("");
        cmb365.setSelectedIndex(-1);
        
        DbAccessPurchase dba1 = new DbAccessPurchase("itemlist");
        dba1.viewSuplierItemsOnTBL(tbl333, lblResultCount301);
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btn331ActionPerformed

    private void btn332ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn332ActionPerformed
        txtF333.setText("");
        cmb365.setSelectedIndex(-1);
    }//GEN-LAST:event_btn332ActionPerformed

    private void btn333ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn333ActionPerformed
        
         if(cmb365.getSelectedIndex()==-1){
            lbl318.setText("!");
        }
        
        
        if(lbl318.getText().equals("!")){
        
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        
        try{
            DbAccessPurchase dba = new DbAccessPurchase("itemlist","itemId", cmb365.getSelectedItem().toString());
            dba.remove();
            
            JOptionPane.showMessageDialog(this, "Item removed successfuly");
        
        txtF333.setText("");
        cmb365.setSelectedIndex(-1);
        
        DbAccessPurchase dba1 = new DbAccessPurchase("itemlist");
        dba1.viewSuplierItemsOnTBL(tbl333, lblResultCount301);
        
        SupplierItems si=new SupplierItems();
        SetPanel sp = new SetPanel();
        sp.SetPanel(si);
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btn333ActionPerformed

    private void cmb365FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb365FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb365, lbl318);
    }//GEN-LAST:event_cmb365FocusLost

    private void btn399ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn399ActionPerformed
        txtF328.getText().toString();
        txtF329.setText("Copper Rods");
        txtF330.setText("2000");
        cmb399.setSelectedIndex(1);
        
        
    }//GEN-LAST:event_btn399ActionPerformed

    private void txtF323KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF323KeyReleased
        DbAccessPurchase dba = new DbAccessPurchase("itemlist", "itemname", txtF323.getText().toString());
        dba.viewSuplierItemsOnTBLserch(tbl318, lblResultCount2);
    }//GEN-LAST:event_txtF323KeyReleased

    private void cmb399FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb399FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb399, lbl329);
    }//GEN-LAST:event_cmb399FocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn325;
    private javax.swing.JButton btn326;
    private javax.swing.JButton btn327;
    private javax.swing.JButton btn331;
    private javax.swing.JButton btn332;
    private javax.swing.JButton btn333;
    private javax.swing.JButton btn399;
    private javax.swing.JComboBox<String> cmb365;
    private javax.swing.JComboBox<String> cmb399;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpnl302;
    private javax.swing.JPanel jpnl304;
    private javax.swing.JPanel jpnl317;
    private javax.swing.JPanel jpnl336;
    private javax.swing.JLabel lbl315;
    private javax.swing.JLabel lbl316;
    private javax.swing.JLabel lbl317;
    private javax.swing.JLabel lbl318;
    private javax.swing.JLabel lbl319;
    private javax.swing.JLabel lbl329;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblItemID1;
    private javax.swing.JLabel lblItemID3;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemName2;
    private javax.swing.JLabel lblPurchaseID;
    private javax.swing.JLabel lblResultCount2;
    private javax.swing.JLabel lblResultCount300;
    private javax.swing.JLabel lblResultCount301;
    private javax.swing.JLabel lblSearchSalesID;
    private javax.swing.JScrollPane tbl307;
    private javax.swing.JScrollPane tbl309;
    private javax.swing.JScrollPane tbl310;
    private javax.swing.JTable tbl318;
    private javax.swing.JTable tbl331;
    private javax.swing.JTable tbl333;
    private javax.swing.JTextField txtF323;
    private javax.swing.JTextField txtF328;
    private javax.swing.JTextField txtF329;
    private javax.swing.JTextField txtF330;
    private javax.swing.JTextField txtF333;
    // End of variables declaration//GEN-END:variables
}
