/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PurchaseManagement;

import RootElement.DbConnect;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Samitha Heanthenna
 */
public class SupplierManagment extends javax.swing.JPanel {

    /**
     * Creates new form SupplierManagment
     */
    public SupplierManagment() {
        ComboKeyHandler cm;
        
        initComponents();
        
        DbConnect c=new DbConnect();
        c.setConnection();
        
            try
            {                                                                             
                ResultSet qresults;
                Statement statem1=c.con.createStatement();
                qresults=statem1.executeQuery("select * from supplier");
                               
                String ids="";
            
                while(qresults.next())
                {
                    ids=qresults.getString("supplierId");
                }
                
                IdIncrementPurchase inc=new IdIncrementPurchase(ids,'s');
                String newids=inc.getIncrementedId();
                
                txtF303.setText(newids);
                

                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(this,"Error Connecting to Database", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            finally
            {
                try 
                {
                c.con.close();
                } 
                catch (SQLException ex) 
                {
                Logger.getLogger(PurchaseOrders.class.getName()).log(Level.SEVERE, null, ex);
                }
                
            }
            
            DbAccessPurchase dba = new DbAccessPurchase("supplier");
            dba.fillTableSupplierManagement(tbl314, lblResultCount);
            
            DbAccessPurchase dba2 = new DbAccessPurchase("supplier");
            dba2.fillTable(tbl333, lblResultCount301);
            
            DbAccessPurchase dba3 = new DbAccessPurchase("supplier","supplierName");
            dba3.fillCombo(cmb365);
            cm=new ComboKeyHandler(cmb365);
            
            cmb365.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                cm.keyTyped(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblPurchaseID = new javax.swing.JLabel();
        txtF303 = new javax.swing.JTextField();
        lblItemName = new javax.swing.JLabel();
        lblItemID = new javax.swing.JLabel();
        lblQuentity = new javax.swing.JLabel();
        lblDatePurchased = new javax.swing.JLabel();
        lblPurchaseType = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lbl304 = new javax.swing.JLabel();
        lbl306 = new javax.swing.JLabel();
        lbl305 = new javax.swing.JLabel();
        lbl303 = new javax.swing.JLabel();
        lbl301 = new javax.swing.JLabel();
        btn312 = new javax.swing.JButton();
        btn313 = new javax.swing.JButton();
        jpnl302 = new javax.swing.JPanel();
        tbl307 = new javax.swing.JScrollPane();
        tbl314 = new javax.swing.JTable();
        lblResultCount = new javax.swing.JLabel();
        txtF304 = new javax.swing.JTextField();
        txtF305 = new javax.swing.JTextField();
        txtF306 = new javax.swing.JTextField();
        txtF308 = new javax.swing.JTextField();
        txtF311 = new javax.swing.JTextField();
        lbl307 = new javax.swing.JLabel();
        lbl308 = new javax.swing.JLabel();
        cmb305 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta302 = new javax.swing.JTextArea();
        btn399 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblItemName2 = new javax.swing.JLabel();
        cmb365 = new javax.swing.JComboBox<>();
        jpnl304 = new javax.swing.JPanel();
        tbl310 = new javax.swing.JScrollPane();
        tbl333 = new javax.swing.JTable();
        lblResultCount301 = new javax.swing.JLabel();
        btn333 = new javax.swing.JButton();
        lbl311 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(790, 590));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblPurchaseID.setText("Supplier ID");

        txtF303.setEditable(false);

        lblItemName.setText("Supplier Name");

        lblItemID.setText("Company Name");

        lblQuentity.setText("Address");

        lblDatePurchased.setText("Telephone");

        lblPurchaseType.setText("Email");

        lblPrice.setText("Specialization");

        lblStatus.setText("Supply Type");

        lbl304.setBackground(new java.awt.Color(255, 255, 255));
        lbl304.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl304.setForeground(new java.awt.Color(255, 0, 0));

        lbl306.setBackground(new java.awt.Color(255, 255, 255));
        lbl306.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl306.setForeground(new java.awt.Color(255, 0, 0));

        lbl305.setBackground(new java.awt.Color(255, 255, 255));
        lbl305.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl305.setForeground(new java.awt.Color(255, 0, 0));

        lbl303.setBackground(new java.awt.Color(255, 255, 255));
        lbl303.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl303.setForeground(new java.awt.Color(255, 0, 0));

        lbl301.setBackground(new java.awt.Color(255, 255, 255));
        lbl301.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl301.setForeground(new java.awt.Color(255, 0, 0));

        btn312.setText("Add ");
        btn312.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn312ActionPerformed(evt);
            }
        });

        btn313.setText("Cancel ");
        btn313.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn313ActionPerformed(evt);
            }
        });

        jpnl302.setBackground(new java.awt.Color(255, 255, 255));
        jpnl302.setBorder(javax.swing.BorderFactory.createTitledBorder("Available Suppliers"));

        tbl314.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Supplier ID", "Supplier_Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl307.setViewportView(tbl314);

        lblResultCount.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl302Layout = new javax.swing.GroupLayout(jpnl302);
        jpnl302.setLayout(jpnl302Layout);
        jpnl302Layout.setHorizontalGroup(
            jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl302Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnl302Layout.createSequentialGroup()
                        .addComponent(lblResultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 126, Short.MAX_VALUE))
                    .addComponent(tbl307, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnl302Layout.setVerticalGroup(
            jpnl302Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl302Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl307, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultCount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        txtF304.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF304FocusLost(evt);
            }
        });
        txtF304.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF304KeyTyped(evt);
            }
        });

        txtF305.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF305FocusLost(evt);
            }
        });
        txtF305.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF305KeyTyped(evt);
            }
        });

        txtF306.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF306FocusLost(evt);
            }
        });
        txtF306.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF306KeyTyped(evt);
            }
        });

        txtF308.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF308FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF308FocusLost(evt);
            }
        });

        txtF311.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF311FocusLost(evt);
            }
        });
        txtF311.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF311KeyTyped(evt);
            }
        });

        lbl307.setBackground(new java.awt.Color(255, 255, 255));
        lbl307.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl307.setForeground(new java.awt.Color(255, 0, 0));

        lbl308.setBackground(new java.awt.Color(255, 255, 255));
        lbl308.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl308.setForeground(new java.awt.Color(255, 0, 0));

        cmb305.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Local", "Foreign" }));
        cmb305.setSelectedIndex(-1);
        cmb305.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb305FocusLost(evt);
            }
        });

        txta302.setColumns(20);
        txta302.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        txta302.setRows(5);
        txta302.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txta302FocusLost(evt);
            }
        });
        jScrollPane1.setViewportView(txta302);

        btn399.setText("Demo");
        btn399.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn399ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPurchaseID)
                    .addComponent(lblItemName)
                    .addComponent(lblItemID)
                    .addComponent(lblQuentity)
                    .addComponent(lblPurchaseType)
                    .addComponent(lblPrice)
                    .addComponent(lblStatus)
                    .addComponent(lblDatePurchased))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF303, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF304, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtF306, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                                .addComponent(txtF305, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtF308, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtF311, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(cmb305, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl301, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl303, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl306, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl304, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl305, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl307, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl308, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn399, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(btn312, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn313, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnl302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnl302, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtF303, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txtF304, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(lbl301, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbl303, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblItemID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtF306, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPurchaseID)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl304, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQuentity, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDatePurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl305, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPurchaseType, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF308, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl306, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF311, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPrice)
                            .addComponent(lbl307, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb305, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStatus)
                            .addComponent(lbl308, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn313)
                    .addComponent(btn312)
                    .addComponent(btn399)))
        );

        jTabbedPane1.addTab("Add Supplier", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lblItemName2.setText("Supplier Name");

        cmb365.setEditable(true);
        cmb365.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb365FocusLost(evt);
            }
        });

        jpnl304.setBackground(new java.awt.Color(255, 255, 255));
        jpnl304.setBorder(javax.swing.BorderFactory.createTitledBorder("Supplier Details"));

        tbl333.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Supplier_ID", "Item_ID", "Item_Name", "Supplier_ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl310.setViewportView(tbl333);

        lblResultCount301.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblResultCount301.setForeground(new java.awt.Color(0, 153, 51));
        lblResultCount301.setText("0 Maching record(s) found");

        javax.swing.GroupLayout jpnl304Layout = new javax.swing.GroupLayout(jpnl304);
        jpnl304.setLayout(jpnl304Layout);
        jpnl304Layout.setHorizontalGroup(
            jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl304Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbl310, javax.swing.GroupLayout.DEFAULT_SIZE, 682, Short.MAX_VALUE)
                    .addGroup(jpnl304Layout.createSequentialGroup()
                        .addComponent(lblResultCount301, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpnl304Layout.setVerticalGroup(
            jpnl304Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl304Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl310, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblResultCount301, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btn333.setText("Remove");
        btn333.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn333ActionPerformed(evt);
            }
        });

        lbl311.setBackground(new java.awt.Color(255, 255, 255));
        lbl311.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl311.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn333, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(cmb365, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl311, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(lblItemName2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jpnl304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(26, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl311, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb365))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 456, Short.MAX_VALUE)
                .addComponent(btn333)
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(32, 32, 32)
                    .addComponent(lblItemName2)
                    .addGap(31, 31, 31)
                    .addComponent(jpnl304, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Remove Supplier", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 589, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn313ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn313ActionPerformed
        SupplierManagment sm = new SupplierManagment();
        SetPanel sp = new SetPanel();
        sp.SetPanel(sm);
    }//GEN-LAST:event_btn313ActionPerformed

    private void btn312ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn312ActionPerformed
        if(lbl301.getText().equals("!")||lbl303.getText().equals("!")||lbl304.getText().equals("!")||lbl305.getText().equals("!")||lbl306.getText().equals("!")||lbl307.getText().equals("!")||lbl308.getText().equals("!")){
        
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
            
        }
        
        else if(cmb305.getSelectedIndex()==-1||txtF304.getText().isEmpty()||txtF311.getText().isEmpty()||txtF306.getText().isEmpty()||txta302.getText().isEmpty()||txtF305.getText().isEmpty()||txtF308.getText().isEmpty()){
        
            TextValidatorPurchase tv = new TextValidatorPurchase();
            
            if(cmb305.getSelectedIndex()==-1){
                tv.comboSelection(cmb305, lbl308);
            }
            if(txtF304.getText().isEmpty()){
                lbl301.setText("!");
            }
            if(txtF306.getText().isEmpty()){
                lbl303.setText("!");
            }
            if(txta302.getText().isEmpty()){
                lbl304.setText("!");
            }
            if(txtF305.getText().isEmpty()){
                lbl305.setText("!");
            }
            if(txtF308.getText().isEmpty()){
                lbl306.setText("!");
            }
            if(txtF311.getText().isEmpty()){
                lbl307.setText("!");
            }
            
            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }
       
        else{
            //insertion code
            
            DbAccessPurchase dba = new DbAccessPurchase();
            dba.addSupplier(txtF303.getText().toString(),txtF304.getText().toString(),txtF306.getText().toString(),txta302.getText().toString(),txtF305.getText().toString(),txtF308.getText().toString(),txtF311.getText().toString(),cmb305.getSelectedItem().toString());
            JOptionPane.showMessageDialog(this, "Supplier details recorded successfuly");
        
        
        SupplierManagment sm = new SupplierManagment();
        SetPanel sp = new SetPanel();
        sp.SetPanel(sm);
    }//GEN-LAST:event_btn312ActionPerformed
    }
    private void txtF305KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF305KeyTyped
        if(txtF305.getText().length()<10){
                   if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF305KeyTyped

    private void txtF311KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF311KeyTyped
         if(txtF311.getText().length()<=20){
                   if((Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF311KeyTyped

    private void txtF304KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF304KeyTyped
         if(txtF304.getText().length()<=20){
                   if((Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF304KeyTyped

    private void cmb365FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb365FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb365, lbl311);
    }//GEN-LAST:event_cmb365FocusLost

    private void btn333ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn333ActionPerformed

        if(cmb365.getSelectedIndex()==-1){
            lbl311.setText("!");
        }

        if(lbl311.getText().equals("!")){

            JOptionPane.showMessageDialog(this,"One or more fields contain invalid data", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        try{
            DbAccessPurchase dba = new DbAccessPurchase("supplier","supplierName", cmb365.getSelectedItem().toString());
            dba.remove();

            JOptionPane.showMessageDialog(this, "Item removed successfuly");
            
            cmb365.setSelectedIndex(-1);

            DbAccessPurchase dba1 = new DbAccessPurchase("supplier");
            dba1.viewSuplierItemsOnTBL(tbl333, lblResultCount301);

            SupplierManagment sm = new SupplierManagment();
            SetPanel sp = new SetPanel();
            sp.SetPanel(sm);
        }
        catch (Exception e){
        }
    }//GEN-LAST:event_btn333ActionPerformed

    private void txtF308FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF308FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF308.getText().toString());
        tv.empty(lbl306);
        
        TextValidatorPurchase tv2 = new TextValidatorPurchase(txtF308.getText().toString());
        if(tv2.isEmail()){
            lbl306.setText("");
        }
        else{
            lbl306.setText("!");
        }
    }//GEN-LAST:event_txtF308FocusLost

    private void txtF308FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF308FocusGained
        lbl306.setText("");
    }//GEN-LAST:event_txtF308FocusGained

    private void txtF304FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF304FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF304.getText().toString());
        tv.empty(lbl301);
    }//GEN-LAST:event_txtF304FocusLost

    private void txtF306KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF306KeyTyped
       if(txtF306.getText().length()<50){     
        }
            else
            evt.consume();
    }//GEN-LAST:event_txtF306KeyTyped

    private void txtF306FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF306FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF306.getText().toString());
        tv.empty(lbl303);
    }//GEN-LAST:event_txtF306FocusLost

    private void txta302FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txta302FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txta302.getText().toString());
        tv.empty(lbl304);
    }//GEN-LAST:event_txta302FocusLost

    private void txtF305FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF305FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF305.getText().toString());
        tv.empty(lbl305);
        
        if(txtF305.getText().length()<10){
                         lbl305.setText("!");
        }
    }//GEN-LAST:event_txtF305FocusLost

    private void txtF311FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF311FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase(txtF311.getText().toString());
        tv.empty(lbl307);
    }//GEN-LAST:event_txtF311FocusLost

    private void cmb305FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb305FocusLost
        TextValidatorPurchase tv = new TextValidatorPurchase();
        tv.comboSelection(cmb305, lbl308);
    }//GEN-LAST:event_cmb305FocusLost

    private void btn399ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn399ActionPerformed
        cmb305.setSelectedIndex(0);
        txtF304.setText("Mr.Sunil Perera");
        txtF306.setText("ABC Globle Traders");
        txta302.setText("No123 Katugasthota road, Kandy");
        txtF305.setText("0756990877");
        txtF308.setText("info@abcgloble.lk");
        txtF311.setText("Chemicals");
        
    }//GEN-LAST:event_btn399ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn312;
    private javax.swing.JButton btn313;
    private javax.swing.JButton btn333;
    private javax.swing.JButton btn399;
    private javax.swing.JComboBox<String> cmb305;
    private javax.swing.JComboBox<String> cmb365;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpnl302;
    private javax.swing.JPanel jpnl304;
    private javax.swing.JLabel lbl301;
    private javax.swing.JLabel lbl303;
    private javax.swing.JLabel lbl304;
    private javax.swing.JLabel lbl305;
    private javax.swing.JLabel lbl306;
    private javax.swing.JLabel lbl307;
    private javax.swing.JLabel lbl308;
    private javax.swing.JLabel lbl311;
    private javax.swing.JLabel lblDatePurchased;
    private javax.swing.JLabel lblItemID;
    private javax.swing.JLabel lblItemName;
    private javax.swing.JLabel lblItemName2;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblPurchaseID;
    private javax.swing.JLabel lblPurchaseType;
    private javax.swing.JLabel lblQuentity;
    private javax.swing.JLabel lblResultCount;
    private javax.swing.JLabel lblResultCount301;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JScrollPane tbl307;
    private javax.swing.JScrollPane tbl310;
    private javax.swing.JTable tbl314;
    private javax.swing.JTable tbl333;
    private javax.swing.JTextField txtF303;
    private javax.swing.JTextField txtF304;
    private javax.swing.JTextField txtF305;
    private javax.swing.JTextField txtF306;
    private javax.swing.JTextField txtF308;
    private javax.swing.JTextField txtF311;
    private javax.swing.JTextArea txta302;
    // End of variables declaration//GEN-END:variables
}
