/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package DistributionManagement;

import java.awt.Component;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Shali
 */
public class ManageVehicles extends javax.swing.JPanel {

    /**
     * Creates new form Manage_Vehicles
     */
    public ManageVehicles() {
        initComponents();
       //Add Tab --- Load Department Combo with divisions
        SQL man =new  SQL();
        man.fillComboBox(jcmb101,"occupation","division");
        
        //Update Tab --- Department Combo
         SQL l1 = new SQL();
        l1.fillComboBox(cmb131,"occupation","division");
         
        // Load Vehicle Numbers
        SQL l2 = new SQL();
        l2.fillComboBox(cmb113,"vehicle","vehicleNo");
        
         
        
        //Vehicle Details Table
         SQL q3= new SQL();
         q3.SearchVehiclesAll(jTable102,"");
       
        
    
        
        
      /* SQL man1= new SQL();
        man1.fillComboBox(cmb113,"vehicle","vehicleNo");
        
        */
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtF100 = new javax.swing.JTextField();
        txtF101 = new javax.swing.JTextField();
        txtF103 = new javax.swing.JTextField();
        jDateChooser105 = new com.toedter.calendar.JDateChooser();
        txtF104 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtF105 = new javax.swing.JTextField();
        err101 = new javax.swing.JLabel();
        err102 = new javax.swing.JLabel();
        err103 = new javax.swing.JLabel();
        err104 = new javax.swing.JLabel();
        err105 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtAr100 = new javax.swing.JTextArea();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel110 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcmb101 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jcmb100 = new javax.swing.JComboBox<>();
        jButton100 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jcmb102 = new javax.swing.JComboBox<>();
        jLayeredPane6 = new javax.swing.JLayeredPane();
        cmb165 = new javax.swing.JComboBox<>();
        jlbl_hidden_111 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton120 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea136 = new javax.swing.JTextArea();
        cmb113 = new javax.swing.JComboBox<>();
        jLayeredPane5 = new javax.swing.JLayeredPane();
        jLabel15 = new javax.swing.JLabel();
        cmb130 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        cmb131 = new javax.swing.JComboBox<>();
        jLayeredPane7 = new javax.swing.JLayeredPane();
        cmb147 = new javax.swing.JComboBox<>();
        jbtn104 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLayeredPane8 = new javax.swing.JLayeredPane();
        lbl130 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable102 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jTextField123 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable178 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel132 = new javax.swing.JLabel();
        count150 = new javax.swing.JLabel();

        jLabel12.setText("jLabel12");

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(790, 590));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(790, 590));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(790, 590));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(790, 590));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(790, 590));
        jTabbedPane1.setRequestFocusEnabled(false);
        jTabbedPane1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane1StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 590));
        jPanel1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jPanel1PropertyChange(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehile Identification"));

        jLabel1.setText("Registered Date  ");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(10, 190, 120, 20);

        jLabel2.setText("Vehicle Number   ");
        jLayeredPane1.add(jLabel2);
        jLabel2.setBounds(10, 50, 120, 20);

        jLabel3.setText("Make ");
        jLayeredPane1.add(jLabel3);
        jLabel3.setBounds(10, 80, 120, 20);

        jLabel4.setText("Model ");
        jLayeredPane1.add(jLabel4);
        jLabel4.setBounds(10, 110, 120, 20);

        jLabel5.setText("Color ");
        jLayeredPane1.add(jLabel5);
        jLabel5.setBounds(10, 150, 120, 20);

        txtF100.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF100FocusLost(evt);
            }
        });
        txtF100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF100ActionPerformed(evt);
            }
        });
        txtF100.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF100KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF100KeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtF100);
        txtF100.setBounds(130, 50, 140, 20);

        txtF101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF101ActionPerformed(evt);
            }
        });
        txtF101.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF101KeyReleased(evt);
            }
        });
        jLayeredPane1.add(txtF101);
        txtF101.setBounds(130, 80, 140, 20);

        txtF103.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF103KeyReleased(evt);
            }
        });
        jLayeredPane1.add(txtF103);
        txtF103.setBounds(130, 110, 140, 20);
        jLayeredPane1.add(jDateChooser105);
        jDateChooser105.setBounds(130, 190, 140, 20);

        txtF104.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF104KeyReleased(evt);
            }
        });
        jLayeredPane1.add(txtF104);
        txtF104.setBounds(130, 150, 140, 20);

        jLabel7.setText("Weight ");
        jLayeredPane1.add(jLabel7);
        jLabel7.setBounds(10, 230, 120, 20);

        txtF105.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF105KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF105KeyTyped(evt);
            }
        });
        jLayeredPane1.add(txtF105);
        txtF105.setBounds(130, 230, 140, 20);

        err101.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err101.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.add(err101);
        err101.setBounds(270, 50, 40, 20);

        err102.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err102.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.add(err102);
        err102.setBounds(270, 80, 40, 20);

        err103.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err103.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.add(err103);
        err103.setBounds(270, 110, 40, 20);

        err104.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err104.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.add(err104);
        err104.setBounds(270, 150, 40, 20);

        err105.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        err105.setForeground(new java.awt.Color(255, 0, 0));
        jLayeredPane1.add(err105);
        err105.setBounds(270, 230, 40, 20);

        jLayeredPane2.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));

        jtxtAr100.setColumns(20);
        jtxtAr100.setRows(5);
        jScrollPane1.setViewportView(jtxtAr100);

        jLayeredPane2.add(jScrollPane1);
        jScrollPane1.setBounds(10, 20, 320, 80);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        jLabel110.setForeground(new java.awt.Color(255, 255, 255));
        jLayeredPane3.add(jLabel110);
        jLabel110.setBounds(10, 20, 240, 200);

        jLabel6.setText("Department ");

        jLabel9.setText("Type ");

        jcmb101.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcmb101MouseClicked(evt);
            }
        });
        jcmb101.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb101ActionPerformed(evt);
            }
        });

        jLabel10.setText("Location ");

        jcmb100.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Car", "Van", "Jeep", "Lorry", "Truck", "Tuk Tuk" }));
        jcmb100.setSelectedIndex(-1);
        jcmb100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmb100ActionPerformed(evt);
            }
        });

        jButton100.setText("OK");
        jButton100.setBorderPainted(false);
        jButton100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton100ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jcmb102.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelaniya", "Borella", "Warehouse1", "Warehouse2" }));
        jcmb102.setSelectedIndex(-1);

        jLayeredPane6.setBorder(javax.swing.BorderFactory.createTitledBorder("Status"));

        cmb165.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));
        cmb165.setSelectedIndex(-1);

        jLayeredPane6.setLayer(cmb165, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane6Layout = new javax.swing.GroupLayout(jLayeredPane6);
        jLayeredPane6.setLayout(jLayeredPane6Layout);
        jLayeredPane6Layout.setHorizontalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb165, 0, 217, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane6Layout.setVerticalGroup(
            jLayeredPane6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb165, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbl_hidden_111.setBackground(new java.awt.Color(255, 255, 255));
        jlbl_hidden_111.setForeground(new java.awt.Color(255, 255, 255));

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton120.setText("Select Image ");
        jButton120.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton120ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(50, 50, 50)
                        .addComponent(jButton100, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3)
                        .addGap(100, 100, 100))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlbl_hidden_111, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 325, Short.MAX_VALUE)
                        .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(496, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jcmb100, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jcmb102, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(80, 80, 80)
                                    .addComponent(jcmb101, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton120, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(100, 100, 100)
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(241, Short.MAX_VALUE)
                .addComponent(jButton120)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLayeredPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbl_hidden_111, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcmb100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmb102, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcmb101, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton100)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(0, 0, Short.MAX_VALUE)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)))
                    .addGap(60, 60, 60)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 86, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Add Vehicle Details", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 590));

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Details"));

        jLabel13.setText("Vehicle Number ");

        jLabel14.setText("Description ");

        txtArea136.setColumns(20);
        txtArea136.setRows(5);
        jScrollPane2.setViewportView(txtArea136);

        cmb113.setAutoscrolls(true);
        cmb113.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb113ItemStateChanged(evt);
            }
        });
        cmb113.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb113FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb113FocusLost(evt);
            }
        });
        cmb113.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb113ActionPerformed(evt);
            }
        });
        cmb113.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb113PropertyChange(evt);
            }
        });
        cmb113.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cmb113KeyReleased(evt);
            }
        });

        jLayeredPane4.setLayer(jLabel13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel14, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(cmb113, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addGap(28, 28, 28)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                    .addComponent(cmb113, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(cmb113, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLayeredPane5.setBorder(javax.swing.BorderFactory.createTitledBorder("Location"));

        jLabel15.setText("Location ");

        cmb130.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kelaniya", "Borella", "Warehouse1", "Warehouse2" }));
        cmb130.setSelectedIndex(-1);

        jLabel16.setText("Department");

        cmb131.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb131ActionPerformed(evt);
            }
        });

        jLayeredPane5.setLayer(jLabel15, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(cmb130, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(jLabel16, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane5.setLayer(cmb131, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane5Layout = new javax.swing.GroupLayout(jLayeredPane5);
        jLayeredPane5.setLayout(jLayeredPane5Layout);
        jLayeredPane5Layout.setHorizontalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(55, 55, 55)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmb130, 0, 96, Short.MAX_VALUE)
                    .addComponent(cmb131, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        jLayeredPane5Layout.setVerticalGroup(
            jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmb130, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jLayeredPane5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(cmb131, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jLayeredPane7.setBorder(javax.swing.BorderFactory.createTitledBorder("Vehicle Status "));

        cmb147.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Available", "Not Available" }));

        jLayeredPane7.setLayer(cmb147, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane7Layout = new javax.swing.GroupLayout(jLayeredPane7);
        jLayeredPane7.setLayout(jLayeredPane7Layout);
        jLayeredPane7Layout.setHorizontalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb147, 0, 234, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane7Layout.setVerticalGroup(
            jLayeredPane7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane7Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(cmb147, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        jbtn104.setText("Save Changes ");
        jbtn104.setEnabled(false);
        jbtn104.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn104ActionPerformed(evt);
            }
        });

        jButton5.setText("Cancel ");

        jLayeredPane8.setBorder(javax.swing.BorderFactory.createTitledBorder("Image"));

        jLayeredPane8.setLayer(lbl130, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane8Layout = new javax.swing.GroupLayout(jLayeredPane8);
        jLayeredPane8.setLayout(jLayeredPane8Layout);
        jLayeredPane8Layout.setHorizontalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl130, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
        );
        jLayeredPane8Layout.setVerticalGroup(
            jLayeredPane8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl130, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(92, 92, 92)
                                .addComponent(jbtn104)
                                .addGap(30, 30, 30)
                                .addComponent(jButton5))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLayeredPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredPane4)
                    .addComponent(jLayeredPane8))
                .addGap(51, 51, 51)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLayeredPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn104)
                    .addComponent(jButton5))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Vehicle Details", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(790, 590));

        jTable102.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registration Num", "Type ", "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jTable102);
        if (jTable102.getColumnModel().getColumnCount() > 0) {
            jTable102.getColumnModel().getColumn(0).setResizable(false);
            jTable102.getColumnModel().getColumn(1).setResizable(false);
            jTable102.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton6.setText("Delete Vehicle ");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Clear");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 574, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jButton6)
                        .addGap(75, 75, 75)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addGap(180, 180, 180))
        );

        jTabbedPane1.addTab("Delete Vehicle ", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(790, 590));

        jTextField123.setText("Reg.Number ");
        jTextField123.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextField123FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextField123FocusLost(evt);
            }
        });
        jTextField123.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField123ActionPerformed(evt);
            }
        });
        jTextField123.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField123KeyReleased(evt);
            }
        });

        jTable178.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Number ", "Type", "Location", "Department", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable178);

        jButton1.setText("View all");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(88, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(count150, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jTextField123, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 567, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(59, 59, 59)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel132, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(count150, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Search Vehicle", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:\
        
        //Clear Fields
        
    
        ManageVehicles mg = new ManageVehicles();
        
            SetPanel n = new SetPanel();
            n.SetPanel(mg);
                    
       
              
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcmb100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmb100ActionPerformed

    private void jcmb101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmb101ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jcmb101ActionPerformed

    private void jButton120ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton120ActionPerformed
        // TODO add your handling code here:
        String image_path=null;
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);

        try {
            File f = fc.getSelectedFile();
            image_path = f.getAbsolutePath();

           
        } catch (Exception e) {
        }

        jLabel110.setIcon(new ImageIcon(new ImageIcon(image_path).getImage().getScaledInstance(240,240, Image.SCALE_DEFAULT)));
       // jButton120.setVisible(false);
       jlbl_hidden_111.setText(image_path);
        
    }//GEN-LAST:event_jButton120ActionPerformed

    private void txtF100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF100ActionPerformed

    private void jTextField123FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField123FocusGained
        // TODO add your handling code here:
        
       jTextField123.setText(null);
        
    }//GEN-LAST:event_jTextField123FocusGained

    private void jTextField123FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextField123FocusLost
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jTextField123FocusLost

    private void jButton100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton100ActionPerformed
        // TODO add your handling code here:
        
        
         int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you wish to continue?", "Confirm ", dialogButton);
       if(dialogResult == 0)
        {
        
            
            
         if( ( ((jDateChooser105.getDate()!=null))|| (err101.getText()==null)||  (err102.getText()==null)  || (err103.getText()==null) || (err104.getText()==null)  || (err105.getText()==null)) && ( (jcmb100.getSelectedIndex()!=-1)&& (jcmb101.getSelectedIndex()!=-1)&& (jcmb102.getSelectedIndex()!=-1) ) && (cmb165.getSelectedIndex()!=-1))
                 {
                     DateFormat fmt1 = new SimpleDateFormat("yyyy/MM/dd");
                     String date1= fmt1.format(this.jDateChooser105.getDate());
        
        // 
         
                        DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd");
                        Date dateq = new Date();
         
     
        
                            String today = dateFormat.format(dateq);
        
         try{
            Date d1 = fmt1.parse(date1);
            Date d2 = fmt1.parse(today);
                
            
                     
                     
                     if(((jLabel110.getIcon()==null))||(d1.after(d2)))
            {
                JOptionPane.showMessageDialog(null, "One or more fields contain invalid data", "Error!", JOptionPane.ERROR_MESSAGE);

                
            }
                     
                     else
                     {
        
            //System.out.println("Success ");
            
            //Querries Come here 
            SQL q1 = new SQL();
             try { 
                 //Execute Query
                 
                 q1.AddVehicleDetails(txtF100, txtF101, txtF103, jcmb100, txtF104, txtF105, jlbl_hidden_111, jtxtAr100, jDateChooser105, cmb165, jcmb101, jcmb102);
             
                 jLabel110.setIcon(null);
                 jButton120.setVisible(true);
                JOptionPane.showMessageDialog(null, "Vehicle Added Successfuly ", "Successful!", JOptionPane.WARNING_MESSAGE);
                
                SetPanel p1 = new SetPanel();
                ManageVehicles mm= new ManageVehicles();
                p1.SetPanel(mm);
                        

             
             
             
             
             } catch (FileNotFoundException ex) {
                 System.out.println("Error "+ex);
             }
                     }
             
         }
         catch(Exception i)
         {
         
             System.out.println(i);
         }
          
        
        }  
        
        else 
        {
              JOptionPane.showMessageDialog(null, "One or more fields contain invalid data", "Error!", JOptionPane.ERROR_MESSAGE);

        }
        
        }
       else {
       
       
       }
        
          // System.out.println(jlbl_hidden_111.getText());
           
        
        
    }//GEN-LAST:event_jButton100ActionPerformed

    private void txtF100KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF100KeyReleased
        // TODO add your handling code here:
        String num = "[0-9]+"; 
        String charac="[-]+";
        String alpha = "[a-zA-Z]+";
        String patern1=("^[A-Z]{2}-\\d{4}");
        String patern2=("^[A-Z]{3}-\\d{4}");
        
        
        
        
        
        TextValidator tv1 = new TextValidator(txtF100.getText());
        tv1.checkEmpty(err101);
        
        
        if((txtF100.getText().matches(patern1))||(txtF100.getText().matches(patern2)))
        {
            System.out.println("Valid");
        
        }
        else
        {
            err101.setText(" !");
        }
     
    }//GEN-LAST:event_txtF100KeyReleased

    private void txtF101KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF101KeyReleased
        // TODO add your handling code here:
        
        TextValidator tv2 = new TextValidator(txtF101.getText());
        tv2.checkEmpty(err102);
            if(!tv2.isName())
            {
                err102.setText(" !");
            }
        
    }//GEN-LAST:event_txtF101KeyReleased

    private void txtF101ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF101ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF101ActionPerformed

    private void txtF103KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF103KeyReleased
        // TODO add your handling code here:
        TextValidator tv3 = new TextValidator(txtF103.getText());
        tv3.checkEmpty(err103);
            
    }//GEN-LAST:event_txtF103KeyReleased

    private void txtF104KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF104KeyReleased
        // TODO add your handling code here:
        TextValidator tv3 = new TextValidator(txtF104.getText());
        tv3.checkEmpty(err104);
        
        
        TextValidator tv4 = new TextValidator(txtF104.getText());
        tv4.checkEmpty(err104);
            if(!tv4.isName())
            {
                err104.setText(" !");
            }
            
    }//GEN-LAST:event_txtF104KeyReleased

    private void txtF105KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF105KeyReleased
        // TODO add your handling code here:
        
         TextValidator tv3 = new TextValidator(txtF105.getText());
         tv3.checkEmpty(err105);
        
         if(!txtF105.getText().matches("[0-9]+"))
         {
             err105.setText(" !");
         }
        
        
    }//GEN-LAST:event_txtF105KeyReleased

    private void jcmb101MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmb101MouseClicked
        // TODO add your handling code here:
        
        
       
    }//GEN-LAST:event_jcmb101MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        
         String selectedObject = (String) (Object) jTable102.getModel().getValueAt(jTable102.getSelectedRow(),jTable102.getSelectedColumn());
        
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Are you sure you want to delete ?", "Confirm ", dialogButton);
       if(dialogResult == 0)
        {
        //System.out.println("Yes option");
         
         
      // System.out.println(jTable102.getSelectedRow());
      
         SQL l1 = new SQL();
         l1.DelVehicle(selectedObject); 
      
         RemoveFromTable(jTable102.getSelectedRow(),jTable102);
       
       
        
       } 
        else 
        {
        //System.out.println("No Option");
        } 
        
        
        
        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jbtn104ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn104ActionPerformed

            // TODO add your handling code here:
            
             int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Do you wish to continue?", "Confirm ", dialogButton);
       if(dialogResult == 0)
        {
        
            
    
            if ( ((cmb130.getSelectedIndex()==-1)|| (cmb131.getSelectedIndex()== -1) ) /*&& (!jCheckBox103.isSelected()) && (!jCheckBox104.isSelected()) */ )
            {
                
            JOptionPane.showMessageDialog(null, "One or more Empty Fields!", "Error!", JOptionPane.ERROR_MESSAGE);
            
            }
            
            else 
            {
                SQL up = new SQL ();
                up.UpdateVehicle(cmb113, cmb130, cmb131, cmb147, txtArea136, lbl130);
               JOptionPane.showMessageDialog(null, "Vehicle Updated Successfuly ", "Successful!", JOptionPane.WARNING_MESSAGE);

            
            
            }
            
        
            
           //refresh Panel  
          ManageVehicles mv = new ManageVehicles();
          SetPanel p= new SetPanel();
          p.SetPanel(mv);
       
        }
       
       else 
       {
       
       }
          
    }//GEN-LAST:event_jbtn104ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        SQL q2= new SQL();
        q2.SearchVehiclesAll(jTable178,"");
        
        count150.setText("Records : "+jTable178.getRowCount());
       
     
     
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmb113ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb113ActionPerformed
       
     
        
    }//GEN-LAST:event_cmb113ActionPerformed

    private void cmb131ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb131ActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_cmb131ActionPerformed

    private void cmb113ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb113ItemStateChanged
        // TODO add your handling code here:
        
        
      
        
       
        
        
        
         
    }//GEN-LAST:event_cmb113ItemStateChanged

    private void cmb113KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb113KeyReleased
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_cmb113KeyReleased

    private void cmb113PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb113PropertyChange
        // TODO add your handling code here:
        
        
        SQL up= new SQL();
        
        
        up.SetVehicleDetails_UpdateTab(cmb113, cmb130, cmb131, cmb147, txtArea136, lbl130);
        
     
          
    }//GEN-LAST:event_cmb113PropertyChange

    private void cmb113FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb113FocusGained
        // TODO add your handling code here:SQL l2 = new SQL();
        
    }//GEN-LAST:event_cmb113FocusGained

    private void txtF100FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF100FocusLost
        // TODO add your handling code here:
        SQL ch1= new SQL();
        
        if(!ch1.CheckifExists(txtF100,"vehicle","vehicleNo"))
        {
            JOptionPane.showMessageDialog(null, "Number is invalid or existing!", "Error!", JOptionPane.ERROR_MESSAGE);

        
        }
        
        else 
        {
        // JOptionPane.showMessageDialog(null, "Number is Valiid!", "Error!", JOptionPane.ERROR_MESSAGE);

        }
        
    }//GEN-LAST:event_txtF100FocusLost

    private void cmb113FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb113FocusLost
        // TODO add your handling code here:
        
         jbtn104.setEnabled(true);
        
    }//GEN-LAST:event_cmb113FocusLost

    private void txtF105KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF105KeyTyped
        // TODO add your handling code here:
        
        if(txtF105.getText().length() <=10){
                    if(!(Character.isDigit(evt.getKeyChar())))
                          evt.consume();      
        }
            else
                evt.consume();
          
    }//GEN-LAST:event_txtF105KeyTyped

    private void txtF100KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF100KeyTyped
        // TODO add your handling code here:
        
               
        
        
    }//GEN-LAST:event_txtF100KeyTyped

    private void jTabbedPane1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane1StateChanged
        // TODO add your handling code here:
   /*  ManageVehicles mv1 = new ManageVehicles();
        SetPanel pn= new SetPanel();
        pn.SetPanel(mv1);
     */   
       
    }//GEN-LAST:event_jTabbedPane1StateChanged

    private void jPanel1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jPanel1PropertyChange
        // TODO add your handling code here:
        
         System.out.println("State Changed");
    }//GEN-LAST:event_jPanel1PropertyChange

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        txtF100.setText("CAI-0101");
        txtF101.setText("Renault");
        txtF103.setText("D10");
        txtF104.setText("White");
        txtF105.setText("9000");
        
      
       
        
        jtxtAr100.setText(" Imported from Japan !");
        cmb165.setSelectedIndex(1);
          jcmb100.setSelectedIndex(4);
        jcmb101.setSelectedIndex(1);
        jcmb102.setSelectedIndex(1);
                
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField123KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField123KeyReleased
        // TODO add your handling code here:
        String num=jTextField123.getText();
        SQL s1 = new SQL ();
        s1.SearchVehiclesAll(jTable178,num);
        
        count150.setText("Records : "+jTable178.getRowCount());
       
     
        
    }//GEN-LAST:event_jTextField123KeyReleased

    private void jTextField123ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField123ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField123ActionPerformed

    public void RemoveFromTable(int i, JTable t)
    {
    
    DefaultTableModel model = (DefaultTableModel) t.getModel();

    model.removeRow(i);
    
    
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb113;
    private javax.swing.JComboBox<String> cmb130;
    private javax.swing.JComboBox<String> cmb131;
    private javax.swing.JComboBox<String> cmb147;
    private javax.swing.JComboBox<String> cmb165;
    private javax.swing.JLabel count150;
    private javax.swing.JLabel err101;
    private javax.swing.JLabel err102;
    private javax.swing.JLabel err103;
    private javax.swing.JLabel err104;
    private javax.swing.JLabel err105;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton100;
    private javax.swing.JButton jButton120;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private com.toedter.calendar.JDateChooser jDateChooser105;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel110;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel132;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JLayeredPane jLayeredPane5;
    private javax.swing.JLayeredPane jLayeredPane6;
    private javax.swing.JLayeredPane jLayeredPane7;
    private javax.swing.JLayeredPane jLayeredPane8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable102;
    private javax.swing.JTable jTable178;
    private javax.swing.JTextField jTextField123;
    private javax.swing.JButton jbtn104;
    private javax.swing.JComboBox<String> jcmb100;
    private javax.swing.JComboBox<String> jcmb101;
    private javax.swing.JComboBox<String> jcmb102;
    private javax.swing.JLabel jlbl_hidden_111;
    private javax.swing.JTextArea jtxtAr100;
    private javax.swing.JLabel lbl130;
    private javax.swing.JTextArea txtArea136;
    private javax.swing.JTextField txtF100;
    private javax.swing.JTextField txtF101;
    private javax.swing.JTextField txtF103;
    private javax.swing.JTextField txtF104;
    private javax.swing.JTextField txtF105;
    // End of variables declaration//GEN-END:variables
}
