package CustomerOrderManagement;

import CustomerOrderSupportedClasses.SetPanel;
import RootElement.DbConnect;
import RootElement.SessionHandler;
import java.awt.Container;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import javax.swing.UnsupportedLookAndFeelException;
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.swing.JRViewer;
import org.netbeans.lib.awtextra.AbsoluteLayout;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author ashanginige
 */
public class CustomerOrderManagementMain extends javax.swing.JFrame {

    /**
     * Creates new form main_menu
     */
    public CustomerOrderManagementMain() {
        initComponents();
        if(SessionHandler.getInsta()==null){
            jButton2.setVisible(false);
        }
        lbl_logged_user.setText(SessionHandler.getOccupation());
        this.setLocationRelativeTo(null);
        
    }
    
 

    CustomerOrderManagementMain(String filename, Map param) {
      
    // super("view report");
       try {
            DbConnect dbc=new DbConnect();
            dbc.setConnection();
           
            JasperPrint print=JasperFillManager.fillReport(filename,param, dbc.con);
            JRViewer viewer=new JRViewer(print);
            
            Container c=getContentPane();
            c.add(viewer);
            
           
       } catch (Exception e) {
           e.printStackTrace();
       }
       
       
       setBounds(10,10,1000,500);
       setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_sub_function_name = new javax.swing.JLabel();
        lbl_logged_user = new javax.swing.JLabel();
        btn_logout = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn502 = new javax.swing.JButton();
        btn500 = new javax.swing.JButton();
        btn501 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1024, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1024, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(790, 590));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 580));

        lbl_sub_function_name.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_sub_function_name.setForeground(new java.awt.Color(162, 167, 174));
        getContentPane().add(lbl_sub_function_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        lbl_logged_user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_logged_user.setForeground(new java.awt.Color(162, 167, 174));
        lbl_logged_user.setText("Customer Order Manager");
        getContentPane().add(lbl_logged_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, -1, -1));

        btn_logout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/logout_default.png"))); // NOI18N
        btn_logout.setBorderPainted(false);
        btn_logout.setContentAreaFilled(false);
        btn_logout.setFocusPainted(false);
        btn_logout.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/logout_hover.png"))); // NOI18N
        btn_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_logoutActionPerformed(evt);
            }
        });
        getContentPane().add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 40, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/home_default.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/home_hover.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 640, 100, 30));

        btn502.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/reports_default.png"))); // NOI18N
        btn502.setBorderPainted(false);
        btn502.setContentAreaFilled(false);
        btn502.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn502.setFocusPainted(false);
        btn502.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/reports_rollOver.png"))); // NOI18N
        btn502.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn502ActionPerformed(evt);
            }
        });
        getContentPane().add(btn502, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, 30));

        btn500.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/customerManagement_default.png"))); // NOI18N
        btn500.setBorderPainted(false);
        btn500.setContentAreaFilled(false);
        btn500.setFocusPainted(false);
        btn500.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/customerManagement_rollOver.png"))); // NOI18N
        btn500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn500ActionPerformed(evt);
            }
        });
        getContentPane().add(btn500, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, 30));

        btn501.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/orderManagement_default.png"))); // NOI18N
        btn501.setBorderPainted(false);
        btn501.setContentAreaFilled(false);
        btn501.setFocusPainted(false);
        btn501.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/orderManagement_rollOver.png"))); // NOI18N
        btn501.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn501ActionPerformed(evt);
            }
        });
        getContentPane().add(btn501, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/invoiceGeneration_default.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/invoiceGeneration_rollOver.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 170, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/CustomerOrderImages/CustomerOrderManagement.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn500ActionPerformed
        lbl_sub_function_name.setText("Customer Management");
        
        CustomerManagement c= new CustomerManagement();
        
        SetPanel p1=new SetPanel();
        p1.SetPanel(c, jPanel2);

    }//GEN-LAST:event_btn500ActionPerformed

    private void btn502ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn502ActionPerformed
       lbl_sub_function_name.setText("Reports");
        
        Reports r=new Reports();
        
        SetPanel p3=new SetPanel();
        p3.SetPanel(r, jPanel2);
        
    }//GEN-LAST:event_btn502ActionPerformed

    private void btn501ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn501ActionPerformed
       lbl_sub_function_name.setText("Order Management");
       
       OrderManagement o=new OrderManagement();
       
       SetPanel p2=new SetPanel();
       p2.SetPanel(o, jPanel2);
    }//GEN-LAST:event_btn501ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         lbl_sub_function_name.setText("Invoice Generation");
        
        InvoiceGeneration r=new InvoiceGeneration();
        
        SetPanel p3=new SetPanel();
        p3.SetPanel(r, jPanel2);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        SessionHandler.getInsta().getRootPane().getGlassPane().setVisible(false);
        SessionHandler.getInsta().setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_logoutActionPerformed
        int option=JOptionPane.showConfirmDialog(this,"Do you want to logout ?");
      if(option==JOptionPane.YES_OPTION){
          this.dispose();
          SessionHandler.Dispose();
      }
      else{
            
        }
    }//GEN-LAST:event_btn_logoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(CustomerOrderManagementMain.class.getName()).log(Level.SEVERE, null, ex);
                }
                new CustomerOrderManagementMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn500;
    private javax.swing.JButton btn501;
    private javax.swing.JButton btn502;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_logged_user;
    private javax.swing.JLabel lbl_sub_function_name;
    // End of variables declaration//GEN-END:variables
}
