/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WarehouseManagement;

import WarehouseManagement.Reports.GenerateReport;
import WarehouseManagement.SupportedClasses.Chart;
import WarehouseManagement.SupportedClasses.SetPanel;
import java.io.File;
import java.io.FileFilter;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.jfree.chart.JFreeChart;

/**
 *
 * @author Ishan
 */
public class GenerateReports extends javax.swing.JPanel {
    JFreeChart chrt;
    /**
     * Creates new form GenerateReports
     */
    public GenerateReports() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        date290From = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        date290To = new com.toedter.calendar.JDateChooser();
        btn291Graph = new javax.swing.JButton();
        btn291Report = new javax.swing.JButton();
        btn294Save = new javax.swing.JButton();
        jpnl292Graph = new javax.swing.JPanel();
        jpnl293Graph = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        date290From1 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        date290To1 = new com.toedter.calendar.JDateChooser();
        btn291Graph1 = new javax.swing.JButton();
        btn291Report1 = new javax.swing.JButton();
        btn294Save1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmb295OType = new javax.swing.JComboBox<>();
        jpnl292Graph1 = new javax.swing.JPanel();
        jpnl293Graph1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Period"));

        jLabel1.setText("From");

        jLabel2.setText("To");

        btn291Graph.setText("Generate Graph");
        btn291Graph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn291GraphActionPerformed(evt);
            }
        });

        btn291Report.setText("Generate Report");
        btn291Report.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn291ReportActionPerformed(evt);
            }
        });

        btn294Save.setText("Save Graph");
        btn294Save.setEnabled(false);
        btn294Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn294SaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date290From, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                    .addComponent(date290To, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn291Graph)
                .addGap(18, 18, 18)
                .addComponent(btn294Save)
                .addGap(18, 18, 18)
                .addComponent(btn291Report)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date290From, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(date290To, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn291Graph)
                    .addComponent(btn291Report)
                    .addComponent(btn294Save))
                .addContainerGap())
        );

        jpnl292Graph.setBackground(new java.awt.Color(255, 255, 255));
        jpnl292Graph.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated Graph"));

        jpnl293Graph.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnl293GraphLayout = new javax.swing.GroupLayout(jpnl293Graph);
        jpnl293Graph.setLayout(jpnl293GraphLayout);
        jpnl293GraphLayout.setHorizontalGroup(
            jpnl293GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        jpnl293GraphLayout.setVerticalGroup(
            jpnl293GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnl292GraphLayout = new javax.swing.GroupLayout(jpnl292Graph);
        jpnl292Graph.setLayout(jpnl292GraphLayout);
        jpnl292GraphLayout.setHorizontalGroup(
            jpnl292GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl292GraphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl293Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnl292GraphLayout.setVerticalGroup(
            jpnl292GraphLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl292GraphLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl293Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jpnl292Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnl292Graph, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Issued Raw Materials", jPanel1);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Set Period"));

        jLabel3.setText("From");

        jLabel4.setText("To");

        btn291Graph1.setText("Generate Graph");
        btn291Graph1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn291Graph1ActionPerformed(evt);
            }
        });

        btn291Report1.setText("Generate Report");
        btn291Report1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn291Report1ActionPerformed(evt);
            }
        });

        btn294Save1.setText("Save Graph");
        btn294Save1.setEnabled(false);
        btn294Save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn294Save1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Order Type");

        cmb295OType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Large Scale Order", "Small Scale Order" }));
        cmb295OType.setSelectedIndex(-1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(btn291Graph1)
                        .addGap(18, 18, 18)
                        .addComponent(btn294Save1)
                        .addGap(18, 18, 18)
                        .addComponent(btn291Report1))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(date290From1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(date290To1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                            .addComponent(cmb295OType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(date290From1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(date290To1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb295OType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn291Graph1)
                    .addComponent(btn291Report1)
                    .addComponent(btn294Save1))
                .addContainerGap())
        );

        jpnl292Graph1.setBackground(new java.awt.Color(255, 255, 255));
        jpnl292Graph1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generated Graph"));

        jpnl293Graph1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jpnl293Graph1Layout = new javax.swing.GroupLayout(jpnl293Graph1);
        jpnl293Graph1.setLayout(jpnl293Graph1Layout);
        jpnl293Graph1Layout.setHorizontalGroup(
            jpnl293Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 701, Short.MAX_VALUE)
        );
        jpnl293Graph1Layout.setVerticalGroup(
            jpnl293Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 251, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnl292Graph1Layout = new javax.swing.GroupLayout(jpnl292Graph1);
        jpnl292Graph1.setLayout(jpnl292Graph1Layout);
        jpnl292Graph1Layout.setHorizontalGroup(
            jpnl292Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl292Graph1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl293Graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnl292Graph1Layout.setVerticalGroup(
            jpnl292Graph1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl292Graph1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnl293Graph1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnl292Graph1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jpnl292Graph1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Issued Finished Products", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn291GraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn291GraphActionPerformed
       if(date290From.getDate()!=null && date290To.getDate()!=null){
           jpnl293Graph.removeAll();
           jpnl293Graph.repaint();
           jpnl293Graph.revalidate();
           btn294Save.setEnabled(true);
           DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
           String from = dateFormat.format(date290From.getDate());
           String to = dateFormat.format(date290To.getDate());
           String query = "select itemName, sum(quantity) as quantity from viewissuedmaterials where requestDate between '"+from+"' AND '"+to+"' group by rawMaterialId";
           JPanel pnl;

           Chart inputMaterials = new Chart();

           inputMaterials.createPieDataset(query,"itemName","quantity");
           pnl = inputMaterials.createPanel(chrt=inputMaterials.createPieChart("Issued Raw Materials from "+from+" to "+to),700,270);

           SetPanel sp = new SetPanel();
           sp.SetPanel(jpnl293Graph, pnl);
       }
       else{
           JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
       }
       
       
    }//GEN-LAST:event_btn291GraphActionPerformed

    private void btn294SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn294SaveActionPerformed
        try {
            FileNameExtensionFilter ff = new FileNameExtensionFilter(".jpeg files","jpeg");
            JFileChooser jfc = new JFileChooser();

            jfc.setFileFilter(ff);
            jfc.showSaveDialog(this);
            File chartFile = jfc.getSelectedFile();
            String path = chartFile.getAbsolutePath();
            path = path+".jpeg";
            chartFile = new File(path);
            Chart saveChart = new Chart();
            saveChart.SaveChart(chartFile, chrt);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn294SaveActionPerformed

    private void btn291ReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn291ReportActionPerformed
        if(date290From.getDate()!=null && date290To.getDate()!=null){
            Map<String,Object> param = new HashMap();
            param.put("from",date290From.getDate());
            param.put("to",date290To.getDate());
            GenerateReport rawMaterial = new GenerateReport("src\\WarehouseManagement\\Reports\\IssuedRawMaterials.jasper",param);
            rawMaterial.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn291ReportActionPerformed

    private void btn291Graph1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn291Graph1ActionPerformed
        if(date290From1.getDate()!=null && date290To1.getDate()!=null && cmb295OType.getSelectedIndex()!=-1){
            jpnl293Graph1.removeAll();
            jpnl293Graph1.repaint();
            jpnl293Graph1.revalidate();

            DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String from = dateFormat.format(date290From1.getDate());
            String to = dateFormat.format(date290To1.getDate());
            JPanel pnl;
            String query="";
            
            if(cmb295OType.getSelectedIndex()==0)
                query = "select productId,name, quantity from viewlargeissuedproducts where invoiceDate between '"+from+"' AND '"+to+"' group by productId";
            else if(cmb295OType.getSelectedIndex()==1)
                query = "select productId,name, quantity from viewsmallissuedproducts where invoiceDate between '"+from+"' AND '"+to+"' group by productId";
            
            Chart inputMaterials = new Chart();
            inputMaterials.createPieDataset(query,"name","quantity");
            pnl = inputMaterials.createPanel(chrt=inputMaterials.createPieChart("Issued Finished Products from "+from+" to "+to),700,250);
            SetPanel sp = new SetPanel();
            sp.SetPanel(jpnl293Graph1, pnl);
            btn294Save1.setEnabled(true);
        }
        else
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btn291Graph1ActionPerformed

    private void btn291Report1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn291Report1ActionPerformed
       if(date290From1.getDate()!=null && date290To1.getDate()!=null && cmb295OType.getSelectedIndex()!=-1){
            Map<String,Object> param = new HashMap();
            param.put("from",date290From1.getDate());
            param.put("to",date290To1.getDate());
            
            if(cmb295OType.getSelectedIndex()==0){
                GenerateReport fp = new GenerateReport("src\\WarehouseManagement\\Reports\\IssuedFinishedProducts.jasper",param);
                fp.setVisible(true);
            }
            else if(cmb295OType.getSelectedIndex()==1){
                GenerateReport fp = new GenerateReport("src\\WarehouseManagement\\Reports\\IssuedFinishedProducts_1.jasper",param);
                fp.setVisible(true);
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btn291Report1ActionPerformed

    private void btn294Save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn294Save1ActionPerformed
       try {
            FileNameExtensionFilter ff = new FileNameExtensionFilter(".jpeg files","jpeg");
            JFileChooser jfc = new JFileChooser();

            jfc.setFileFilter(ff);
            jfc.showSaveDialog(this);
            File chartFile = jfc.getSelectedFile();
            String path = chartFile.getAbsolutePath();
            path = path+".jpeg";
            chartFile = new File(path);
            Chart saveChart = new Chart();
            saveChart.SaveChart(chartFile, chrt);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn294Save1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn291Graph;
    private javax.swing.JButton btn291Graph1;
    private javax.swing.JButton btn291Report;
    private javax.swing.JButton btn291Report1;
    private javax.swing.JButton btn294Save;
    private javax.swing.JButton btn294Save1;
    private javax.swing.JComboBox<String> cmb295OType;
    private com.toedter.calendar.JDateChooser date290From;
    private com.toedter.calendar.JDateChooser date290From1;
    private com.toedter.calendar.JDateChooser date290To;
    private com.toedter.calendar.JDateChooser date290To1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpnl292Graph;
    private javax.swing.JPanel jpnl292Graph1;
    private javax.swing.JPanel jpnl293Graph;
    private javax.swing.JPanel jpnl293Graph1;
    // End of variables declaration//GEN-END:variables
}
