/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WarehouseManagement;

import WarehouseManagement.SupportedClasses.ComboKeyHandler;
import WarehouseManagement.Reports.GenerateReport;
import WarehouseManagement.SupportedClasses.SetPanel;
import WarehouseManagement.SupportedClasses.WarehouseDBAccess;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ishan
 */
public class IssueGRN extends javax.swing.JPanel {
    WarehouseDBAccess wdba = new WarehouseDBAccess();
    ComboKeyHandler ck;
    /**
     * Creates new form IssueGRN
     */
    public IssueGRN() {
        initComponents();
        menu281Remove.setText("Remove Record");
        tbl286Products.setComponentPopupMenu(pop281Remove);
        wdba.FillCombo(cmb288RMName,"itemName","rawMaterial");
        wdba.FillCombo(cmb289RID,"requestId","getcompletedrequests");
        ck = new ComboKeyHandler(cmb288RMName);
        cmb288RMName.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
           public void keyTyped(KeyEvent e){
               ck.keyTyped(e);
           } 
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop281Remove = new javax.swing.JPopupMenu();
        menu281Remove = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl286Products = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn286Add = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        date283Receive = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtF286PId = new javax.swing.JTextField();
        spnnr285Qty = new javax.swing.JSpinner();
        btn287Update = new javax.swing.JButton();
        cmb288RMName = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmb289RID = new javax.swing.JComboBox<>();

        menu281Remove.setText("jMenuItem1");
        menu281Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menu281RemoveActionPerformed(evt);
            }
        });
        pop281Remove.add(menu281Remove);

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbl286Products.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request ID", "Received Date", "Raw Material ID", "Raw Material Name", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl286Products);

        jLabel1.setText("Raw Material ID");

        jLabel2.setText("Quantity");

        btn286Add.setText("Add");
        btn286Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn286AddActionPerformed(evt);
            }
        });

        jLabel3.setText("Received Date");

        jButton2.setText("Generate GRN");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Raw Material Name");

        txtF286PId.setEditable(false);

        spnnr285Qty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btn287Update.setText("Update Inventory");
        btn287Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn287UpdateActionPerformed(evt);
            }
        });

        cmb288RMName.setEditable(true);
        cmb288RMName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb288RMNamePropertyChange(evt);
            }
        });

        jLabel5.setText("Request ID");

        cmb289RID.setEditable(true);
        cmb289RID.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb289RIDPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 742, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn287Update, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtF286PId, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(spnnr285Qty, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(81, 81, 81)
                                    .addComponent(date283Receive, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btn286Add, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmb288RMName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cmb289RID, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(42, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(date283Receive, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb289RID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmb288RMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtF286PId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnnr285Qty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(btn286Add)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(btn287Update))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn286AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn286AddActionPerformed
        String datex=null;
        String currdate = null;
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        try {
            
            datex = dateFormat.format(date283Receive.getDate());
            Date currentDate = new Date();
            currdate = dateFormat.format(currentDate);
            
        } catch (Exception e) {
        }
        
        if(datex==null || txtF286PId.getText().equals("") || cmb288RMName.getSelectedIndex()==-1 || Integer.parseInt(String.valueOf(spnnr285Qty.getValue()))==0 ){
            try {
                if(dateFormat.parse(currdate).before(dateFormat.parse(datex))){
                   JOptionPane.showMessageDialog(this,"Choose a valid date","Warning ",JOptionPane.WARNING_MESSAGE);
                }
            } catch (Exception e) {
            }
             JOptionPane.showMessageDialog(this,"One or more fields contain invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }
        else{
            Object in[] = {cmb289RID.getSelectedItem(),datex,txtF286PId.getText(),cmb288RMName.getSelectedItem(),spnnr285Qty.getValue()};
            DefaultTableModel model = (DefaultTableModel) tbl286Products.getModel();
            model.addRow(in);
            date283Receive.setDate(null);
            txtF286PId.setText("");
            cmb288RMName.setSelectedIndex(-1);
            spnnr285Qty.setValue(0);
            cmb289RID.setSelectedIndex(-1);
        }
        
        

    }//GEN-LAST:event_btn286AddActionPerformed

    private void menu281RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menu281RemoveActionPerformed
        try {
            DefaultTableModel model = (DefaultTableModel) tbl286Products.getModel();
            model.removeRow(tbl286Products.getSelectedRow());
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_menu281RemoveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      if(tbl286Products.getRowCount()>0){
            HashMap<String,Object> param = new HashMap<String,Object>();
            param.put("receivedDate", String.valueOf(tbl286Products.getValueAt(0,0)));
            Map<String,Object> param2 = new HashMap<String, Object>(param);
            GenerateReport grn = new GenerateReport("src\\WarehouseManagement\\Reports\\GRN.jasper",param2);
            grn.setVisible(true);
            IssueGRN obj1 = new IssueGRN();
            SetPanel sp = new SetPanel();
            sp.SetPanel(obj1);
      }
      else{
            GRNDate grn = new GRNDate(new WarehouseMain(), true);
            grn.setVisible(true);
      }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn287UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn287UpdateActionPerformed
        if(tbl286Products.getRowCount()>0){
            int option = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(option==JOptionPane.YES_OPTION){
                wdba.IssueGRN(tbl286Products);
                IssueGRN is = new IssueGRN();
                SetPanel sp = new SetPanel();
                sp.SetPanel(is);
            }
            
      }
      else{
          JOptionPane.showMessageDialog(this,"Load data before updating","Warning ",JOptionPane.WARNING_MESSAGE);
      }
    }//GEN-LAST:event_btn287UpdateActionPerformed

    private void cmb288RMNamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb288RMNamePropertyChange
        if(cmb288RMName.getSelectedIndex()!=0)
        {
            txtF286PId.setText("");
        }
        String query = "SELECT rawMaterialId FROM rawMaterial WHERE itemName='"+String.valueOf(cmb288RMName.getSelectedItem()+"'");
        txtF286PId.setText(wdba.ReturnValue(query, "rawMaterialId"));
    }//GEN-LAST:event_cmb288RMNamePropertyChange

    private void cmb289RIDPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb289RIDPropertyChange
        if(cmb289RID.getSelectedIndex()!=-1){
            String itemName = wdba.ReturnValue("SELECT itemName FROM getCompletedRequests WHERE requestId='"+String.valueOf(cmb289RID.getSelectedItem())+"'","itemName");
            cmb288RMName.setSelectedItem(itemName);
        }
    }//GEN-LAST:event_cmb289RIDPropertyChange


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn286Add;
    private javax.swing.JButton btn287Update;
    private javax.swing.JComboBox<String> cmb288RMName;
    private javax.swing.JComboBox<String> cmb289RID;
    private com.toedter.calendar.JDateChooser date283Receive;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem menu281Remove;
    private javax.swing.JPopupMenu pop281Remove;
    private javax.swing.JSpinner spnnr285Qty;
    private javax.swing.JTable tbl286Products;
    private javax.swing.JTextField txtF286PId;
    // End of variables declaration//GEN-END:variables
}
