/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WarehouseManagement;

import WarehouseManagement.SupportedClasses.ComboKeyHandler;
import RootElement.DbConnect;
import WarehouseManagement.SupportedClasses.SetLable;
import WarehouseManagement.SupportedClasses.SetPanel;
import WarehouseManagement.SupportedClasses.WarehouseDBAccess;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Ishan
 */
public class ManageRawMaterials extends javax.swing.JPanel {
    SetLable stLbl = new SetLable();
    WarehouseDBAccess wdba = new WarehouseDBAccess();
    ComboKeyHandler ck;
    /**
     * Creates new form ManageRawMaterials
     */
    public ManageRawMaterials() {
        initComponents();
        
        txtF230IID.setText(wdba.GetIncrementedId("rawMaterialId","rawMaterial",2));
       
        wdba.FillCombo(cmb231IName,"itemName","rawMaterial");
        ck = new ComboKeyHandler(cmb231IName);
        
        wdba.ViewAll(tbl201RawMaterials,"rawMaterial");
        SetTableHeaders();
        jLabel9.setVisible(false);
        spnnr233IQty1.setVisible(false);
        updateItem.setText("Update Item");
        tbl201RawMaterials.setComponentPopupMenu(pop234Update);
        
        
        cmb231IName.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                ck.keyTyped(e);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop234Update = new javax.swing.JPopupMenu();
        updateItem = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        spnnr234IReorder = new javax.swing.JSpinner();
        spnnr233IQty = new javax.swing.JSpinner();
        txtF232IWei = new javax.swing.JTextField();
        txtF231IName = new javax.swing.JTextField();
        txtF230IID = new javax.swing.JTextField();
        btn235Add = new javax.swing.JButton();
        lbl231IName = new javax.swing.JLabel();
        lbl232IWei = new javax.swing.JLabel();
        lbl233IQty = new javax.swing.JLabel();
        lbl234IReorder = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl201RawMaterials = new javax.swing.JTable();
        txtF240Search = new javax.swing.JTextField();
        btn240Search = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        spnnr234IReorder1 = new javax.swing.JSpinner();
        spnnr233IQty1 = new javax.swing.JSpinner();
        txtF232IWei1 = new javax.swing.JTextField();
        txtF230IID1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lbl231IName1 = new javax.swing.JLabel();
        lbl232IWei1 = new javax.swing.JLabel();
        lbl233IQty1 = new javax.swing.JLabel();
        lbl234IReorder1 = new javax.swing.JLabel();
        btn235Update = new javax.swing.JButton();
        cmb231IName = new javax.swing.JComboBox<>();

        updateItem.setText("jMenuItem1");
        updateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemActionPerformed(evt);
            }
        });
        pop234Update.add(updateItem);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Item ID");

        jLabel2.setText("Item Name");

        jLabel3.setText("Unit Weight");

        jLabel4.setText("Quantity");

        jLabel5.setText("Reorder Point");

        spnnr234IReorder.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnnr234IReorder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnnr234IReorderStateChanged(evt);
            }
        });
        spnnr234IReorder.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnnr234IReorderFocusLost(evt);
            }
        });
        spnnr234IReorder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                spnnr234IReorderKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spnnr234IReorderKeyTyped(evt);
            }
        });

        spnnr233IQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnnr233IQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnnr233IQtyFocusLost(evt);
            }
        });

        txtF232IWei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF232IWeiFocusLost(evt);
            }
        });
        txtF232IWei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF232IWeiKeyTyped(evt);
            }
        });

        txtF231IName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF231INameFocusLost(evt);
            }
        });

        txtF230IID.setEnabled(false);

        btn235Add.setText("Add");
        btn235Add.setFocusPainted(false);
        btn235Add.setPreferredSize(new java.awt.Dimension(90, 24));
        btn235Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn235AddActionPerformed(evt);
            }
        });

        lbl231IName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl231IName.setForeground(new java.awt.Color(255, 0, 0));

        lbl232IWei.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl232IWei.setForeground(new java.awt.Color(255, 0, 0));

        lbl233IQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl233IQty.setForeground(new java.awt.Color(255, 0, 0));

        lbl234IReorder.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl234IReorder.setForeground(new java.awt.Color(255, 0, 0));

        jButton2.setText("Demo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn235Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(33, 33, 33)
                                    .addComponent(txtF231IName, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(30, 30, 30)
                                    .addComponent(txtF232IWei, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(49, 49, 49)
                                    .addComponent(spnnr233IQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(spnnr234IReorder, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl231IName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl232IWei, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl233IQty, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl234IReorder, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                        .addGap(301, 301, 301))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addComponent(txtF230IID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF230IID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF231IName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl231IName)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF232IWei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl232IWei)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnnr233IQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl233IQty)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnnr234IReorder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl234IReorder)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 219, Short.MAX_VALUE)
                .addComponent(btn235Add, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        jTabbedPane1.addTab("Add New Raw Materials", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl201RawMaterials.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item ID", "Item Name", "Unit Weight", "Quantity", "Reorder Point"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl201RawMaterials);

        txtF240Search.setText("Enter raw material ID or raw material name");
        txtF240Search.setPreferredSize(new java.awt.Dimension(198, 35));
        txtF240Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF240SearchFocusGained(evt);
            }
        });

        btn240Search.setText("Search");
        btn240Search.setPreferredSize(new java.awt.Dimension(73, 24));
        btn240Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn240SearchActionPerformed(evt);
            }
        });

        jButton3.setText("Remove Selected Item");
        jButton3.setPreferredSize(new java.awt.Dimension(151, 24));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("View All");
        jButton1.setPreferredSize(new java.awt.Dimension(73, 24));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 761, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(txtF240Search, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btn240Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF240Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn240Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        jTabbedPane1.addTab("View Inventory", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jPanel3FocusGained(evt);
            }
        });

        spnnr234IReorder1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnnr234IReorder1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnnr234IReorder1StateChanged(evt);
            }
        });
        spnnr234IReorder1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnnr234IReorder1FocusLost(evt);
            }
        });

        spnnr233IQty1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        txtF232IWei1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF232IWei1FocusLost(evt);
            }
        });
        txtF232IWei1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF232IWei1KeyTyped(evt);
            }
        });

        txtF230IID1.setEnabled(false);

        jLabel6.setText("Item ID");

        jLabel7.setText("Item Name");

        jLabel8.setText("Unit Weight");

        jLabel9.setText("Quantity");

        jLabel10.setText("Reorder Point");

        lbl231IName1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl231IName1.setForeground(new java.awt.Color(255, 0, 0));

        lbl232IWei1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl232IWei1.setForeground(new java.awt.Color(255, 0, 0));

        lbl233IQty1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl233IQty1.setForeground(new java.awt.Color(255, 0, 0));

        lbl234IReorder1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl234IReorder1.setForeground(new java.awt.Color(255, 0, 0));

        btn235Update.setText("Update");
        btn235Update.setPreferredSize(new java.awt.Dimension(90, 24));
        btn235Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn235UpdateActionPerformed(evt);
            }
        });

        cmb231IName.setEditable(true);
        cmb231IName.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb231INameItemStateChanged(evt);
            }
        });
        cmb231IName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb231INameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb231INameFocusLost(evt);
            }
        });
        cmb231IName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                cmb231INameMouseReleased(evt);
            }
        });
        cmb231IName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb231INameActionPerformed(evt);
            }
        });
        cmb231IName.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb231INamePropertyChange(evt);
            }
        });
        cmb231IName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cmb231INameKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cmb231INameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel6)
                .addGap(54, 54, 54)
                .addComponent(txtF230IID1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(367, 367, 367)
                .addComponent(btn235Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(spnnr234IReorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF232IWei1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(cmb231IName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)))))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl231IName1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl232IWei1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl234IReorder1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(49, 49, 49)
                .addComponent(spnnr233IQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216)
                .addComponent(lbl233IQty1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtF230IID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb231IName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl231IName1))
                .addGap(30, 30, 30)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF232IWei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl232IWei1)))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnnr234IReorder1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl234IReorder1)))
                .addGap(73, 73, 73)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel9))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spnnr233IQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl233IQty1)))
                .addGap(181, 181, 181)
                .addComponent(btn235Update, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Update Details", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtF240SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF240SearchFocusGained
        txtF240Search.setText("");
    }//GEN-LAST:event_txtF240SearchFocusGained

    private void txtF231INameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF231INameFocusLost
        stLbl.CheckTextField(txtF231IName,lbl231IName,"text");
    }//GEN-LAST:event_txtF231INameFocusLost

    private void txtF232IWeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF232IWeiFocusLost
        stLbl.CheckTextField(txtF232IWei,lbl232IWei,"number");
    }//GEN-LAST:event_txtF232IWeiFocusLost

    private void spnnr233IQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnnr233IQtyFocusLost
        //stLbl.CheckSpinner(spnnr233IQty,lbl233IQty);
    }//GEN-LAST:event_spnnr233IQtyFocusLost

    private void spnnr234IReorderFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnnr234IReorderFocusLost
        stLbl.CheckSpinner(spnnr234IReorder,lbl234IReorder);
    }//GEN-LAST:event_spnnr234IReorderFocusLost

    private void btn235AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn235AddActionPerformed
        txtF231IName.requestFocus();
        txtF232IWei.requestFocus();
        stLbl.CheckSpinner(spnnr234IReorder,lbl234IReorder);
        btn235Add.requestFocus();
        
        if(((!lbl231IName.getText().isEmpty() || !lbl232IWei.getText().isEmpty()) || !lbl233IQty.getText().isEmpty()) || !lbl234IReorder.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            
            int option =  JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(option==JOptionPane.YES_OPTION){
                wdba.AddRawMaterial(txtF230IID, txtF231IName, txtF232IWei, spnnr233IQty, spnnr234IReorder);
                JOptionPane.showMessageDialog(this,"Raw Material Added Successfully");
                ManageRawMaterials mr = new ManageRawMaterials();

                SetPanel sp = new SetPanel();
                sp.SetPanel(mr);
            }
            
            
                    
        }
    }//GEN-LAST:event_btn235AddActionPerformed

    private void cmb231INameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb231INameFocusLost
        stLbl.CheckComboBox(cmb231IName,lbl231IName1);
    }//GEN-LAST:event_cmb231INameFocusLost

    private void txtF232IWei1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF232IWei1FocusLost
        stLbl.CheckTextField(txtF232IWei1,lbl232IWei1);
    }//GEN-LAST:event_txtF232IWei1FocusLost

    private void spnnr234IReorder1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnnr234IReorder1FocusLost
       stLbl.CheckSpinner(spnnr234IReorder1,lbl234IReorder1);
    }//GEN-LAST:event_spnnr234IReorder1FocusLost

    private void btn235UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn235UpdateActionPerformed
        cmb231IName.requestFocus();
        txtF232IWei1.requestFocus();
        spnnr234IReorder1.requestFocus();
        btn235Update.requestFocus();
        
        if(((!lbl231IName1.getText().isEmpty() || !lbl232IWei1.getText().isEmpty()) || !lbl233IQty1.getText().isEmpty()) || !lbl234IReorder1.getText().isEmpty() || cmb231IName.getSelectedIndex()==-1) {
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            
            int option = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(option==JOptionPane.YES_OPTION){
                wdba.UpdateRawMaterial(txtF230IID1,String.valueOf(cmb231IName.getSelectedItem()), txtF232IWei1, spnnr233IQty1, spnnr234IReorder1);
                JOptionPane.showMessageDialog(this,"Raw Material Updated Successfully");
                ManageRawMaterials mr = new ManageRawMaterials();

                SetPanel sp = new SetPanel();
                sp.SetPanel(mr);
            }
            
                    
        }
    }//GEN-LAST:event_btn235UpdateActionPerformed

    private void txtF232IWeiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF232IWeiKeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtF232IWeiKeyTyped

    private void spnnr234IReorderKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnnr234IReorderKeyReleased
        stLbl.CheckSpinner(spnnr234IReorder,lbl234IReorder);
    }//GEN-LAST:event_spnnr234IReorderKeyReleased

    private void spnnr234IReorderKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spnnr234IReorderKeyTyped
        stLbl.CheckSpinner(spnnr234IReorder,lbl234IReorder);
    }//GEN-LAST:event_spnnr234IReorderKeyTyped

    private void spnnr234IReorderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnnr234IReorderStateChanged
        stLbl.CheckSpinner(spnnr234IReorder,lbl234IReorder);
    }//GEN-LAST:event_spnnr234IReorderStateChanged

    private void cmb231INameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb231INameActionPerformed
        txtF232IWei1.requestFocus();
        btn235Update.requestFocus();
        
    }//GEN-LAST:event_cmb231INameActionPerformed

    private void jPanel3FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jPanel3FocusGained
         
    }//GEN-LAST:event_jPanel3FocusGained

    private void cmb231INameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb231INameFocusGained
         
    }//GEN-LAST:event_cmb231INameFocusGained

    private void cmb231INamePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb231INamePropertyChange
        if(cmb231IName.getSelectedIndex() != 0)
        {
            txtF230IID1.setText("");
            txtF232IWei1.setText("");
            spnnr234IReorder1.setValue(0);
        }
           wdba.RetrieveRawMaterial(cmb231IName, String.valueOf(cmb231IName.getSelectedItem()),txtF230IID1, txtF232IWei1, spnnr233IQty1, spnnr234IReorder1);
        
    }//GEN-LAST:event_cmb231INamePropertyChange

    private void spnnr234IReorder1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnnr234IReorder1StateChanged
         stLbl.CheckSpinner(spnnr234IReorder1,lbl234IReorder1);
    }//GEN-LAST:event_spnnr234IReorder1StateChanged

    private void txtF232IWei1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF232IWei1KeyTyped
        if(!Character.isDigit(evt.getKeyChar()))
            evt.consume();
    }//GEN-LAST:event_txtF232IWei1KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        wdba.ViewAll(tbl201RawMaterials,"rawMaterial");
        SetTableHeaders();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn240SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn240SearchActionPerformed
        wdba.SearchByKeyWord(tbl201RawMaterials,"rawMaterial",String.valueOf(txtF240Search.getText()),"rawMaterialId","itemName");
        SetTableHeaders();
    }//GEN-LAST:event_btn240SearchActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(tbl201RawMaterials.getRowCount()>0){
            int dialogResult = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(dialogResult==JOptionPane.YES_OPTION)
            {
                wdba.DeleteRow("rawMaterial","rawMaterialId" ,String.valueOf(tbl201RawMaterials.getValueAt(tbl201RawMaterials.getSelectedRow(),0)));
                wdba.ViewAll(tbl201RawMaterials,"rawMaterial");
                SetTableHeaders();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Select an item to delete","Warning ",JOptionPane.WARNING_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmb231INameMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmb231INameMouseReleased
        
        
    }//GEN-LAST:event_cmb231INameMouseReleased

    private void updateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemActionPerformed
        cmb231IName.setSelectedItem(tbl201RawMaterials.getValueAt(tbl201RawMaterials.getSelectedRow(), 1));
        jTabbedPane1.setSelectedIndex(2);
        
    }//GEN-LAST:event_updateItemActionPerformed

    private void cmb231INameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb231INameKeyTyped
    
    }//GEN-LAST:event_cmb231INameKeyTyped

    private void cmb231INameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cmb231INameKeyPressed

    }//GEN-LAST:event_cmb231INameKeyPressed

    private void cmb231INameItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb231INameItemStateChanged
       // if(cmb231IName.getSelectedIndex() !=-1)
        //    wdba.RetrieveRawMaterial(cmb231IName, String.valueOf(cmb231IName.getSelectedItem()),txtF230IID1, txtF232IWei1, spnnr233IQty1, spnnr234IReorder1);
    }//GEN-LAST:event_cmb231INameItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        txtF231IName.setText("Copper");
        txtF232IWei.setText("100");
        spnnr233IQty.setValue(20000);
        spnnr234IReorder.setValue(7000);
    }//GEN-LAST:event_jButton2ActionPerformed
    
    private void SetTableHeaders()
    {
        TableColumnModel tcm = tbl201RawMaterials.getColumnModel();
        tcm.getColumn(0).setHeaderValue("Raw Material ID");
        tcm.getColumn(1).setHeaderValue("Item Name");
        tcm.getColumn(2).setHeaderValue("Quantity");
        tcm.getColumn(3).setHeaderValue("Unit Weight");
        tcm.getColumn(4).setHeaderValue("Reorder Point");
    }
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn235Add;
    private javax.swing.JButton btn235Update;
    private javax.swing.JButton btn240Search;
    private javax.swing.JComboBox<String> cmb231IName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl231IName;
    private javax.swing.JLabel lbl231IName1;
    private javax.swing.JLabel lbl232IWei;
    private javax.swing.JLabel lbl232IWei1;
    private javax.swing.JLabel lbl233IQty;
    private javax.swing.JLabel lbl233IQty1;
    private javax.swing.JLabel lbl234IReorder;
    private javax.swing.JLabel lbl234IReorder1;
    private javax.swing.JPopupMenu pop234Update;
    private javax.swing.JSpinner spnnr233IQty;
    private javax.swing.JSpinner spnnr233IQty1;
    private javax.swing.JSpinner spnnr234IReorder;
    private javax.swing.JSpinner spnnr234IReorder1;
    private javax.swing.JTable tbl201RawMaterials;
    private javax.swing.JTextField txtF230IID;
    private javax.swing.JTextField txtF230IID1;
    private javax.swing.JTextField txtF231IName;
    private javax.swing.JTextField txtF232IWei;
    private javax.swing.JTextField txtF232IWei1;
    private javax.swing.JTextField txtF240Search;
    private javax.swing.JMenuItem updateItem;
    // End of variables declaration//GEN-END:variables
}
