/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package WarehouseManagement;


import WarehouseManagement.SupportedClasses.ComboKeyHandler;
import WarehouseManagement.SupportedClasses.SetLable;
import WarehouseManagement.SupportedClasses.SetPanel;
import WarehouseManagement.SupportedClasses.TextValidator;
import WarehouseManagement.SupportedClasses.WarehouseDBAccess;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Ishan
 */
public class ManageFinalProducts extends javax.swing.JPanel {
    SetLable stLbl = new SetLable();
    WarehouseDBAccess wdba = new WarehouseDBAccess();
    ComboKeyHandler ck;

    /**
     * Creates new form ManageFinalProducts
     */
    public ManageFinalProducts() {
        initComponents();
        txtF210PID.setText(wdba.GetIncrementedId("productId","finishedProducts",3));
        wdba.FillCombo(cmb211Pname1,"name","finishedProducts");
        ck = new ComboKeyHandler(cmb211Pname1);
        jLabel45.setVisible(false);
        spnnr220PQty1.setVisible(false);
        wdba.ViewAll(tbl250FProducts, "finishedProducts");
        SetTableHeaders();
        updateItem.setText("Update Item");
        tbl250FProducts.setComponentPopupMenu(pop250Update);
        cmb211Pname1.getEditor().getEditorComponent().addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e){
                ck.keyTyped(e);
            }
        });
    }

     private int dotCount(JTextField jtf){
        int count=0;
        if("".equals(jtf.getText())){
            return 0;
        }
        else{
            
            for(int i=0; i<=jtf.getText().length()-1;i++){
            if(jtf.getText().charAt(i)=='.')
                count++;
        }
        }
        
         
        return count;
        } 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop250Update = new javax.swing.JPopupMenu();
        updateItem = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtF210PID = new javax.swing.JTextField();
        txtF211Pname = new javax.swing.JTextField();
        txtF213PStd = new javax.swing.JTextField();
        txtF214PIns = new javax.swing.JTextField();
        txtF215PCon = new javax.swing.JTextField();
        txtF217PWei = new javax.swing.JTextField();
        txtF218PNCSA = new javax.swing.JTextField();
        txtF219PNOD = new javax.swing.JTextField();
        btn221PAdd = new javax.swing.JButton();
        spnnr216PLen = new javax.swing.JSpinner();
        spnnr220PQty = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbl211Pname = new javax.swing.JLabel();
        lbl212PCat = new javax.swing.JLabel();
        lbl213PStd = new javax.swing.JLabel();
        lbl214PIns = new javax.swing.JLabel();
        lbl215PCon = new javax.swing.JLabel();
        lbl216PLen = new javax.swing.JLabel();
        lbl217PWei = new javax.swing.JLabel();
        lbl218PNCSA = new javax.swing.JLabel();
        lbl219PNOD = new javax.swing.JLabel();
        lbl220PQty = new javax.swing.JLabel();
        cmb212Pcat = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        btnDemo1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl250FProducts = new javax.swing.JTable();
        txtF250Search = new javax.swing.JTextField();
        btn251Search = new javax.swing.JButton();
        btn253Delete = new javax.swing.JButton();
        btn252ViewAll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtF210PID1 = new javax.swing.JTextField();
        txtF213PStd1 = new javax.swing.JTextField();
        txtF214PIns1 = new javax.swing.JTextField();
        txtF215PCon1 = new javax.swing.JTextField();
        txtF217PWei1 = new javax.swing.JTextField();
        txtF218PNCSA1 = new javax.swing.JTextField();
        txtF219PNOD1 = new javax.swing.JTextField();
        btn221PUpdate = new javax.swing.JButton();
        spnnr216PLen1 = new javax.swing.JSpinner();
        spnnr220PQty1 = new javax.swing.JSpinner();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        lbl211Pname1 = new javax.swing.JLabel();
        lbl212PCat1 = new javax.swing.JLabel();
        lbl213PStd1 = new javax.swing.JLabel();
        lbl214PIns1 = new javax.swing.JLabel();
        lbl215PCon1 = new javax.swing.JLabel();
        lbl216PLen1 = new javax.swing.JLabel();
        lbl217PWei1 = new javax.swing.JLabel();
        lbl218PNCSA1 = new javax.swing.JLabel();
        lbl219PNOD1 = new javax.swing.JLabel();
        lbl220PQty1 = new javax.swing.JLabel();
        cmb212Pcat1 = new javax.swing.JComboBox<>();
        jLabel45 = new javax.swing.JLabel();
        cmb211Pname1 = new javax.swing.JComboBox<>();
        btnUpdateQuantity = new javax.swing.JButton();

        updateItem.setText("jMenuItem1");
        updateItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateItemActionPerformed(evt);
            }
        });
        pop250Update.add(updateItem);

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        setPreferredSize(new java.awt.Dimension(790, 590));

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(790, 560));

        jLabel1.setText("Product ID");

        jLabel2.setText("Product Name");

        jLabel3.setText("Category");

        jLabel4.setText("Standard");

        jLabel5.setText("Insulation");

        jLabel6.setText("Conductor");

        jLabel7.setText("Length");

        jLabel8.setText("Approximate weight");

        jLabel9.setText("Nominal cross sectional area");

        jLabel10.setText("Nominal overall diameter");

        txtF210PID.setEditable(false);

        txtF211Pname.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF211PnameFocusLost(evt);
            }
        });

        txtF213PStd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF213PStdFocusLost(evt);
            }
        });
        txtF213PStd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF213PStdActionPerformed(evt);
            }
        });

        txtF214PIns.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF214PInsFocusLost(evt);
            }
        });

        txtF215PCon.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF215PConFocusLost(evt);
            }
        });
        txtF215PCon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF215PConActionPerformed(evt);
            }
        });

        txtF217PWei.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF217PWeiFocusLost(evt);
            }
        });
        txtF217PWei.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF217PWeiKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF217PWeiKeyTyped(evt);
            }
        });

        txtF218PNCSA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF218PNCSAFocusLost(evt);
            }
        });
        txtF218PNCSA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF218PNCSAKeyTyped(evt);
            }
        });

        txtF219PNOD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF219PNODFocusLost(evt);
            }
        });
        txtF219PNOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF219PNODActionPerformed(evt);
            }
        });
        txtF219PNOD.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF219PNODKeyTyped(evt);
            }
        });

        btn221PAdd.setText("Add");
        btn221PAdd.setMaximumSize(new java.awt.Dimension(129, 37));
        btn221PAdd.setMinimumSize(new java.awt.Dimension(129, 37));
        btn221PAdd.setPreferredSize(new java.awt.Dimension(90, 24));
        btn221PAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn221PAddActionPerformed(evt);
            }
        });

        spnnr216PLen.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnnr216PLen.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnnr216PLenStateChanged(evt);
            }
        });
        spnnr216PLen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnnr216PLenFocusLost(evt);
            }
        });

        spnnr220PQty.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel11.setText("m");

        jLabel12.setText("kg/km");

        jLabel13.setText("mm^2");

        jLabel14.setText("mm^2");

        lbl211Pname.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl211Pname.setForeground(new java.awt.Color(255, 0, 0));

        lbl212PCat.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl212PCat.setForeground(new java.awt.Color(255, 0, 0));

        lbl213PStd.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl213PStd.setForeground(new java.awt.Color(255, 0, 0));

        lbl214PIns.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl214PIns.setForeground(new java.awt.Color(255, 0, 0));

        lbl215PCon.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl215PCon.setForeground(new java.awt.Color(255, 0, 0));

        lbl216PLen.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl216PLen.setForeground(new java.awt.Color(255, 0, 0));

        lbl217PWei.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl217PWei.setForeground(new java.awt.Color(255, 0, 0));

        lbl218PNCSA.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl218PNCSA.setForeground(new java.awt.Color(255, 0, 0));

        lbl219PNOD.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl219PNOD.setForeground(new java.awt.Color(255, 0, 0));

        lbl220PQty.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl220PQty.setForeground(new java.awt.Color(255, 0, 0));

        cmb212Pcat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Screened Cables", "Outdoor Cables", "Indoor Cables", "Control Cables" }));
        cmb212Pcat.setSelectedIndex(-1);
        cmb212Pcat.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb212PcatFocusLost(evt);
            }
        });
        cmb212Pcat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb212PcatActionPerformed(evt);
            }
        });

        jLabel29.setText("Quantity");

        btnDemo1.setText("Demo");
        btnDemo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDemo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)
                        .addGap(102, 102, 102)
                        .addComponent(txtF211Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl211Pname, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(131, 131, 131)
                        .addComponent(cmb212Pcat, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl212PCat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addGap(130, 130, 130)
                        .addComponent(txtF213PStd, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl213PStd, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel5)
                        .addGap(127, 127, 127)
                        .addComponent(txtF214PIns, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl214PIns, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addGap(124, 124, 124)
                        .addComponent(txtF215PCon, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl215PCon, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel7)
                        .addGap(144, 144, 144)
                        .addComponent(spnnr216PLen, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel11)
                        .addGap(200, 200, 200)
                        .addComponent(lbl216PLen, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(68, 68, 68)
                        .addComponent(txtF217PWei, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12)
                        .addGap(176, 176, 176)
                        .addComponent(lbl217PWei, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(txtF218PNCSA, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel13)
                        .addGap(173, 173, 173)
                        .addComponent(lbl218PNCSA, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel10)
                        .addGap(39, 39, 39)
                        .addComponent(txtF219PNOD, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel14)
                        .addGap(173, 173, 173)
                        .addComponent(lbl219PNOD, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel29)
                        .addGap(135, 135, 135)
                        .addComponent(spnnr220PQty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(lbl220PQty, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(367, 367, 367)
                        .addComponent(btn221PAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addGap(123, 123, 123)
                .addComponent(txtF210PID, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDemo1)
                .addGap(57, 57, 57))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF210PID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnDemo1)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtF211Pname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl211Pname))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmb212Pcat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl212PCat))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addComponent(txtF213PStd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl213PStd))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel5))
                    .addComponent(txtF214PIns, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl214PIns))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel6))
                    .addComponent(txtF215PCon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl215PCon))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnnr216PLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl216PLen)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel11))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF217PWei, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl217PWei)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF218PNCSA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl218PNCSA)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF219PNOD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl219PNOD)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel29)
                    .addComponent(spnnr220PQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl220PQty))
                .addGap(30, 30, 30)
                .addComponent(btn221PAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane1.addTab("Add New Final Products", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tbl250FProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Category", "Standard", "Insulation", "Conductor", "Length", "Quantity", "Local Price", "Foriegn Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl250FProducts);

        txtF250Search.setText("Enter product ID or product name");
        txtF250Search.setPreferredSize(new java.awt.Dimension(198, 24));
        txtF250Search.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtF250SearchFocusGained(evt);
            }
        });

        btn251Search.setText("Search");
        btn251Search.setPreferredSize(new java.awt.Dimension(73, 24));
        btn251Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn251SearchActionPerformed(evt);
            }
        });

        btn253Delete.setText("Remove Selected Item");
        btn253Delete.setPreferredSize(new java.awt.Dimension(151, 24));
        btn253Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn253DeleteActionPerformed(evt);
            }
        });

        btn252ViewAll.setText("View All");
        btn252ViewAll.setPreferredSize(new java.awt.Dimension(79, 24));
        btn252ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn252ViewAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(txtF250Search, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn251Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn252ViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 757, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn253Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtF250Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn251Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn252ViewAll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(btn253Delete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("View Inventory", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel31.setText("Product ID");

        jLabel32.setText("Product Name");

        jLabel33.setText("Category");

        jLabel34.setText("Standard");

        jLabel35.setText("Insulation");

        jLabel36.setText("Conductor");

        jLabel37.setText("Length");

        jLabel38.setText("Approximate weight");

        jLabel39.setText("Nominal cross sectional area");

        jLabel40.setText("Nominal overall diameter");

        txtF210PID1.setEditable(false);

        txtF213PStd1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF213PStd1FocusLost(evt);
            }
        });
        txtF213PStd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF213PStd1ActionPerformed(evt);
            }
        });

        txtF214PIns1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF214PIns1FocusLost(evt);
            }
        });

        txtF215PCon1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF215PCon1FocusLost(evt);
            }
        });
        txtF215PCon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF215PCon1ActionPerformed(evt);
            }
        });

        txtF217PWei1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF217PWei1FocusLost(evt);
            }
        });
        txtF217PWei1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF217PWei1KeyTyped(evt);
            }
        });

        txtF218PNCSA1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF218PNCSA1FocusLost(evt);
            }
        });
        txtF218PNCSA1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF218PNCSA1KeyTyped(evt);
            }
        });

        txtF219PNOD1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF219PNOD1FocusLost(evt);
            }
        });
        txtF219PNOD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF219PNOD1ActionPerformed(evt);
            }
        });
        txtF219PNOD1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF219PNOD1KeyTyped(evt);
            }
        });

        btn221PUpdate.setText("Update");
        btn221PUpdate.setMaximumSize(new java.awt.Dimension(129, 37));
        btn221PUpdate.setMinimumSize(new java.awt.Dimension(129, 37));
        btn221PUpdate.setPreferredSize(new java.awt.Dimension(90, 24));
        btn221PUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn221PUpdateActionPerformed(evt);
            }
        });

        spnnr216PLen1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        spnnr216PLen1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                spnnr216PLen1FocusLost(evt);
            }
        });

        spnnr220PQty1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jLabel41.setText("m");

        jLabel42.setText("kg/km");

        jLabel43.setText("mm^2");

        jLabel44.setText("mm^2");

        lbl211Pname1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl211Pname1.setForeground(new java.awt.Color(255, 0, 0));

        lbl212PCat1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl212PCat1.setForeground(new java.awt.Color(255, 0, 0));

        lbl213PStd1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl213PStd1.setForeground(new java.awt.Color(255, 0, 0));

        lbl214PIns1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl214PIns1.setForeground(new java.awt.Color(255, 0, 0));

        lbl215PCon1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl215PCon1.setForeground(new java.awt.Color(255, 0, 0));

        lbl216PLen1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl216PLen1.setForeground(new java.awt.Color(255, 0, 0));

        lbl217PWei1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl217PWei1.setForeground(new java.awt.Color(255, 0, 0));

        lbl218PNCSA1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl218PNCSA1.setForeground(new java.awt.Color(255, 0, 0));

        lbl219PNOD1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl219PNOD1.setForeground(new java.awt.Color(255, 0, 0));

        lbl220PQty1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lbl220PQty1.setForeground(new java.awt.Color(255, 0, 0));

        cmb212Pcat1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Screened Cables", "Outdoor Cables", "Indoor Cables", "Control Cables" }));
        cmb212Pcat1.setSelectedIndex(-1);
        cmb212Pcat1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb212Pcat1FocusLost(evt);
            }
        });
        cmb212Pcat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb212Pcat1ActionPerformed(evt);
            }
        });

        jLabel45.setText("Quantity");

        cmb211Pname1.setEditable(true);
        cmb211Pname1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb211Pname1FocusLost(evt);
            }
        });
        cmb211Pname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb211Pname1ActionPerformed(evt);
            }
        });
        cmb211Pname1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmb211Pname1PropertyChange(evt);
            }
        });

        btnUpdateQuantity.setText("Update Quantity");
        btnUpdateQuantity.setPreferredSize(new java.awt.Dimension(123, 24));
        btnUpdateQuantity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateQuantityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(123, 123, 123)
                        .addComponent(txtF210PID1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(130, 130, 130)
                        .addComponent(txtF213PStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl213PStd1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(127, 127, 127)
                        .addComponent(txtF214PIns1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl214PIns1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addGap(124, 124, 124)
                        .addComponent(txtF215PCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbl215PCon1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(144, 144, 144)
                        .addComponent(spnnr216PLen1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel41)
                        .addGap(200, 200, 200)
                        .addComponent(lbl216PLen1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(68, 68, 68)
                        .addComponent(txtF217PWei1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel42)
                        .addGap(176, 176, 176)
                        .addComponent(lbl217PWei1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(txtF218PNCSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel43)
                        .addGap(173, 173, 173)
                        .addComponent(lbl218PNCSA1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel40)
                        .addGap(39, 39, 39)
                        .addComponent(txtF219PNOD1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jLabel44)
                        .addGap(173, 173, 173)
                        .addComponent(lbl219PNOD1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel45)
                        .addGap(135, 135, 135)
                        .addComponent(spnnr220PQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(216, 216, 216)
                        .addComponent(lbl220PQty1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jLabel32))
                        .addGap(102, 102, 102)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmb211Pname1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb212Pcat1, 0, 298, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl212PCat1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl211Pname1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnUpdateQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn221PUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel31))
                    .addComponent(txtF210PID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel32))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbl211Pname1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(cmb211Pname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel33))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(cmb212Pcat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl212PCat1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel34))
                    .addComponent(txtF213PStd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl213PStd1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel35))
                    .addComponent(txtF214PIns1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl214PIns1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel36))
                    .addComponent(txtF215PCon1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl215PCon1))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnnr216PLen1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl216PLen1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel41))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF217PWei1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl217PWei1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel38)
                            .addComponent(jLabel42))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF218PNCSA1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl218PNCSA1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel39)
                            .addComponent(jLabel43))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtF219PNOD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl219PNOD1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel40)
                            .addComponent(jLabel44))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addComponent(spnnr220PQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl220PQty1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn221PUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Update Details", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 786, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtF213PStdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF213PStdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF213PStdActionPerformed

    private void txtF215PConActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF215PConActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF215PConActionPerformed

    private void txtF219PNODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF219PNODActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF219PNODActionPerformed

    private void cmb212PcatFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb212PcatFocusLost
        stLbl.CheckComboBox(cmb212Pcat, lbl212PCat);
    }//GEN-LAST:event_cmb212PcatFocusLost

    private void spnnr216PLenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnnr216PLenFocusLost
        stLbl.CheckSpinner(spnnr216PLen, lbl216PLen);
    }//GEN-LAST:event_spnnr216PLenFocusLost

    private void txtF250SearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF250SearchFocusGained
        txtF250Search.setText("");
    }//GEN-LAST:event_txtF250SearchFocusGained

    private void btn221PAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn221PAddActionPerformed
        txtF211Pname.requestFocus();
        cmb212Pcat.requestFocus();
        txtF213PStd.requestFocus();
        txtF214PIns.requestFocus();
        txtF215PCon.requestFocus();
        spnnr216PLen.requestFocus();
        txtF217PWei.requestFocus();
        txtF218PNCSA.requestFocus();
        txtF219PNOD.requestFocus();
        spnnr220PQty.requestFocus();
        btn221PAdd.requestFocus();
        
        
        if(((((((((!lbl211Pname.getText().isEmpty() || !lbl212PCat.getText().isEmpty()) || !lbl213PStd.getText().isEmpty()) || !lbl214PIns.getText().isEmpty()) || !lbl215PCon.getText().isEmpty()) || !lbl216PLen.getText().isEmpty()) || !lbl217PWei.getText().isEmpty()) || !lbl218PNCSA.getText().isEmpty()) || !lbl219PNOD.getText().isEmpty()) || !lbl220PQty.getText().isEmpty() || cmb212Pcat.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        } 
        else {
            int option = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(option==JOptionPane.YES_OPTION){
                wdba.AddFinishedProduct(txtF210PID, txtF211Pname,String.valueOf(cmb212Pcat.getSelectedItem()), txtF213PStd, txtF214PIns, txtF215PCon, spnnr216PLen, txtF217PWei, txtF218PNCSA, txtF219PNOD, spnnr220PQty);
                JOptionPane.showMessageDialog(this,"Finished Product Added Successfully");
                ManageFinalProducts mgf = new ManageFinalProducts();
                SetPanel sp = new SetPanel();
                sp.SetPanel(mgf); 
            }
            
        }
    }//GEN-LAST:event_btn221PAddActionPerformed

    private void txtF211PnameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF211PnameFocusLost
        stLbl.CheckTextField(txtF211Pname,lbl211Pname);
    }//GEN-LAST:event_txtF211PnameFocusLost

    private void txtF213PStdFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF213PStdFocusLost
        stLbl.CheckTextField(txtF213PStd,lbl213PStd);
    }//GEN-LAST:event_txtF213PStdFocusLost

    private void txtF214PInsFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF214PInsFocusLost
      stLbl.CheckTextField(txtF214PIns,lbl214PIns);
    }//GEN-LAST:event_txtF214PInsFocusLost

    private void cmb212PcatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb212PcatActionPerformed
        btn221PAdd.requestFocus();
    }//GEN-LAST:event_cmb212PcatActionPerformed

    private void txtF215PConFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF215PConFocusLost
       stLbl.CheckTextField(txtF215PCon,lbl215PCon);
    }//GEN-LAST:event_txtF215PConFocusLost

    private void txtF217PWeiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF217PWeiFocusLost
        stLbl.CheckTextField(txtF217PWei,lbl217PWei);
    }//GEN-LAST:event_txtF217PWeiFocusLost

    private void txtF218PNCSAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF218PNCSAFocusLost
        stLbl.CheckTextField(txtF218PNCSA,lbl218PNCSA);
    }//GEN-LAST:event_txtF218PNCSAFocusLost

    private void txtF219PNODFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF219PNODFocusLost
        stLbl.CheckTextField(txtF219PNOD,lbl219PNOD);
    }//GEN-LAST:event_txtF219PNODFocusLost

    private void txtF213PStd1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF213PStd1FocusLost
        stLbl.CheckTextField(txtF213PStd1,lbl213PStd1);
    }//GEN-LAST:event_txtF213PStd1FocusLost

    private void txtF213PStd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF213PStd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF213PStd1ActionPerformed

    private void txtF214PIns1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF214PIns1FocusLost
         stLbl.CheckTextField(txtF214PIns1,lbl214PIns1);
    }//GEN-LAST:event_txtF214PIns1FocusLost

    private void txtF215PCon1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF215PCon1FocusLost
        stLbl.CheckTextField(txtF215PCon1,lbl215PCon1);
    }//GEN-LAST:event_txtF215PCon1FocusLost

    private void txtF215PCon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF215PCon1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF215PCon1ActionPerformed

    private void txtF217PWei1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF217PWei1FocusLost
        stLbl.CheckTextField(txtF217PWei1,lbl217PWei1,"number");
    }//GEN-LAST:event_txtF217PWei1FocusLost

    private void txtF218PNCSA1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF218PNCSA1FocusLost
        stLbl.CheckTextField(txtF218PNCSA1,lbl218PNCSA1,"number");
    }//GEN-LAST:event_txtF218PNCSA1FocusLost

    private void txtF219PNOD1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF219PNOD1FocusLost
        stLbl.CheckTextField(txtF219PNOD1,lbl219PNOD1,"number");
    }//GEN-LAST:event_txtF219PNOD1FocusLost

    private void txtF219PNOD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF219PNOD1ActionPerformed
        
    }//GEN-LAST:event_txtF219PNOD1ActionPerformed

    private void btn221PUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn221PUpdateActionPerformed
        cmb211Pname1.requestFocus();
        cmb212Pcat1.requestFocus();
        txtF213PStd1.requestFocus();
        txtF214PIns1.requestFocus();
        txtF215PCon1.requestFocus();
        spnnr216PLen1.requestFocus();
        txtF217PWei1.requestFocus();
        txtF218PNCSA1.requestFocus();
        txtF219PNOD1.requestFocus();
        spnnr220PQty1.requestFocus();
        btn221PUpdate.requestFocus();
         if(((((((((!lbl211Pname1.getText().isEmpty() || !lbl212PCat1.getText().isEmpty()) || !lbl213PStd1.getText().isEmpty()) || !lbl214PIns1.getText().isEmpty()) || !lbl215PCon1.getText().isEmpty()) || !lbl216PLen1.getText().isEmpty()) || !lbl217PWei1.getText().isEmpty()) || !lbl218PNCSA1.getText().isEmpty()) || !lbl219PNOD1.getText().isEmpty()) || !lbl220PQty1.getText().isEmpty() || cmb212Pcat1.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        } 
         else{
            
            int option = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(option==JOptionPane.YES_OPTION){
                wdba.UpdateFinishedProducts(String.valueOf(txtF210PID1.getText()),String.valueOf(cmb211Pname1.getSelectedItem()), String.valueOf(cmb212Pcat1.getSelectedItem()), txtF213PStd1, txtF214PIns1, txtF215PCon1, spnnr216PLen1, txtF217PWei1, txtF218PNCSA1, txtF219PNOD1, spnnr220PQty1);
                JOptionPane.showMessageDialog(this,"Finished Product Updated Successfully");
                ManageFinalProducts mgf = new ManageFinalProducts();
                SetPanel sp = new SetPanel();
                sp.SetPanel(mgf);
            }
            
           
         }
        
    }//GEN-LAST:event_btn221PUpdateActionPerformed

    private void spnnr216PLen1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_spnnr216PLen1FocusLost
        stLbl.CheckSpinner(spnnr216PLen1, lbl216PLen1);
    }//GEN-LAST:event_spnnr216PLen1FocusLost

    private void cmb212Pcat1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb212Pcat1FocusLost
        stLbl.CheckComboBox(cmb212Pcat1, lbl212PCat1);
    }//GEN-LAST:event_cmb212Pcat1FocusLost

    private void cmb212Pcat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb212Pcat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb212Pcat1ActionPerformed

    private void cmb211Pname1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb211Pname1FocusLost
       stLbl.CheckComboBox(cmb211Pname1, lbl211Pname1);
    }//GEN-LAST:event_cmb211Pname1FocusLost

    private void btn252ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn252ViewAllActionPerformed
        wdba.ViewAll(tbl250FProducts, "finishedProducts");
        SetTableHeaders();
    }//GEN-LAST:event_btn252ViewAllActionPerformed

    private void btn251SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn251SearchActionPerformed
        wdba.SearchByKeyWord(tbl250FProducts,"finishedProducts",String.valueOf(txtF250Search.getText()),"productId","name");
        SetTableHeaders();
    }//GEN-LAST:event_btn251SearchActionPerformed

    private void btn253DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn253DeleteActionPerformed
        if(tbl250FProducts.getRowCount()>0){
            int dialogResult = JOptionPane.showConfirmDialog(this,"Do you wish to proceed ?");
            if(dialogResult==JOptionPane.YES_OPTION){
                wdba.DeleteRow("finishedProducts", "productId", String.valueOf(tbl250FProducts.getValueAt(tbl250FProducts.getSelectedRow(),0)));
                wdba.ViewAll(tbl250FProducts, "finishedProducts");
                SetTableHeaders();
            }
        }
        else{
            JOptionPane.showMessageDialog(this,"Select an item to delete","Warning ",JOptionPane.WARNING_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btn253DeleteActionPerformed

    private void spnnr216PLenStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnnr216PLenStateChanged
        stLbl.CheckSpinner(spnnr216PLen,lbl216PLen);
    }//GEN-LAST:event_spnnr216PLenStateChanged

    private void txtF217PWeiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF217PWeiKeyTyped
        int count = dotCount(txtF217PWei);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
        
         
            
        

    }//GEN-LAST:event_txtF217PWeiKeyTyped

    private void txtF217PWeiKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF217PWeiKeyReleased
        
    }//GEN-LAST:event_txtF217PWeiKeyReleased

    private void txtF218PNCSAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF218PNCSAKeyTyped
        int count = dotCount(txtF218PNCSA);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
    }//GEN-LAST:event_txtF218PNCSAKeyTyped

    private void txtF219PNODKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF219PNODKeyTyped
        int count = dotCount(txtF219PNOD);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
    }//GEN-LAST:event_txtF219PNODKeyTyped

    private void cmb211Pname1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmb211Pname1PropertyChange
        if(cmb211Pname1.getSelectedIndex()!=0){
            txtF210PID1.setText("");
            cmb212Pcat1.setSelectedIndex(-1);
            txtF213PStd1.setText("");
            txtF214PIns1.setText("");
            txtF215PCon1.setText("");
            spnnr216PLen1.setValue(0);
            txtF217PWei1.setText("");
            txtF218PNCSA1.setText("");
            txtF219PNOD1.setText("");
            spnnr220PQty1.setValue(0);
        }
        wdba.RetrieveFinishedProduct(txtF210PID1,String.valueOf(cmb211Pname1.getSelectedItem()), cmb212Pcat1,txtF213PStd1, txtF214PIns1, txtF215PCon1, spnnr216PLen1, txtF217PWei1, txtF218PNCSA1, txtF219PNOD1, spnnr220PQty1);
    }//GEN-LAST:event_cmb211Pname1PropertyChange

    private void cmb211Pname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb211Pname1ActionPerformed
        cmb211Pname1.requestFocus();
        cmb212Pcat1.requestFocus();
        txtF213PStd1.requestFocus();
        txtF214PIns1.requestFocus();
        txtF215PCon1.requestFocus();
        spnnr216PLen1.requestFocus();
        txtF217PWei1.requestFocus();
        txtF218PNCSA1.requestFocus();
        txtF219PNOD1.requestFocus();
        spnnr220PQty1.requestFocus();
        btn221PUpdate.requestFocus();
    }//GEN-LAST:event_cmb211Pname1ActionPerformed

    private void btnDemo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDemo1ActionPerformed
       txtF211Pname.setText("Single core armoured");
       cmb212Pcat.setSelectedIndex(1);
       txtF213PStd.setText("BS 5467");
       txtF214PIns.setText("XLPE Compound");
       txtF215PCon.setText("Aluminium wires");
       spnnr216PLen.setValue(1000);
       txtF217PWei.setText("405");
       txtF218PNCSA.setText("2.5");
       txtF219PNOD.setText("17.5");
       spnnr220PQty.setValue(100);
    }//GEN-LAST:event_btnDemo1ActionPerformed

    private void btnUpdateQuantityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateQuantityActionPerformed
        if(cmb211Pname1.getSelectedIndex()!=-1){
            AssignFinishedProducts af = new AssignFinishedProducts(new WarehouseMain(), true,String.valueOf(txtF210PID1.getText()), String.valueOf(cmb211Pname1.getSelectedItem()),Integer.parseInt(String.valueOf(spnnr220PQty1.getValue())));
            af.setVisible(true);
        }
    }//GEN-LAST:event_btnUpdateQuantityActionPerformed

    private void updateItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateItemActionPerformed
        cmb211Pname1.setSelectedItem(tbl250FProducts.getValueAt(tbl250FProducts.getSelectedRow(),1));
        jTabbedPane1.setSelectedIndex(2);
       
    }//GEN-LAST:event_updateItemActionPerformed

    private void txtF217PWei1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF217PWei1KeyTyped
         int count = dotCount(txtF217PWei1);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
    }//GEN-LAST:event_txtF217PWei1KeyTyped

    private void txtF218PNCSA1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF218PNCSA1KeyTyped
         int count = dotCount(txtF218PNCSA1);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
    }//GEN-LAST:event_txtF218PNCSA1KeyTyped

    private void txtF219PNOD1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF219PNOD1KeyTyped
        int count = dotCount(txtF219PNOD1);
        if(count<1){
            if(Character.isDigit(evt.getKeyChar()) || evt.getKeyChar()=='.'){

            }
            else
                evt.consume();
               
        }
        else 
        {
            if(Character.isDigit(evt.getKeyChar())){
                
            }
            else
                evt.consume();
        }
    }//GEN-LAST:event_txtF219PNOD1KeyTyped

     private void SetTableHeaders()
    {
        TableColumnModel tcm = tbl250FProducts.getColumnModel();
        tcm.getColumn(0).setHeaderValue("Product ID");
        tcm.getColumn(1).setHeaderValue("Product Name");
        tcm.getColumn(2).setHeaderValue("Category");
        tcm.getColumn(3).setHeaderValue("Standard");
        tcm.getColumn(4).setHeaderValue("Insulation");
        tcm.getColumn(5).setHeaderValue("Conductor");
        tcm.getColumn(6).setHeaderValue("Length");
        tcm.getColumn(7).setHeaderValue("Quantity");
        tcm.getColumn(8).setHeaderValue("Local Price");
        tcm.getColumn(9).setHeaderValue("Foriegn Price");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn221PAdd;
    private javax.swing.JButton btn221PUpdate;
    private javax.swing.JButton btn251Search;
    private javax.swing.JButton btn252ViewAll;
    private javax.swing.JButton btn253Delete;
    private javax.swing.JButton btnDemo1;
    private javax.swing.JButton btnUpdateQuantity;
    private javax.swing.JComboBox<String> cmb211Pname1;
    private javax.swing.JComboBox<String> cmb212Pcat;
    private javax.swing.JComboBox<String> cmb212Pcat1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lbl211Pname;
    private javax.swing.JLabel lbl211Pname1;
    private javax.swing.JLabel lbl212PCat;
    private javax.swing.JLabel lbl212PCat1;
    private javax.swing.JLabel lbl213PStd;
    private javax.swing.JLabel lbl213PStd1;
    private javax.swing.JLabel lbl214PIns;
    private javax.swing.JLabel lbl214PIns1;
    private javax.swing.JLabel lbl215PCon;
    private javax.swing.JLabel lbl215PCon1;
    private javax.swing.JLabel lbl216PLen;
    private javax.swing.JLabel lbl216PLen1;
    private javax.swing.JLabel lbl217PWei;
    private javax.swing.JLabel lbl217PWei1;
    private javax.swing.JLabel lbl218PNCSA;
    private javax.swing.JLabel lbl218PNCSA1;
    private javax.swing.JLabel lbl219PNOD;
    private javax.swing.JLabel lbl219PNOD1;
    private javax.swing.JLabel lbl220PQty;
    private javax.swing.JLabel lbl220PQty1;
    private javax.swing.JPopupMenu pop250Update;
    private javax.swing.JSpinner spnnr216PLen;
    private javax.swing.JSpinner spnnr216PLen1;
    private javax.swing.JSpinner spnnr220PQty;
    private javax.swing.JSpinner spnnr220PQty1;
    private javax.swing.JTable tbl250FProducts;
    private javax.swing.JTextField txtF210PID;
    private javax.swing.JTextField txtF210PID1;
    private javax.swing.JTextField txtF211Pname;
    private javax.swing.JTextField txtF213PStd;
    private javax.swing.JTextField txtF213PStd1;
    private javax.swing.JTextField txtF214PIns;
    private javax.swing.JTextField txtF214PIns1;
    private javax.swing.JTextField txtF215PCon;
    private javax.swing.JTextField txtF215PCon1;
    private javax.swing.JTextField txtF217PWei;
    private javax.swing.JTextField txtF217PWei1;
    private javax.swing.JTextField txtF218PNCSA;
    private javax.swing.JTextField txtF218PNCSA1;
    private javax.swing.JTextField txtF219PNOD;
    private javax.swing.JTextField txtF219PNOD1;
    private javax.swing.JTextField txtF250Search;
    private javax.swing.JMenuItem updateItem;
    // End of variables declaration//GEN-END:variables
}
