/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRManagement;

import HRManagement.SupportedClasses.HRManagementDBAccess;
import java.awt.Component;
import javax.swing.JOptionPane;

/**
 *
 * @author ashanginige
 */
public class EditJobDetails extends javax.swing.JPanel {
    HRManagementDBAccess hrdac = new HRManagementDBAccess();

    /**
     * Creates new form EditJobDetails
     */
    public EditJobDetails() {
        initComponents();
        hrdac.LoadOccupationTable2(jTable640Search);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtF630JobID = new javax.swing.JTextField();
        txtF633BonusRate = new javax.swing.JTextField();
        txtF631JobTitle = new javax.swing.JTextField();
        cmb630Devision = new javax.swing.JComboBox<>();
        txtF632BasicSal = new javax.swing.JTextField();
        txtF634OTRate = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable640Search = new javax.swing.JTable();
        lbl622SrchErr = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        txtF641Search = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Occupation Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("OT Rate (Rs) :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 100, -1, -1));

        txtF630JobID.setEditable(false);
        txtF630JobID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF630JobIDActionPerformed(evt);
            }
        });
        jPanel1.add(txtF630JobID, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 34, 160, -1));

        txtF633BonusRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF633BonusRateKeyTyped(evt);
            }
        });
        jPanel1.add(txtF633BonusRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 64, 160, -1));

        txtF631JobTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF631JobTitleKeyTyped(evt);
            }
        });
        jPanel1.add(txtF631JobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 64, 160, -1));

        cmb630Devision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Human Resource", "Sales", "Manufacturing", "Customer Order Management", "Warehouse", "Distribution Management", "Technical Services", "Purchase" }));
        jPanel1.add(cmb630Devision, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 98, 200, -1));

        txtF632BasicSal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF632BasicSalKeyTyped(evt);
            }
        });
        jPanel1.add(txtF632BasicSal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 34, 160, -1));

        txtF634OTRate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF634OTRateKeyTyped(evt);
            }
        });
        jPanel1.add(txtF634OTRate, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 95, 160, -1));

        jLabel2.setText("Job Identification No :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel4.setText("Bonus Rate (Rs) :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 70, -1, -1));

        jLabel6.setText("Basic Salary (Rs) :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 40, -1, -1));

        jLabel7.setText("Job Title :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel8.setText("Devision :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 710, 160));

        jTable640Search.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTable640Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable640SearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable640Search);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 710, 210));

        lbl622SrchErr.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbl622SrchErr.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl622SrchErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 120, 20));

        jButton3.setText("Remove");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, 80, 40));

        jButton2.setText("Update Details");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 490, -1, 40));

        txtF641Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtF641SearchMouseClicked(evt);
            }
        });
        txtF641Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtF641SearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF641SearchKeyReleased(evt);
            }
        });
        add(txtF641Search, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 510, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRManagement/Images/search-25.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jButton1.setText("View All");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 160, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtF641SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtF641SearchMouseClicked
        txtF641Search.setText("");
    }//GEN-LAST:event_txtF641SearchMouseClicked

    private void txtF630JobIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF630JobIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF630JobIDActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String source_id=txtF630JobID.getText();
        
        if(txtF630JobID.getText().isEmpty()||txtF631JobTitle.getText().isEmpty()||cmb630Devision.getSelectedItem()==null||txtF632BasicSal.getText().isEmpty()||txtF633BonusRate.getText().isEmpty()||txtF634OTRate.getText().isEmpty()){
             JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }else{
            try {
                hrdac.UpdateOccupationDetails(txtF630JobID, txtF631JobTitle, cmb630Devision, txtF632BasicSal, txtF633BonusRate, txtF634OTRate, source_id);
                hrdac.LoadOccupationTable2(jTable640Search);
                JOptionPane.showMessageDialog(this,"Record succesfully updated","Success! ",JOptionPane.INFORMATION_MESSAGE);
                hrdac.ClearOccupation(txtF630JobID, txtF631JobTitle, cmb630Devision, txtF632BasicSal, txtF633BonusRate, txtF634OTRate);
            } catch (Exception e) {
                Component rootPane = null;
                JOptionPane.showMessageDialog(rootPane,"Unexpected error occured "+e, "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable640SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable640SearchMouseClicked
        hrdac.LoadOccupationtoForm(jTable640Search, txtF630JobID, txtF631JobTitle, cmb630Devision, txtF632BasicSal, txtF633BonusRate, txtF634OTRate);
    }//GEN-LAST:event_jTable640SearchMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        hrdac.LoadOccupationTable2(jTable640Search);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       int dialogResult = JOptionPane.showConfirmDialog(null, "Selected employee details will delete from the database! Are you sure to proceed?");
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                try {
                    hrdac.RemoveOccupation(txtF630JobID.getText());
                    JOptionPane.showMessageDialog(this,"Record Succesfully removed","Success! ",JOptionPane.INFORMATION_MESSAGE);
                    hrdac.LoadOccupationTable2(jTable640Search);
                    hrdac.ClearOccupation(txtF630JobID, txtF631JobTitle, cmb630Devision, txtF632BasicSal, txtF633BonusRate, txtF634OTRate);
                } catch (Exception e) {
                }
  
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtF641SearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF641SearchKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF641SearchKeyPressed

    private void txtF641SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF641SearchKeyReleased
        hrdac.SearchJob(jTable640Search, String.valueOf(txtF641Search.getText()));
    }//GEN-LAST:event_txtF641SearchKeyReleased

    private void txtF631JobTitleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF631JobTitleKeyTyped
        if (txtF631JobTitle.getText() != null){
            if (!(Character.isAlphabetic(evt.getKeyChar()))) {
                evt.consume(); // this could be a complecated relationship!
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtF631JobTitleKeyTyped

    private void txtF632BasicSalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF632BasicSalKeyTyped
       if (txtF632BasicSal.getText()!= null){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume(); // this could be a complecated relationship!
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtF632BasicSalKeyTyped

    private void txtF633BonusRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF633BonusRateKeyTyped
       if (txtF633BonusRate.getText()!= null){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume(); // this could be a complecated relationship!
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtF633BonusRateKeyTyped

    private void txtF634OTRateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF634OTRateKeyTyped
       if (txtF634OTRate.getText()!= null){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume(); // this could be a complecated relationship!
            }
        } else {
            evt.consume();
        }
    }//GEN-LAST:event_txtF634OTRateKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmb630Devision;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable640Search;
    private javax.swing.JLabel lbl622SrchErr;
    private javax.swing.JTextField txtF630JobID;
    private javax.swing.JTextField txtF631JobTitle;
    private javax.swing.JTextField txtF632BasicSal;
    private javax.swing.JTextField txtF633BonusRate;
    private javax.swing.JTextField txtF634OTRate;
    private javax.swing.JTextField txtF641Search;
    // End of variables declaration//GEN-END:variables
}
