/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRManagement;


import RootElement.DbConnect;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import HRManagement.SupportedClasses.TextValidator;
import HRManagement.SupportedClasses.SetLable;
import HRManagement.SupportedClasses.HRManagementDBAccess;
import HRManagement.SupportedClasses.GetJobIDNAME;
import java.awt.Image;
import java.io.File;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;



/**
 *
 * @author ashanginige
 */
public class EnrollEmployee extends javax.swing.JPanel {
    
    SetLable stLbl = new SetLable();
    HRManagementDBAccess hrdac = new HRManagementDBAccess();
    private boolean errorStatus = true;
    GetJobIDNAME jobidname = new GetJobIDNAME();
    
    Connection conn = null;
    ResultSet rs = null;
    Statement stmt = null;
  
    /**
     * Creates new form EnrollEmployee
     */
    public EnrollEmployee() throws SQLException {
        initComponents();
        hrdac.FillCombo(cmb600, "jobName", "occupation");
        hrdac.EmpIDIncrement(txtF600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txtF600 = new javax.swing.JTextField();
        txtF601 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmb600 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        lbl600 = new javax.swing.JLabel();
        lbl610ERImg = new javax.swing.JLabel();
        btn600 = new javax.swing.JButton();
        btn601EnrollEmp = new javax.swing.JButton();
        lbl602ERJob = new javax.swing.JLabel();
        lbl601ERName = new javax.swing.JLabel();
        lbl605ERCivil = new javax.swing.JLabel();
        lbl608ERRes = new javax.swing.JLabel();
        lbl609ERMob = new javax.swing.JLabel();
        txtF607ImagePath = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtF602 = new javax.swing.JTextField();
        rdBtn600 = new javax.swing.JRadioButton();
        rdBtn601 = new javax.swing.JRadioButton();
        rdBtn603 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rdBtn602 = new javax.swing.JRadioButton();
        jDate600DOB = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        lbl604ERGender = new javax.swing.JLabel();
        lbl603ERNic = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtF603 = new javax.swing.JTextField();
        txtF604 = new javax.swing.JTextField();
        txtF605 = new javax.swing.JTextField();
        txtF606 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lbl606ERAdd1 = new javax.swing.JLabel();
        lbl607ERAdd2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Employee ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 46, -1, -1));

        txtF600.setEditable(false);
        txtF600.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF600KeyReleased(evt);
            }
        });
        add(txtF600, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, 290, -1));

        txtF601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF601ActionPerformed(evt);
            }
        });
        txtF601.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF601FocusLost(evt);
            }
        });
        txtF601.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF601KeyReleased(evt);
            }
        });
        add(txtF601, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 73, 290, -1));

        jLabel3.setText("Name :");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 79, -1, -1));

        cmb600.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb600FocusLost(evt);
            }
        });
        add(cmb600, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 106, 290, -1));

        jLabel4.setText("Assigned Job :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 108, -1, -1));

        lbl600.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbl600.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbl600FocusLost(evt);
            }
        });
        add(lbl600, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 30, 200, 250));

        lbl610ERImg.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl610ERImg.setForeground(new java.awt.Color(255, 51, 0));
        lbl610ERImg.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                lbl610ERImgFocusLost(evt);
            }
        });
        add(lbl610ERImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 314, 20, 20));

        btn600.setText("Upload Image");
        btn600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn600ActionPerformed(evt);
            }
        });
        add(btn600, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 310, -1, -1));

        btn601EnrollEmp.setText("Enroll Employee");
        btn601EnrollEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn601EnrollEmpActionPerformed(evt);
            }
        });
        add(btn601EnrollEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 440, 140, 40));

        lbl602ERJob.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl602ERJob.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl602ERJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 110, 50, 20));

        lbl601ERName.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl601ERName.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl601ERName, new org.netbeans.lib.awtextra.AbsoluteConstraints(468, 76, 40, 20));

        lbl605ERCivil.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl605ERCivil, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 40, 20));

        lbl608ERRes.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl608ERRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 404, 40, 20));

        lbl609ERMob.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl609ERMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 435, 40, 20));

        txtF607ImagePath.setForeground(new java.awt.Color(255, 255, 255));
        txtF607ImagePath.setBorder(null);
        txtF607ImagePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF607ImagePathActionPerformed(evt);
            }
        });
        txtF607ImagePath.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF607ImagePathFocusLost(evt);
            }
        });
        add(txtF607ImagePath, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 490, 110, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Personal Details"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("NIC :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        txtF602.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF602ActionPerformed(evt);
            }
        });
        txtF602.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF602FocusLost(evt);
            }
        });
        txtF602.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF602KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF602KeyReleased(evt);
            }
        });
        jPanel1.add(txtF602, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 290, -1));

        buttonGroup1.add(rdBtn600);
        rdBtn600.setText("Male");
        rdBtn600.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn600ActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtn600, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        buttonGroup1.add(rdBtn601);
        rdBtn601.setText("Female");
        rdBtn601.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn601ActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtn601, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        buttonGroup2.add(rdBtn603);
        rdBtn603.setText("Unmarried");
        rdBtn603.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn603ActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtn603, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        jLabel6.setText("Gender :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel1.setText("Civil Status :");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        buttonGroup2.add(rdBtn602);
        rdBtn602.setText("Married");
        rdBtn602.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn602ActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtn602, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, -1, -1));

        jDate600DOB.setMaxSelectableDate(new java.util.Date(1471980689000L));
        jPanel1.add(jDate600DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, -1, -1));

        jLabel8.setText("Date Of Birth :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lbl604ERGender.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lbl604ERGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 40, 20));

        lbl603ERNic.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl603ERNic.setForeground(new java.awt.Color(255, 51, 0));
        jPanel1.add(lbl603ERNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 135, 40, 20));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 500, 280));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Contact Details"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Address :");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        txtF603.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF603FocusLost(evt);
            }
        });
        jPanel2.add(txtF603, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 290, -1));

        txtF604.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF604FocusLost(evt);
            }
        });
        jPanel2.add(txtF604, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 290, -1));

        txtF605.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF605ActionPerformed(evt);
            }
        });
        txtF605.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF605FocusLost(evt);
            }
        });
        txtF605.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF605KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF605KeyReleased(evt);
            }
        });
        jPanel2.add(txtF605, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 114, -1));

        txtF606.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF606FocusLost(evt);
            }
        });
        txtF606.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF606KeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF606KeyReleased(evt);
            }
        });
        jPanel2.add(txtF606, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 114, -1));

        jLabel7.setText("Telephone :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        lbl606ERAdd1.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl606ERAdd1.setForeground(new java.awt.Color(255, 51, 0));
        jPanel2.add(lbl606ERAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 40, 20));

        lbl607ERAdd2.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        lbl607ERAdd2.setForeground(new java.awt.Color(255, 51, 0));
        jPanel2.add(lbl607ERAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 73, 40, 20));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 500, 180));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Employee Image"));
        add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 10, 220, 280));

        jButton1.setForeground(new java.awt.Color(153, 153, 153));
        jButton1.setText("Demo Values");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtF601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF601ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF601ActionPerformed

    private void btn600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn600ActionPerformed

        String image_path=null;
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);

        try {
            File f = fc.getSelectedFile();
            image_path = f.getAbsolutePath();

            txtF607ImagePath.setText(image_path);
        } catch (Exception e) {
        }
        
        lbl610ERImg.setText("");
        lbl600.setIcon(new ImageIcon(new ImageIcon(image_path).getImage().getScaledInstance(200, 250, Image.SCALE_DEFAULT)));
        
    }//GEN-LAST:event_btn600ActionPerformed

    private void txtF600KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF600KeyReleased
                
    }//GEN-LAST:event_txtF600KeyReleased

    private void txtF601KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF601KeyReleased
        
        
    }//GEN-LAST:event_txtF601KeyReleased

    private void txtF605KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF605KeyReleased
      
    }//GEN-LAST:event_txtF605KeyReleased

    private void txtF606KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF606KeyReleased
        
    }//GEN-LAST:event_txtF606KeyReleased

    private void txtF605KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF605KeyTyped
       
        if (txtF605.getText().length() <= 9){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume();
            }
        } else {
            evt.consume();
       }
    }//GEN-LAST:event_txtF605KeyTyped

    private void txtF606KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF606KeyTyped
      
        if (txtF606.getText().length() <= 9){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume(); // this could be a complecated relationship!
            }
        } else {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtF606KeyTyped

    private void btn601EnrollEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn601EnrollEmpActionPerformed
        String dob="";
        try {
            java.util.Date dateFromDateChooser1 = jDate600DOB.getDate();
        dob = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1);
        } catch (Exception e) {
        }
        
        
        String job = String.valueOf(cmb600.getSelectedItem());
        GetJobIDNAME getJo = new GetJobIDNAME();

        txtF600.requestFocus();
        txtF601.requestFocus();
        txtF602.requestFocus();
        txtF603.requestFocus();
        txtF604.requestFocus();
        txtF605.requestFocus();
        txtF606.requestFocus();
        txtF607ImagePath.requestFocus();
        txtF601.requestFocus();
        
        if(txtF600.getText().isEmpty()||txtF601.getText().isEmpty()||txtF602.getText().isEmpty()||txtF603.getText().isEmpty()||txtF604.getText().isEmpty()||txtF605.getText().isEmpty()||txtF606.getText().isEmpty()||buttonGroup1.getElements()==null||buttonGroup2.getSelection()==null||cmb600.getSelectedIndex()==-1||txtF607ImagePath.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }else{
            try {  
                hrdac.AddEmpDetails(txtF600, txtF601, dob, getJo.ReturnJobID(job) , txtF602, rdBtn600, rdBtn601, rdBtn602, rdBtn603, txtF603, txtF604, txtF605, txtF606, txtF607ImagePath);
                System.out.println("Triggered"); 
                JOptionPane.showMessageDialog(this,"Record Succesfully added","Success! ",JOptionPane.INFORMATION_MESSAGE);
                hrdac.clearEmp(txtF600, txtF601, cmb600, txtF602, rdBtn600, rdBtn601, rdBtn602, rdBtn603, jDate600DOB, txtF603, txtF604, txtF605, txtF606, lbl600);
                hrdac.EmpIDIncrement(txtF600);
            } catch (Exception e) {
                System.out.println(e);
            } 
        }
        
        //opencv validating part
//        else if(hrdac.detectfaces(txtF607ImagePath.getText())==-1){
//           JOptionPane.showMessageDialog(null,"Please Enter a valid image of Employee! \n (No face detected!)");
//        }else if(hrdac.detectfaces(txtF607ImagePath.getText())==2){
//           JOptionPane.showMessageDialog(null,"Please Enter a valid image of Employee! \n (more than one face detected!)");        
//        }
        //opencv validating part

        
    }//GEN-LAST:event_btn601EnrollEmpActionPerformed

    private void txtF601FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF601FocusLost
       
        stLbl.CheckTextField(txtF601, lbl601ERName);
        
    }//GEN-LAST:event_txtF601FocusLost

    private void cmb600FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb600FocusLost
        
        stLbl.CheckComboBox(cmb600, lbl602ERJob);
        
    }//GEN-LAST:event_cmb600FocusLost

    private void txtF603FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF603FocusLost
        
        stLbl.CheckTextField(txtF603, lbl606ERAdd1);
        
    }//GEN-LAST:event_txtF603FocusLost

    private void txtF604FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF604FocusLost
        
        stLbl.CheckTextField(txtF604, lbl607ERAdd2);
        
    }//GEN-LAST:event_txtF604FocusLost

    private void txtF605FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF605FocusLost
        
        //stLbl.CheckTelephone(txtF605, lbl608ERRes, "text");
        
    }//GEN-LAST:event_txtF605FocusLost

    private void txtF606FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF606FocusLost
        
        //stLbl.CheckTelephone(txtF606, lbl609ERMob, "text");
        
    }//GEN-LAST:event_txtF606FocusLost

    private void lbl600FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbl600FocusLost
        
        
        
    }//GEN-LAST:event_lbl600FocusLost

    private void lbl610ERImgFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lbl610ERImgFocusLost
        
    }//GEN-LAST:event_lbl610ERImgFocusLost

    private void txtF607ImagePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF607ImagePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF607ImagePathActionPerformed

    private void txtF607ImagePathFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF607ImagePathFocusLost
        stLbl.CheckTextField(txtF607ImagePath, lbl610ERImg, "text");
    }//GEN-LAST:event_txtF607ImagePathFocusLost

    private void rdBtn602ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn602ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn602ActionPerformed

    private void rdBtn603ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn603ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn603ActionPerformed

    private void rdBtn601ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn601ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn601ActionPerformed

    private void rdBtn600ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn600ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn600ActionPerformed

    private void txtF602KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF602KeyReleased

    }//GEN-LAST:event_txtF602KeyReleased

    private void txtF602KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF602KeyTyped
       
    }//GEN-LAST:event_txtF602KeyTyped

    private void txtF602FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF602FocusLost
        
        stLbl.CheckNic(txtF602, lbl603ERNic, "text");
     
    }//GEN-LAST:event_txtF602FocusLost

    private void txtF602ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF602ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF602ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        txtF601.setText("V.A.R Tharuka");
        txtF602.setText("923210890V");
        txtF603.setText("No.25 Kandy Rd,");
        txtF604.setText("Malabe");
        txtF605.setText("0714990389");
        txtF606.setText("0353452344");
        cmb600.setSelectedItem("Sales Manager");
        rdBtn600.setSelected(true);
        rdBtn603.setSelected(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtF605ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF605ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF605ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn600;
    private javax.swing.JButton btn601EnrollEmp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb600;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate600DOB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbl600;
    private javax.swing.JLabel lbl601ERName;
    private javax.swing.JLabel lbl602ERJob;
    private javax.swing.JLabel lbl603ERNic;
    private javax.swing.JLabel lbl604ERGender;
    private javax.swing.JLabel lbl605ERCivil;
    private javax.swing.JLabel lbl606ERAdd1;
    private javax.swing.JLabel lbl607ERAdd2;
    private javax.swing.JLabel lbl608ERRes;
    private javax.swing.JLabel lbl609ERMob;
    private javax.swing.JLabel lbl610ERImg;
    private javax.swing.JRadioButton rdBtn600;
    private javax.swing.JRadioButton rdBtn601;
    private javax.swing.JRadioButton rdBtn602;
    private javax.swing.JRadioButton rdBtn603;
    private javax.swing.JTextField txtF600;
    private javax.swing.JTextField txtF601;
    private javax.swing.JTextField txtF602;
    private javax.swing.JTextField txtF603;
    private javax.swing.JTextField txtF604;
    private javax.swing.JTextField txtF605;
    private javax.swing.JTextField txtF606;
    private javax.swing.JTextField txtF607ImagePath;
    // End of variables declaration//GEN-END:variables
}
