/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HRManagement;

import RootElement.DbConnect;
import HRManagement.SupportedClasses.SetLable;
import javax.swing.JOptionPane;
import HRManagement.SupportedClasses.HRManagementDBAccess;
import HRManagement.SupportedClasses.GetJobIDNAME;
import java.awt.Image;
import java.io.File;
import java.io.PrintWriter;
import java.io.StringWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ashanginige
 */
public class UpdateDeleteEmpDetails extends javax.swing.JPanel {
    
    SetLable stLbl = new SetLable();
    private boolean errorStatus = true;
   
    HRManagementDBAccess hrdac = new HRManagementDBAccess();
    GetJobIDNAME getJobId = new GetJobIDNAME();
    
    /**
     * Creates new form UpdateDeleteDetails
     */
    public UpdateDeleteEmpDetails() {
        initComponents();
        
         hrdac.ViewAllEmp(tbl620SearchLoad);
        
         hrdac.FillCombo(cmb601AssignedJob, "jobName", "occupation");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        lbl610ERImg = new javax.swing.JLabel();
        lbl608ERRes = new javax.swing.JLabel();
        lbl609ERMob = new javax.swing.JLabel();
        lbl601ERName = new javax.swing.JLabel();
        lbl606ERAdd1 = new javax.swing.JLabel();
        lbl607ERAdd2 = new javax.swing.JLabel();
        lbl603ERNic = new javax.swing.JLabel();
        lbl602ERJob = new javax.swing.JLabel();
        lbl620Image = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl620SearchLoad = new javax.swing.JTable();
        txtF620SearchEmp = new javax.swing.JTextField();
        lbl622SrchErr = new javax.swing.JLabel();
        rdBtn622Male = new javax.swing.JRadioButton();
        btn623ViewAll = new javax.swing.JButton();
        txtF622EmpName = new javax.swing.JTextField();
        cmb601AssignedJob = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        rdBtn623Female = new javax.swing.JRadioButton();
        btn621Remove = new javax.swing.JButton();
        txtF628Image_path = new javax.swing.JTextField();
        btn622Update = new javax.swing.JButton();
        jDate620DOB = new com.toedter.calendar.JDateChooser();
        txtF623Add1 = new javax.swing.JTextField();
        txtF624Add2 = new javax.swing.JTextField();
        txtF621EmpID = new javax.swing.JTextField();
        txtF625Res = new javax.swing.JTextField();
        txtF626Mob = new javax.swing.JTextField();
        txtF627NIC = new javax.swing.JTextField();
        rdBtn620Unmarried = new javax.swing.JRadioButton();
        rdBtn621Married = new javax.swing.JRadioButton();
        btn620Upload = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl610ERImg.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl610ERImg.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl610ERImg, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 40, 20));

        lbl608ERRes.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl608ERRes.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl608ERRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 430, 30, 20));

        lbl609ERMob.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl609ERMob.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl609ERMob, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 430, 30, 20));

        lbl601ERName.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl601ERName.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl601ERName, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 275, 30, 20));

        lbl606ERAdd1.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl606ERAdd1.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl606ERAdd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 20, 20));

        lbl607ERAdd2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl607ERAdd2.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl607ERAdd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 30, 20));

        lbl603ERNic.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl603ERNic.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl603ERNic, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 335, 30, 20));

        lbl602ERJob.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lbl602ERJob.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl602ERJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 303, 20, 20));

        lbl620Image.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(lbl620Image, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 90, 100));

        tbl620SearchLoad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl620SearchLoad.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl620SearchLoadMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl620SearchLoad);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 60, 730, 140));

        txtF620SearchEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF620SearchEmpActionPerformed(evt);
            }
        });
        txtF620SearchEmp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF620SearchEmpKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF620SearchEmpKeyReleased(evt);
            }
        });
        add(txtF620SearchEmp, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 520, -1));

        lbl622SrchErr.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lbl622SrchErr.setForeground(new java.awt.Color(255, 51, 0));
        add(lbl622SrchErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 150, 20));

        buttonGroup2.add(rdBtn622Male);
        rdBtn622Male.setText("Male");
        add(rdBtn622Male, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, -1, -1));

        btn623ViewAll.setText("ViewAll");
        btn623ViewAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn623ViewAllActionPerformed(evt);
            }
        });
        add(btn623ViewAll, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 20, 160, -1));

        txtF622EmpName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF622EmpNameFocusLost(evt);
            }
        });
        add(txtF622EmpName, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 200, -1));

        cmb601AssignedJob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        cmb601AssignedJob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmb601AssignedJobFocusLost(evt);
            }
        });
        add(cmb601AssignedJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, 200, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HRManagement/Images/search-25.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        buttonGroup2.add(rdBtn623Female);
        rdBtn623Female.setText("Female");
        add(rdBtn623Female, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 270, -1, -1));

        btn621Remove.setText("Remove Employee");
        btn621Remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn621RemoveActionPerformed(evt);
            }
        });
        add(btn621Remove, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 150, 40));

        txtF628Image_path.setForeground(new java.awt.Color(255, 255, 255));
        txtF628Image_path.setBorder(null);
        txtF628Image_path.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtF628Image_pathActionPerformed(evt);
            }
        });
        add(txtF628Image_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 180, -1));

        btn622Update.setText("Update Details");
        btn622Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn622UpdateActionPerformed(evt);
            }
        });
        add(btn622Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, -1, 40));

        jDate620DOB.setMaxSelectableDate(new java.util.Date(1471980680000L));
        add(jDate620DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 360, 190, -1));

        txtF623Add1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF623Add1FocusLost(evt);
            }
        });
        add(txtF623Add1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 395, 200, -1));

        txtF624Add2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF624Add2FocusLost(evt);
            }
        });
        add(txtF624Add2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 395, 200, -1));

        txtF621EmpID.setEditable(false);
        txtF621EmpID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF621EmpIDFocusLost(evt);
            }
        });
        add(txtF621EmpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 200, -1));

        txtF625Res.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF625ResFocusLost(evt);
            }
        });
        txtF625Res.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF625ResKeyTyped(evt);
            }
        });
        add(txtF625Res, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 425, 200, -1));

        txtF626Mob.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF626MobFocusLost(evt);
            }
        });
        txtF626Mob.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtF626MobKeyTyped(evt);
            }
        });
        add(txtF626Mob, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 425, 200, -1));

        txtF627NIC.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtF627NICFocusLost(evt);
            }
        });
        add(txtF627NIC, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 200, -1));

        buttonGroup1.add(rdBtn620Unmarried);
        rdBtn620Unmarried.setText("Unmarried");
        rdBtn620Unmarried.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn620UnmarriedActionPerformed(evt);
            }
        });
        add(rdBtn620Unmarried, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, -1));

        buttonGroup1.add(rdBtn621Married);
        rdBtn621Married.setText("Married");
        rdBtn621Married.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtn621MarriedActionPerformed(evt);
            }
        });
        add(rdBtn621Married, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, -1, -1));

        btn620Upload.setText("Upload");
        btn620Upload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn620UploadActionPerformed(evt);
            }
        });
        add(btn620Upload, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 360, 100, -1));

        jLabel2.setText("Employee ID :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 245, -1, -1));

        jLabel4.setText("Date Of Birth :");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 365, -1, -1));

        jLabel6.setText("Assigned Job :");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 303, -1, -1));

        jLabel7.setText("Address :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, -1, -1));

        jLabel8.setText("Contact No :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, -1, -1));

        jLabel9.setText("NIC :");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 333, -1, -1));

        jLabel10.setText("Employee Name :");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 275, -1, -1));

        jLabel11.setText("Civil Status :");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, -1, -1));

        jLabel12.setText("Gender :");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 245, -1, -1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Selected Employee's Details"));
        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 740, 250));

        jButton1.setText("Reports");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 510, -1, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtn620UnmarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn620UnmarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn620UnmarriedActionPerformed

    private void rdBtn621MarriedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtn621MarriedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdBtn621MarriedActionPerformed

    private void txtF621EmpIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF621EmpIDFocusLost
       
       
        
    }//GEN-LAST:event_txtF621EmpIDFocusLost

    private void txtF622EmpNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF622EmpNameFocusLost
       
       stLbl.CheckTextField(txtF622EmpName, lbl601ERName);
        
    }//GEN-LAST:event_txtF622EmpNameFocusLost

    private void cmb601AssignedJobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb601AssignedJobFocusLost
        
        stLbl.CheckComboBox(cmb601AssignedJob, lbl602ERJob);
        
    }//GEN-LAST:event_cmb601AssignedJobFocusLost

    private void txtF627NICFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF627NICFocusLost
        
        stLbl.CheckNic(txtF627NIC, lbl603ERNic, "text");


    }//GEN-LAST:event_txtF627NICFocusLost

    private void txtF623Add1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF623Add1FocusLost
        
        stLbl.CheckTextField(txtF623Add1, lbl606ERAdd1);
        
    }//GEN-LAST:event_txtF623Add1FocusLost

    private void txtF624Add2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF624Add2FocusLost
       
        stLbl.CheckTextField(txtF624Add2, lbl607ERAdd2);
        
    }//GEN-LAST:event_txtF624Add2FocusLost

    private void txtF625ResFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF625ResFocusLost
        
        //stLbl.CheckTelephone(txtF625Res, lbl608ERRes, "text");
        
    }//GEN-LAST:event_txtF625ResFocusLost

    private void txtF626MobFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtF626MobFocusLost
        
       //stLbl.CheckTelephone( txtF626Mob, lbl609ERMob, "text");
        
    }//GEN-LAST:event_txtF626MobFocusLost

    private void txtF625ResKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF625ResKeyTyped
        
        if (txtF625Res.getText().length() <= 9){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume();
            }
        } else {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtF625ResKeyTyped

    private void txtF626MobKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF626MobKeyTyped
        
        if (txtF626Mob.getText().length() <= 9){
            if (!(Character.isDigit(evt.getKeyChar()))) {
                evt.consume();
            }
        } else {
            evt.consume();
        }
        
    }//GEN-LAST:event_txtF626MobKeyTyped

    private void btn622UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn622UpdateActionPerformed
        
        String source_id=txtF621EmpID.getText();
        
        java.util.Date dateFromDateChooser1 = jDate620DOB.getDate();
        String dob = String.format("%1$tY-%1$tm-%1$td", dateFromDateChooser1);
        
        String job = String.valueOf(cmb601AssignedJob.getSelectedItem());
        GetJobIDNAME getJo = new GetJobIDNAME();
        
        //txtF621EmpID.requestFocus();
        txtF622EmpName.requestFocus();
        txtF623Add1.requestFocus();
        txtF624Add2.requestFocus();
        txtF625Res.requestFocus();
        txtF626Mob.requestFocus();
        txtF627NIC.requestFocus();
        txtF628Image_path.requestFocus();
        //jLabel1.requestFocus();
        
        if(txtF622EmpName.getText().isEmpty()||txtF623Add1.getText().isEmpty()||txtF624Add2.getText().isEmpty()||txtF625Res.getText().isEmpty()||txtF626Mob.getText().isEmpty()||txtF627NIC.getText().isEmpty()||buttonGroup1.getSelection()==null||buttonGroup2.getSelection()==null){
            JOptionPane.showMessageDialog(this,"One or more fields contains invalid data","Warning ",JOptionPane.WARNING_MESSAGE);
        }else if(!txtF628Image_path.getText().isEmpty()){
            try {
                hrdac.UpdateEmpDetailsMethod1(txtF621EmpID, txtF622EmpName, dob, getJo.ReturnJobID(job), txtF627NIC, rdBtn622Male, rdBtn623Female, rdBtn621Married, rdBtn620Unmarried, txtF623Add1, txtF624Add2, txtF625Res, txtF626Mob, txtF628Image_path, source_id);
                SetPanel p1 = new SetPanel();
                UpdateDeleteEmpDetails d= new UpdateDeleteEmpDetails();
                p1.SetPanel(d);
            
                //hrdac.ViewAllEmp(tbl620SearchLoad);
            
            } catch (SQLException ex) {
                Logger.getLogger(UpdateDeleteEmpDetails.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(txtF628Image_path.getText().isEmpty()){
            try {
                hrdac.UpdateEmpDetailsMethod2(txtF621EmpID, txtF622EmpName, dob, getJo.ReturnJobID(job), txtF627NIC, rdBtn622Male, rdBtn623Female, rdBtn621Married, rdBtn620Unmarried, txtF623Add1, txtF624Add2, txtF625Res, txtF626Mob, source_id);
                SetPanel p1 = new SetPanel();
                UpdateDeleteEmpDetails d= new UpdateDeleteEmpDetails();
                p1.SetPanel(d);
                
                //hrdac.ViewAllEmp(tbl620SearchLoad);
                
            } catch (SQLException ex) {
                Logger.getLogger(UpdateDeleteEmpDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btn622UpdateActionPerformed

    private void txtF620SearchEmpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF620SearchEmpKeyTyped
               
    }//GEN-LAST:event_txtF620SearchEmpKeyTyped

    private void txtF620SearchEmpKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF620SearchEmpKeyReleased
        
        hrdac.Search(tbl620SearchLoad, String.valueOf(txtF620SearchEmp.getText()));
        
    }//GEN-LAST:event_txtF620SearchEmpKeyReleased

    private void btn621RemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn621RemoveActionPerformed

            int dialogResult = JOptionPane.showConfirmDialog(null, "Selected employee details will delete from the database! Are you sure to proceed?");
            if(dialogResult == JOptionPane.YES_OPTION)
            {
                hrdac.DeleteEmployee(txtF621EmpID.getText());
                JOptionPane.showMessageDialog(this,"Record Succesfully removed","Success! ",JOptionPane.INFORMATION_MESSAGE);
                hrdac.ViewAllEmp(tbl620SearchLoad);
            }

    }//GEN-LAST:event_btn621RemoveActionPerformed

    private void tbl620SearchLoadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl620SearchLoadMouseClicked
        
        hrdac.LoadtoForm(tbl620SearchLoad, txtF621EmpID, txtF622EmpName, jDate620DOB, txtF627NIC, rdBtn622Male, rdBtn623Female, rdBtn621Married, rdBtn620Unmarried, txtF623Add1, txtF624Add2, txtF625Res, txtF626Mob, lbl620Image,cmb601AssignedJob);
        
    }//GEN-LAST:event_tbl620SearchLoadMouseClicked

    private void btn620UploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn620UploadActionPerformed

    if(txtF621EmpID.getText().isEmpty()){
      JOptionPane.showMessageDialog(this,"Please Select a employee record to update the employee image!","Warning ",JOptionPane.WARNING_MESSAGE);

    }else if(lbl620Image.getIcon()==null){
        String image_path=null;
        JFileChooser fc = new JFileChooser();
        fc.showSaveDialog(this);

            try {
                File f = fc.getSelectedFile();
                image_path = f.getAbsolutePath();
                    txtF628Image_path.setText(image_path);
            } catch (Exception e) {
            
            }
        
            lbl610ERImg.setText("");
            lbl620Image.setIcon(new ImageIcon(new ImageIcon(image_path).getImage().getScaledInstance(90, 100, Image.SCALE_DEFAULT)));
    }else{
    
    int dialogResult = JOptionPane.showConfirmDialog(null, "Selected employee details will delete from the database! Are you sure to proceed?");

    if(dialogResult == JOptionPane.YES_OPTION)
            {
                String image_path=null;
                JFileChooser fc = new JFileChooser();
                fc.showSaveDialog(this);

                try {
                    File f = fc.getSelectedFile();
                    image_path = f.getAbsolutePath();

                    txtF628Image_path.setText(image_path);
                } catch (Exception e) {
            
                }
        
                lbl610ERImg.setText("");
                lbl620Image.setIcon(new ImageIcon(new ImageIcon(image_path).getImage().getScaledInstance(90, 100, Image.SCALE_DEFAULT)));
            }
    }
    }//GEN-LAST:event_btn620UploadActionPerformed

    private void txtF628Image_pathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF628Image_pathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF628Image_pathActionPerformed

    private void btn623ViewAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn623ViewAllActionPerformed
        hrdac.ViewAllEmp(tbl620SearchLoad);
    }//GEN-LAST:event_btn623ViewAllActionPerformed

    private void txtF620SearchEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtF620SearchEmpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtF620SearchEmpActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //String report = "src\\Reports\\GateP.jasper";
        // - - - - - - - - - 
//        String report = "/Users/ashanginige/Documents/ash ash/ITP_Project/src/HRManagement/Reports/EmployeeDetails.jasper";
//              
//         HashMap param = new HashMap();
//         param.put("id",txtF621EmpID.getText());
//         //param.put("to",to);
//       
//         Reports rep1 = new Reports(report,param);
//         rep1.setVisible(true);
         // - - - - - - - - - - - - - 
         
         EmployeeReports a = new EmployeeReports();
         a.setVisible(true);
   
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn620Upload;
    private javax.swing.JButton btn621Remove;
    private javax.swing.JButton btn622Update;
    private javax.swing.JButton btn623ViewAll;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cmb601AssignedJob;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDate620DOB;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl601ERName;
    private javax.swing.JLabel lbl602ERJob;
    private javax.swing.JLabel lbl603ERNic;
    private javax.swing.JLabel lbl606ERAdd1;
    private javax.swing.JLabel lbl607ERAdd2;
    private javax.swing.JLabel lbl608ERRes;
    private javax.swing.JLabel lbl609ERMob;
    private javax.swing.JLabel lbl610ERImg;
    private javax.swing.JLabel lbl620Image;
    private javax.swing.JLabel lbl622SrchErr;
    private javax.swing.JRadioButton rdBtn620Unmarried;
    private javax.swing.JRadioButton rdBtn621Married;
    private javax.swing.JRadioButton rdBtn622Male;
    private javax.swing.JRadioButton rdBtn623Female;
    private javax.swing.JTable tbl620SearchLoad;
    private javax.swing.JTextField txtF620SearchEmp;
    private javax.swing.JTextField txtF621EmpID;
    private javax.swing.JTextField txtF622EmpName;
    private javax.swing.JTextField txtF623Add1;
    private javax.swing.JTextField txtF624Add2;
    private javax.swing.JTextField txtF625Res;
    private javax.swing.JTextField txtF626Mob;
    private javax.swing.JTextField txtF627NIC;
    private javax.swing.JTextField txtF628Image_path;
    // End of variables declaration//GEN-END:variables
}
